# 03 — Derived Healthcare Capacity Metrics

## Project: System Capacity & Care Load Analytics for Unaccompanied Children

### Step 3A — Load Validated Dataset and Confirm Metric Input Readiness

This notebook follows the project guideline section: **Derived Healthcare Capacity Metrics**.

The goal of this step is to:
- Load the validated dataset created in Notebook 02
- Confirm required input columns
- Confirm logical anomaly flag columns
- Review data types
- Confirm the dataset is ready for healthcare capacity metric engineering

No derived metric calculation, KPI calculation, visualization, or business insight generation is performed in this step.

In [1]:
# ============================================================
# Step 3A — Load Validated Dataset and Confirm Metric Input Readiness
# Project: System Capacity & Care Load Analytics for Unaccompanied Children
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path

# Display settings for better notebook readability
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)
pd.set_option("display.max_colwidth", 100)

print("Step 3A — Load Validated Dataset and Confirm Metric Input Readiness")
print("=" * 85)

# ------------------------------------------------------------
# 1. Project paths
# ------------------------------------------------------------

PROJECT_ROOT = Path.cwd().parent

DATA_CLEANED_DIR = PROJECT_ROOT / "data" / "cleaned"
DATA_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

VALIDATED_FILE_PATH = DATA_CLEANED_DIR / "02_validated_uac_data.csv"

print("Project paths configured successfully.")
print(f"Project root: {PROJECT_ROOT}")
print(f"Validated input file: {VALIDATED_FILE_PATH}")

# ------------------------------------------------------------
# 2. Check if validated file exists
# ------------------------------------------------------------

validated_file_exists = VALIDATED_FILE_PATH.exists()

print(f"\nValidated input file exists: {validated_file_exists}")

if not validated_file_exists:
    raise FileNotFoundError(
        f"Validated dataset not found at: {VALIDATED_FILE_PATH}. "
        "Please complete Notebook 02 Step 2E before running Notebook 03."
    )

# ------------------------------------------------------------
# 3. Load validated dataset
# ------------------------------------------------------------

df_hhs_metrics = pd.read_csv(VALIDATED_FILE_PATH)

print("\nValidated dataset loaded successfully.")
print(f"Dataset shape: {df_hhs_metrics.shape[0]:,} rows × {df_hhs_metrics.shape[1]:,} columns")

# ------------------------------------------------------------
# 4. Convert Date column back to datetime after CSV reload
# ------------------------------------------------------------

df_hhs_metrics["Date"] = pd.to_datetime(df_hhs_metrics["Date"], errors="coerce")

date_parse_errors = df_hhs_metrics["Date"].isna().sum()

print(f"\nDate parse errors after loading validated CSV: {date_parse_errors:,}")

if date_parse_errors > 0:
    print("\nRows with Date parse errors:")
    display(df_hhs_metrics[df_hhs_metrics["Date"].isna()])
else:
    print("Date column parsed successfully.")

# ------------------------------------------------------------
# 5. Required columns for derived capacity metrics
# ------------------------------------------------------------

required_metric_input_columns = [
    "Date",
    "Children apprehended and placed in CBP custody*",
    "Children in CBP custody",
    "Children transferred out of CBP custody",
    "Children in HHS Care",
    "Children discharged from HHS Care"
]

required_anomaly_flag_columns = [
    "transfer_exceeds_cbp_custody_flag",
    "discharge_exceeds_hhs_care_flag",
    "logical_constraint_anomaly_flag"
]

print("\nRequired metric input columns:")
for idx, col in enumerate(required_metric_input_columns, start=1):
    print(f"{idx}. {col}")

print("\nRequired anomaly flag columns:")
for idx, col in enumerate(required_anomaly_flag_columns, start=1):
    print(f"{idx}. {col}")

# ------------------------------------------------------------
# 6. Column availability check
# ------------------------------------------------------------

missing_metric_columns = [
    col for col in required_metric_input_columns
    if col not in df_hhs_metrics.columns
]

missing_flag_columns = [
    col for col in required_anomaly_flag_columns
    if col not in df_hhs_metrics.columns
]

print(f"\nMissing metric input columns: {len(missing_metric_columns)}")
print(f"Missing anomaly flag columns: {len(missing_flag_columns)}")

if missing_metric_columns:
    print("Missing metric columns:")
    print(missing_metric_columns)

if missing_flag_columns:
    print("Missing anomaly flag columns:")
    print(missing_flag_columns)

# ------------------------------------------------------------
# 7. Data type review
# ------------------------------------------------------------

print("\nCurrent data types:")
display(df_hhs_metrics.dtypes.to_frame(name="Data Type"))

# ------------------------------------------------------------
# 8. Preview validated input dataset
# ------------------------------------------------------------

print("\nValidated dataset preview:")
display(df_hhs_metrics.head())

print("\nValidated dataset tail:")
display(df_hhs_metrics.tail())

# ------------------------------------------------------------
# 9. Metric input readiness summary
# ------------------------------------------------------------

metric_input_readiness_summary = pd.DataFrame({
    "Readiness Check": [
        "Validated File Exists",
        "Rows Loaded",
        "Columns Loaded",
        "Expected Rows",
        "Expected Columns After Validation Flags",
        "Date Parse Errors",
        "Missing Metric Input Columns",
        "Missing Anomaly Flag Columns",
        "Date Column Type",
        "Dataset Chronological Order"
    ],
    "Result": [
        validated_file_exists,
        df_hhs_metrics.shape[0],
        df_hhs_metrics.shape[1],
        720,
        9,
        int(date_parse_errors),
        len(missing_metric_columns),
        len(missing_flag_columns),
        str(df_hhs_metrics["Date"].dtype),
        df_hhs_metrics["Date"].is_monotonic_increasing
    ]
})

print("\nMetric input readiness summary:")
display(metric_input_readiness_summary)

Step 3A — Load Validated Dataset and Confirm Metric Input Readiness
=====================================================================================
Project paths configured successfully.
Project root: C:\Users\Mohit\OneDrive\Documents\Data Analytics\Unified Mentor Projects\System Capacity & Care Load Analytics for Unaccompanied Children
Validated input file: C:\Users\Mohit\OneDrive\Documents\Data Analytics\Unified Mentor Projects\System Capacity & Care Load Analytics for Unaccompanied Children\data\cleaned\02_validated_uac_data.csv

Validated input file exists: True

Validated dataset loaded successfully.
Dataset shape: 720 rows × 9 columns

Date parse errors after loading validated CSV: 0
Date column parsed successfully.

Required metric input columns:
1. Date
2. Children apprehended and placed in CBP custody*
3. Children in CBP custody
4. Children transferred out of CBP custody
5. Children in HHS Care
6. Children discharged from HHS Care

Required anomaly flag columns:
1. transfer_exceeds_cbp_custody_flag
2. discharge_exceeds_hhs_care_flag
3. logical_constraint_anomaly_flag

Missing metric input columns: 0
Missing anomaly flag columns: 0

Current data types:

                                                      Data Type
Date                                             datetime64[ns]
Children apprehended and placed in CBP custody*           int64
Children in CBP custody                                   int64
Children transferred out of CBP custody                   int64
Children in HHS Care                                      int64
Children discharged from HHS Care                         int64
transfer_exceeds_cbp_custody_flag                          bool
discharge_exceeds_hhs_care_flag                            bool
logical_constraint_anomaly_flag                            bool

Validated dataset preview:

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care,transfer_exceeds_cbp_custody_flag,discharge_exceeds_hhs_care_flag,logical_constraint_anomaly_flag
0,2023-01-12,33,53,34,6566,436,False,False,False
1,2023-01-22,32,49,39,7122,227,False,False,False
2,2023-01-23,32,50,39,7280,181,False,False,False
3,2023-01-24,47,42,47,7433,175,True,False,True
4,2023-01-25,20,22,41,7538,180,True,False,True

Validated dataset tail:

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care,transfer_exceeds_cbp_custody_flag,discharge_exceeds_hhs_care_flag,logical_constraint_anomaly_flag
715,2025-12-15,11,42,9,2470,7,False,False,False
716,2025-12-16,8,54,15,2468,9,False,False,False
717,2025-12-17,7,31,11,2481,10,False,False,False
718,2025-12-18,11,50,6,2472,16,False,False,False
719,2025-12-21,6,18,11,2484,14,False,False,False

Metric input readiness summary:

                           Readiness Check          Result
0                    Validated File Exists            True
1                              Rows Loaded             720
2                           Columns Loaded               9
3                            Expected Rows             720
4  Expected Columns After Validation Flags               9
5                        Date Parse Errors               0
6             Missing Metric Input Columns               0
7             Missing Anomaly Flag Columns               0
8                         Date Column Type  datetime64[ns]
9              Dataset Chronological Order            True

## Step 3B — Create Core Healthcare Capacity Metrics

This step creates the core derived healthcare capacity metrics defined in the project guidelines.

The metrics created in this step are:
- Total System Load = Children in CBP custody + Children in HHS Care
- Net Daily Intake = Children transferred out of CBP custody − Children discharged from HHS Care
- Care Load Growth Rate = Day-over-day percentage change in Total System Load

No backlog indicator, rolling average, KPI summary, visualization, or business insight generation is performed in this step.

In [2]:
# ============================================================
# Step 3B — Create Core Healthcare Capacity Metrics
# Project: System Capacity & Care Load Analytics for Unaccompanied Children
# ============================================================

print("Step 3B — Create Core Healthcare Capacity Metrics")
print("=" * 75)

# ------------------------------------------------------------
# 1. Create working copy for metric engineering
# ------------------------------------------------------------

df_hhs_capacity = df_hhs_metrics.copy()

print("Working capacity metrics copy created successfully.")
print(f"Working dataset shape before metrics: {df_hhs_capacity.shape[0]:,} rows × {df_hhs_capacity.shape[1]:,} columns")

# ------------------------------------------------------------
# 2. Define source columns
# ------------------------------------------------------------

cbp_custody_col = "Children in CBP custody"
hhs_care_col = "Children in HHS Care"
transfer_col = "Children transferred out of CBP custody"
discharge_col = "Children discharged from HHS Care"

print("\nSource columns used for core capacity metrics:")
print(f"CBP custody column: {cbp_custody_col}")
print(f"HHS care column: {hhs_care_col}")
print(f"Transfer column: {transfer_col}")
print(f"Discharge column: {discharge_col}")

# ------------------------------------------------------------
# 3. Create Total System Load
# Guideline formula: CBP Custody + HHS Care
# ------------------------------------------------------------

df_hhs_capacity["total_system_load"] = (
    df_hhs_capacity[cbp_custody_col] + df_hhs_capacity[hhs_care_col]
)

# ------------------------------------------------------------
# 4. Create Net Daily Intake
# Guideline formula: Transfers into HHS − Discharges from HHS
# ------------------------------------------------------------

df_hhs_capacity["net_daily_intake"] = (
    df_hhs_capacity[transfer_col] - df_hhs_capacity[discharge_col]
)

# ------------------------------------------------------------
# 5. Create Care Load Growth Rate
# Guideline definition: Day-over-day percentage change
# ------------------------------------------------------------

df_hhs_capacity["care_load_growth_rate_pct"] = (
    df_hhs_capacity["total_system_load"]
    .pct_change()
    .mul(100)
)

# First row has no previous day for comparison, so growth rate is set to 0 for safe interpretation
df_hhs_capacity["care_load_growth_rate_pct"] = (
    df_hhs_capacity["care_load_growth_rate_pct"]
    .fillna(0)
    .round(2)
)

print("\nCore capacity metrics created successfully:")
print("1. total_system_load")
print("2. net_daily_intake")
print("3. care_load_growth_rate_pct")

# ------------------------------------------------------------
# 6. Metric validation checks
# ------------------------------------------------------------

metric_columns = [
    "total_system_load",
    "net_daily_intake",
    "care_load_growth_rate_pct"
]

metric_validation_summary = []

for col in metric_columns:
    metric_validation_summary.append({
        "Metric Column": col,
        "Missing Values": df_hhs_capacity[col].isna().sum(),
        "Minimum Value": df_hhs_capacity[col].min(),
        "Maximum Value": df_hhs_capacity[col].max(),
        "Data Type": str(df_hhs_capacity[col].dtype)
    })

metric_validation_summary_df = pd.DataFrame(metric_validation_summary)

print("\nCore metric validation summary:")
display(metric_validation_summary_df)

# ------------------------------------------------------------
# 7. Preview core metric calculations
# ------------------------------------------------------------

core_metric_preview_columns = [
    "Date",
    cbp_custody_col,
    hhs_care_col,
    "total_system_load",
    transfer_col,
    discharge_col,
    "net_daily_intake",
    "care_load_growth_rate_pct",
    "logical_constraint_anomaly_flag"
]

print("\nCore metric calculation preview:")
display(df_hhs_capacity[core_metric_preview_columns].head(10))

print("\nCore metric calculation tail:")
display(df_hhs_capacity[core_metric_preview_columns].tail(10))

# ------------------------------------------------------------
# 8. Core metric engineering summary
# ------------------------------------------------------------

core_metric_engineering_summary = pd.DataFrame({
    "Metric Engineering Check": [
        "Rows Before Metrics",
        "Columns Before Metrics",
        "Rows After Metrics",
        "Columns After Metrics",
        "Metrics Created",
        "Total System Load Missing Values",
        "Net Daily Intake Missing Values",
        "Care Load Growth Rate Missing Values",
        "Rows Deleted or Modified"
    ],
    "Result": [
        df_hhs_metrics.shape[0],
        df_hhs_metrics.shape[1],
        df_hhs_capacity.shape[0],
        df_hhs_capacity.shape[1],
        len(metric_columns),
        int(df_hhs_capacity["total_system_load"].isna().sum()),
        int(df_hhs_capacity["net_daily_intake"].isna().sum()),
        int(df_hhs_capacity["care_load_growth_rate_pct"].isna().sum()),
        0
    ]
})

print("\nCore metric engineering summary:")
display(core_metric_engineering_summary)

Step 3B — Create Core Healthcare Capacity Metrics
===========================================================================
Working capacity metrics copy created successfully.
Working dataset shape before metrics: 720 rows × 9 columns

Source columns used for core capacity metrics:
CBP custody column: Children in CBP custody
HHS care column: Children in HHS Care
Transfer column: Children transferred out of CBP custody
Discharge column: Children discharged from HHS Care

Core capacity metrics created successfully:
1. total_system_load
2. net_daily_intake
3. care_load_growth_rate_pct

Core metric validation summary:

               Metric Column  Missing Values  Minimum Value  Maximum Value Data Type
0          total_system_load               0         2002.0       11762.00     int64
1           net_daily_intake               0         -465.0         206.00     int64
2  care_load_growth_rate_pct               0          -11.6           8.34   float64

Core metric calculation preview:

,Date,Children in CBP custody,Children in HHS Care,total_system_load,Children transferred out of CBP custody,Children discharged from HHS Care,net_daily_intake,care_load_growth_rate_pct,logical_constraint_anomaly_flag
0,2023-01-12,53,6566,6619,34,436,-402,0.00,False
1,2023-01-22,49,7122,7171,39,227,-188,8.34,False
2,2023-01-23,50,7280,7330,39,181,-142,2.22,False
3,2023-01-24,42,7433,7475,47,175,-128,1.98,True
4,2023-01-25,22,7538,7560,41,180,-139,1.14,True
5,2023-01-29,45,7472,7517,11,303,-292,-0.57,False
6,2023-01-30,54,7743,7797,29,196,-167,3.72,False
7,2023-01-31,36,7803,7839,36,158,-122,0.54,False
8,2023-02-01,32,7903,7935,27,231,-204,1.22,False
9,2023-02-02,13,7879,7892,23,298,-275,-0.54,True

Core metric calculation tail:

,Date,Children in CBP custody,Children in HHS Care,total_system_load,Children transferred out of CBP custody,Children discharged from HHS Care,net_daily_intake,care_load_growth_rate_pct,logical_constraint_anomaly_flag
710,2025-12-08,27,2440,2467,9,4,5,0.57,False
711,2025-12-09,30,2443,2473,7,8,-1,0.24,False
712,2025-12-10,54,2439,2493,5,9,-4,0.81,False
713,2025-12-11,47,2437,2484,9,10,-1,-0.36,False
714,2025-12-14,35,2462,2497,4,8,-4,0.52,False
715,2025-12-15,42,2470,2512,9,7,2,0.60,False
716,2025-12-16,54,2468,2522,15,9,6,0.40,False
717,2025-12-17,31,2481,2512,11,10,1,-0.40,False
718,2025-12-18,50,2472,2522,6,16,-10,0.40,False
719,2025-12-21,18,2484,2502,11,14,-3,-0.79,False

Core metric engineering summary:

               Metric Engineering Check  Result
0                   Rows Before Metrics     720
1                Columns Before Metrics       9
2                    Rows After Metrics     720
3                 Columns After Metrics      12
4                       Metrics Created       3
5      Total System Load Missing Values       0
6       Net Daily Intake Missing Values       0
7  Care Load Growth Rate Missing Values       0
8              Rows Deleted or Modified       0

## Step 3C — Backlog Indicator Foundation

This step creates the foundation for the guideline-defined backlog indicator.

The project guideline defines the Backlog Indicator as: **Sustained positive net intake over time**.

The goal of this step is to create:
- Positive net intake flag
- Net intake direction label
- Cumulative net intake pressure
- Consecutive positive net intake days

No rolling averages, KPI summary, visualization, or business insight generation is performed in this step.

In [3]:
# ============================================================
# Step 3C — Backlog Indicator Foundation
# Project: System Capacity & Care Load Analytics for Unaccompanied Children
# ============================================================

print("Step 3C — Backlog Indicator Foundation")
print("=" * 75)

# ------------------------------------------------------------
# 1. Confirm input dataset from Step 3B
# ------------------------------------------------------------

print("Input dataset for backlog foundation:")
print(f"Rows: {df_hhs_capacity.shape[0]:,}")
print(f"Columns before backlog foundation: {df_hhs_capacity.shape[1]:,}")

# ------------------------------------------------------------
# 2. Create positive net intake flag
# Guideline logic: sustained positive net intake over time
# ------------------------------------------------------------

df_hhs_capacity["positive_net_intake_flag"] = df_hhs_capacity["net_daily_intake"] > 0

# ------------------------------------------------------------
# 3. Create net intake direction label
# ------------------------------------------------------------

df_hhs_capacity["net_intake_direction"] = np.select(
    [
        df_hhs_capacity["net_daily_intake"] > 0,
        df_hhs_capacity["net_daily_intake"] < 0,
        df_hhs_capacity["net_daily_intake"] == 0
    ],
    [
        "Pressure: Transfers Exceed Discharges",
        "Relief: Discharges Exceed Transfers",
        "Balanced: Transfers Equal Discharges"
    ],
    default="Unknown"
)

# ------------------------------------------------------------
# 4. Create cumulative net intake pressure
# ------------------------------------------------------------

df_hhs_capacity["cumulative_net_intake_pressure"] = (
    df_hhs_capacity["net_daily_intake"].cumsum()
)

# ------------------------------------------------------------
# 5. Create consecutive positive net intake days
# ------------------------------------------------------------

positive_group = (
    df_hhs_capacity["positive_net_intake_flag"]
    != df_hhs_capacity["positive_net_intake_flag"].shift()
).cumsum()

df_hhs_capacity["consecutive_positive_net_intake_days"] = (
    df_hhs_capacity
    .groupby(positive_group)["positive_net_intake_flag"]
    .cumsum()
)

df_hhs_capacity.loc[
    ~df_hhs_capacity["positive_net_intake_flag"],
    "consecutive_positive_net_intake_days"
] = 0

df_hhs_capacity["consecutive_positive_net_intake_days"] = (
    df_hhs_capacity["consecutive_positive_net_intake_days"].astype("int64")
)

print("\nBacklog foundation columns created successfully:")
print("1. positive_net_intake_flag")
print("2. net_intake_direction")
print("3. cumulative_net_intake_pressure")
print("4. consecutive_positive_net_intake_days")

# ------------------------------------------------------------
# 6. Backlog foundation validation summary
# ------------------------------------------------------------

backlog_foundation_columns = [
    "positive_net_intake_flag",
    "net_intake_direction",
    "cumulative_net_intake_pressure",
    "consecutive_positive_net_intake_days"
]

backlog_foundation_validation_summary = []

for col in backlog_foundation_columns:
    backlog_foundation_validation_summary.append({
        "Column Name": col,
        "Missing Values": df_hhs_capacity[col].isna().sum(),
        "Data Type": str(df_hhs_capacity[col].dtype)
    })

backlog_foundation_validation_summary_df = pd.DataFrame(backlog_foundation_validation_summary)

print("\nBacklog foundation validation summary:")
display(backlog_foundation_validation_summary_df)

# ------------------------------------------------------------
# 7. Direction distribution
# ------------------------------------------------------------

net_intake_direction_distribution = (
    df_hhs_capacity["net_intake_direction"]
    .value_counts()
    .reset_index()
)

net_intake_direction_distribution.columns = [
    "Net Intake Direction",
    "Record Count"
]

print("\nNet intake direction distribution:")
display(net_intake_direction_distribution)

# ------------------------------------------------------------
# 8. Backlog foundation preview
# ------------------------------------------------------------

backlog_preview_columns = [
    "Date",
    "net_daily_intake",
    "positive_net_intake_flag",
    "net_intake_direction",
    "cumulative_net_intake_pressure",
    "consecutive_positive_net_intake_days",
    "logical_constraint_anomaly_flag"
]

print("\nBacklog foundation preview:")
display(df_hhs_capacity[backlog_preview_columns].head(15))

print("\nBacklog foundation tail:")
display(df_hhs_capacity[backlog_preview_columns].tail(15))

# ------------------------------------------------------------
# 9. Backlog foundation engineering summary
# ------------------------------------------------------------

backlog_foundation_engineering_summary = pd.DataFrame({
    "Backlog Foundation Check": [
        "Rows Before Backlog Foundation",
        "Columns Before Backlog Foundation",
        "Rows After Backlog Foundation",
        "Columns After Backlog Foundation",
        "Backlog Foundation Columns Created",
        "Positive Net Intake Days",
        "Maximum Consecutive Positive Net Intake Days",
        "Rows Deleted or Modified"
    ],
    "Result": [
        720,
        12,
        df_hhs_capacity.shape[0],
        df_hhs_capacity.shape[1],
        len(backlog_foundation_columns),
        int(df_hhs_capacity["positive_net_intake_flag"].sum()),
        int(df_hhs_capacity["consecutive_positive_net_intake_days"].max()),
        0
    ]
})

print("\nBacklog foundation engineering summary:")
display(backlog_foundation_engineering_summary)

Step 3C — Backlog Indicator Foundation
===========================================================================
Input dataset for backlog foundation:
Rows: 720
Columns before backlog foundation: 12

Backlog foundation columns created successfully:
1. positive_net_intake_flag
2. net_intake_direction
3. cumulative_net_intake_pressure
4. consecutive_positive_net_intake_days

Backlog foundation validation summary:

                            Column Name  Missing Values Data Type
0              positive_net_intake_flag               0      bool
1                  net_intake_direction               0    object
2        cumulative_net_intake_pressure               0     int64
3  consecutive_positive_net_intake_days               0     int64

Net intake direction distribution:

                    Net Intake Direction  Record Count
0    Relief: Discharges Exceed Transfers           475
1  Pressure: Transfers Exceed Discharges           238
2   Balanced: Transfers Equal Discharges             7

Backlog foundation preview:

,Date,net_daily_intake,positive_net_intake_flag,net_intake_direction,cumulative_net_intake_pressure,consecutive_positive_net_intake_days,logical_constraint_anomaly_flag
0,2023-01-12,-402,False,Relief: Discharges Exceed Transfers,-402,0,False
1,2023-01-22,-188,False,Relief: Discharges Exceed Transfers,-590,0,False
2,2023-01-23,-142,False,Relief: Discharges Exceed Transfers,-732,0,False
3,2023-01-24,-128,False,Relief: Discharges Exceed Transfers,-860,0,True
4,2023-01-25,-139,False,Relief: Discharges Exceed Transfers,-999,0,True
5,2023-01-29,-292,False,Relief: Discharges Exceed Transfers,-1291,0,False
6,2023-01-30,-167,False,Relief: Discharges Exceed Transfers,-1458,0,False
7,2023-01-31,-122,False,Relief: Discharges Exceed Transfers,-1580,0,False
8,2023-02-01,-204,False,Relief: Discharges Exceed Transfers,-1784,0,False
9,2023-02-02,-275,False,Relief: Discharges Exceed Transfers,-2059,0,True
10,2023-02-05,-327,False,Relief: Discharges Exceed Transfers,-2386,0,False
11,2023-02-06,-184,False,Relief: Discharges Exceed Transfers,-2570,0,False
12,2023-02-07,-180,False,Relief: Discharges Exceed Transfers,-2750,0,False
13,2023-02-08,-148,False,Relief: Discharges Exceed Transfers,-2898,0,False
14,2023-02-09,-192,False,Relief: Discharges Exceed Transfers,-3090,0,False

Backlog foundation tail:

,Date,net_daily_intake,positive_net_intake_flag,net_intake_direction,cumulative_net_intake_pressure,consecutive_positive_net_intake_days,logical_constraint_anomaly_flag
705,2025-12-01,-5,False,Relief: Discharges Exceed Transfers,-32197,0,False
706,2025-12-02,-2,False,Relief: Discharges Exceed Transfers,-32199,0,False
707,2025-12-03,1,True,Pressure: Transfers Exceed Discharges,-32198,1,False
708,2025-12-04,-6,False,Relief: Discharges Exceed Transfers,-32204,0,False
709,2025-12-07,1,True,Pressure: Transfers Exceed Discharges,-32203,1,False
710,2025-12-08,5,True,Pressure: Transfers Exceed Discharges,-32198,2,False
711,2025-12-09,-1,False,Relief: Discharges Exceed Transfers,-32199,0,False
712,2025-12-10,-4,False,Relief: Discharges Exceed Transfers,-32203,0,False
713,2025-12-11,-1,False,Relief: Discharges Exceed Transfers,-32204,0,False
714,2025-12-14,-4,False,Relief: Discharges Exceed Transfers,-32208,0,False
715,2025-12-15,2,True,Pressure: Transfers Exceed Discharges,-32206,1,False
716,2025-12-16,6,True,Pressure: Transfers Exceed Discharges,-32200,2,False
717,2025-12-17,1,True,Pressure: Transfers Exceed Discharges,-32199,3,False
718,2025-12-18,-10,False,Relief: Discharges Exceed Transfers,-32209,0,False
719,2025-12-21,-3,False,Relief: Discharges Exceed Transfers,-32212,0,False

Backlog foundation engineering summary:

                       Backlog Foundation Check  Result
0                Rows Before Backlog Foundation     720
1             Columns Before Backlog Foundation      12
2                 Rows After Backlog Foundation     720
3              Columns After Backlog Foundation      16
4            Backlog Foundation Columns Created       4
5                      Positive Net Intake Days     238
6  Maximum Consecutive Positive Net Intake Days      12
7                      Rows Deleted or Modified       0

## Step 3D — Final Backlog Indicator Classification

This step creates the final backlog indicator based on the project guideline definition: **Sustained positive net intake over time**.

The indicator uses consecutive positive net intake days:
- 0 days: No Current Backlog Pressure
- 1–2 days: Short-Term Intake Pressure
- 3–6 days: Sustained Backlog Pressure
- 7+ days: Prolonged Backlog Pressure

No rolling averages, variability analysis, strain window detection, visualization, or KPI summary is performed in this step.

In [4]:
# ============================================================
# Step 3D — Final Backlog Indicator Classification
# Project: System Capacity & Care Load Analytics for Unaccompanied Children
# ============================================================

print("Step 3D — Final Backlog Indicator Classification")
print("=" * 80)

# ------------------------------------------------------------
# 1. Confirm input dataset from Step 3C
# ------------------------------------------------------------

print("Input dataset for final backlog indicator:")
print(f"Rows: {df_hhs_capacity.shape[0]:,}")
print(f"Columns before final backlog indicator: {df_hhs_capacity.shape[1]:,}")

# ------------------------------------------------------------
# 2. Create final backlog indicator
# Guideline logic: sustained positive net intake over time
# ------------------------------------------------------------

df_hhs_capacity["backlog_indicator"] = np.select(
    [
        df_hhs_capacity["consecutive_positive_net_intake_days"] == 0,
        df_hhs_capacity["consecutive_positive_net_intake_days"].between(1, 2),
        df_hhs_capacity["consecutive_positive_net_intake_days"].between(3, 6),
        df_hhs_capacity["consecutive_positive_net_intake_days"] >= 7
    ],
    [
        "No Current Backlog Pressure",
        "Short-Term Intake Pressure",
        "Sustained Backlog Pressure",
        "Prolonged Backlog Pressure"
    ],
    default="Unknown"
)

# ------------------------------------------------------------
# 3. Create numeric backlog severity score
# ------------------------------------------------------------

backlog_severity_mapping = {
    "No Current Backlog Pressure": 0,
    "Short-Term Intake Pressure": 1,
    "Sustained Backlog Pressure": 2,
    "Prolonged Backlog Pressure": 3
}

df_hhs_capacity["backlog_severity_score"] = (
    df_hhs_capacity["backlog_indicator"]
    .map(backlog_severity_mapping)
    .astype("int64")
)

print("\nFinal backlog indicator columns created successfully:")
print("1. backlog_indicator")
print("2. backlog_severity_score")

# ------------------------------------------------------------
# 4. Backlog indicator distribution
# ------------------------------------------------------------

backlog_indicator_distribution = (
    df_hhs_capacity["backlog_indicator"]
    .value_counts()
    .reset_index()
)

backlog_indicator_distribution.columns = [
    "Backlog Indicator",
    "Record Count"
]

print("\nBacklog indicator distribution:")
display(backlog_indicator_distribution)

# ------------------------------------------------------------
# 5. Backlog severity distribution
# ------------------------------------------------------------

backlog_severity_distribution = (
    df_hhs_capacity["backlog_severity_score"]
    .value_counts()
    .sort_index()
    .reset_index()
)

backlog_severity_distribution.columns = [
    "Backlog Severity Score",
    "Record Count"
]

print("\nBacklog severity score distribution:")
display(backlog_severity_distribution)

# ------------------------------------------------------------
# 6. Final backlog indicator validation summary
# ------------------------------------------------------------

final_backlog_indicator_validation_summary = pd.DataFrame({
    "Backlog Indicator Check": [
        "Rows Checked",
        "Columns Before Final Indicator",
        "Columns After Final Indicator",
        "Backlog Indicator Missing Values",
        "Backlog Severity Score Missing Values",
        "Unique Backlog Indicator Labels",
        "Maximum Backlog Severity Score",
        "Rows Deleted or Modified"
    ],
    "Result": [
        df_hhs_capacity.shape[0],
        16,
        df_hhs_capacity.shape[1],
        int(df_hhs_capacity["backlog_indicator"].isna().sum()),
        int(df_hhs_capacity["backlog_severity_score"].isna().sum()),
        df_hhs_capacity["backlog_indicator"].nunique(),
        int(df_hhs_capacity["backlog_severity_score"].max()),
        0
    ]
})

print("\nFinal backlog indicator validation summary:")
display(final_backlog_indicator_validation_summary)

# ------------------------------------------------------------
# 7. Final backlog indicator preview
# ------------------------------------------------------------

final_backlog_preview_columns = [
    "Date",
    "net_daily_intake",
    "positive_net_intake_flag",
    "net_intake_direction",
    "consecutive_positive_net_intake_days",
    "backlog_indicator",
    "backlog_severity_score",
    "logical_constraint_anomaly_flag"
]

print("\nFinal backlog indicator preview:")
display(df_hhs_capacity[final_backlog_preview_columns].head(20))

print("\nFinal backlog indicator tail:")
display(df_hhs_capacity[final_backlog_preview_columns].tail(20))

Step 3D — Final Backlog Indicator Classification
================================================================================
Input dataset for final backlog indicator:
Rows: 720
Columns before final backlog indicator: 16

Final backlog indicator columns created successfully:
1. backlog_indicator
2. backlog_severity_score

Backlog indicator distribution:

             Backlog Indicator  Record Count
0  No Current Backlog Pressure           482
1   Short-Term Intake Pressure           142
2   Sustained Backlog Pressure            69
3   Prolonged Backlog Pressure            27

Backlog severity score distribution:

   Backlog Severity Score  Record Count
0                       0           482
1                       1           142
2                       2            69
3                       3            27

Final backlog indicator validation summary:

                 Backlog Indicator Check  Result
0                           Rows Checked     720
1         Columns Before Final Indicator      16
2          Columns After Final Indicator      18
3       Backlog Indicator Missing Values       0
4  Backlog Severity Score Missing Values       0
5        Unique Backlog Indicator Labels       4
6         Maximum Backlog Severity Score       3
7               Rows Deleted or Modified       0

Final backlog indicator preview:

,Date,net_daily_intake,positive_net_intake_flag,net_intake_direction,consecutive_positive_net_intake_days,backlog_indicator,backlog_severity_score,logical_constraint_anomaly_flag
0,2023-01-12,-402,False,Relief: Discharges Exceed Transfers,0,No Current Backlog Pressure,0,False
1,2023-01-22,-188,False,Relief: Discharges Exceed Transfers,0,No Current Backlog Pressure,0,False
2,2023-01-23,-142,False,Relief: Discharges Exceed Transfers,0,No Current Backlog Pressure,0,False
3,2023-01-24,-128,False,Relief: Discharges Exceed Transfers,0,No Current Backlog Pressure,0,True
4,2023-01-25,-139,False,Relief: Discharges Exceed Transfers,0,No Current Backlog Pressure,0,True
5,2023-01-29,-292,False,Relief: Discharges Exceed Transfers,0,No Current Backlog Pressure,0,False
6,2023-01-30,-167,False,Relief: Discharges Exceed Transfers,0,No Current Backlog Pressure,0,False
7,2023-01-31,-122,False,Relief: Discharges Exceed Transfers,0,No Current Backlog Pressure,0,False
8,2023-02-01,-204,False,Relief: Discharges Exceed Transfers,0,No Current Backlog Pressure,0,False
9,2023-02-02,-275,False,Relief: Discharges Exceed Transfers,0,No Current Backlog Pressure,0,True
10,2023-02-05,-327,False,Relief: Discharges Exceed Transfers,0,No Current Backlog Pressure,0,False
11,2023-02-06,-184,False,Relief: Discharges Exceed Transfers,0,No Current Backlog Pressure,0,False
12,2023-02-07,-180,False,Relief: Discharges Exceed Transfers,0,No Current Backlog Pressure,0,False
13,2023-02-08,-148,False,Relief: Discharges Exceed Transfers,0,No Current Backlog Pressure,0,False
14,2023-02-09,-192,False,Relief: Discharges Exceed Transfers,0,No Current Backlog Pressure,0,False
15,2023-02-12,-144,False,Relief: Discharges Exceed Transfers,0,No Current Backlog Pressure,0,False
16,2023-02-13,-72,False,Relief: Discharges Exceed Transfers,0,No Current Backlog Pressure,0,False
17,2023-02-14,-3,False,Relief: Discharges Exceed Transfers,0,No Current Backlog Pressure,0,False
18,2023-02-15,-118,False,Relief: Discharges Exceed Transfers,0,No Current Backlog Pressure,0,False
19,2023-02-16,-208,False,Relief: Discharges Exceed Transfers,0,No Current Backlog Pressure,0,False

Final backlog indicator tail:

,Date,net_daily_intake,positive_net_intake_flag,net_intake_direction,consecutive_positive_net_intake_days,backlog_indicator,backlog_severity_score,logical_constraint_anomaly_flag
700,2025-11-23,21,True,Pressure: Transfers Exceed Discharges,1,Short-Term Intake Pressure,1,False
701,2025-11-24,-4,False,Relief: Discharges Exceed Transfers,0,No Current Backlog Pressure,0,False
702,2025-11-25,3,True,Pressure: Transfers Exceed Discharges,1,Short-Term Intake Pressure,1,False
703,2025-11-27,1,True,Pressure: Transfers Exceed Discharges,2,Short-Term Intake Pressure,1,False
704,2025-11-30,10,True,Pressure: Transfers Exceed Discharges,3,Sustained Backlog Pressure,2,False
705,2025-12-01,-5,False,Relief: Discharges Exceed Transfers,0,No Current Backlog Pressure,0,False
706,2025-12-02,-2,False,Relief: Discharges Exceed Transfers,0,No Current Backlog Pressure,0,False
707,2025-12-03,1,True,Pressure: Transfers Exceed Discharges,1,Short-Term Intake Pressure,1,False
708,2025-12-04,-6,False,Relief: Discharges Exceed Transfers,0,No Current Backlog Pressure,0,False
709,2025-12-07,1,True,Pressure: Transfers Exceed Discharges,1,Short-Term Intake Pressure,1,False
710,2025-12-08,5,True,Pressure: Transfers Exceed Discharges,2,Short-Term Intake Pressure,1,False
711,2025-12-09,-1,False,Relief: Discharges Exceed Transfers,0,No Current Backlog Pressure,0,False
712,2025-12-10,-4,False,Relief: Discharges Exceed Transfers,0,No Current Backlog Pressure,0,False
713,2025-12-11,-1,False,Relief: Discharges Exceed Transfers,0,No Current Backlog Pressure,0,False
714,2025-12-14,-4,False,Relief: Discharges Exceed Transfers,0,No Current Backlog Pressure,0,False
715,2025-12-15,2,True,Pressure: Transfers Exceed Discharges,1,Short-Term Intake Pressure,1,False
716,2025-12-16,6,True,Pressure: Transfers Exceed Discharges,2,Short-Term Intake Pressure,1,False
717,2025-12-17,1,True,Pressure: Transfers Exceed Discharges,3,Sustained Backlog Pressure,2,False
718,2025-12-18,-10,False,Relief: Discharges Exceed Transfers,0,No Current Backlog Pressure,0,False
719,2025-12-21,-3,False,Relief: Discharges Exceed Transfers,0,No Current Backlog Pressure,0,False

## Step 3E — Save Derived Healthcare Capacity Metrics Outputs

This step completes Notebook 03 by saving the final derived healthcare capacity metrics outputs.

The goal of this step is to:
- Save the dataset with derived healthcare capacity metrics
- Save a capacity metrics summary
- Save the backlog indicator distribution
- Confirm output file locations

No rolling averages, trend analysis, visualization, pressure/stress analysis, or business recommendation generation is performed in this step.

In [5]:
# ============================================================
# Step 3E — Save Derived Healthcare Capacity Metrics Outputs
# Project: System Capacity & Care Load Analytics for Unaccompanied Children
# ============================================================

print("Step 3E — Save Derived Healthcare Capacity Metrics Outputs")
print("=" * 85)

# ------------------------------------------------------------
# 1. Ensure output directories exist
# ------------------------------------------------------------

DATA_CLEANED_DIR.mkdir(parents=True, exist_ok=True)
DATA_PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

print("Output directories verified successfully.")
print(f"Cleaned data directory: {DATA_CLEANED_DIR}")
print(f"Processed data directory: {DATA_PROCESSED_DIR}")

# ------------------------------------------------------------
# 2. Define Notebook 03 metric columns
# ------------------------------------------------------------

notebook_03_metric_columns = [
    "total_system_load",
    "net_daily_intake",
    "care_load_growth_rate_pct",
    "positive_net_intake_flag",
    "net_intake_direction",
    "cumulative_net_intake_pressure",
    "consecutive_positive_net_intake_days",
    "backlog_indicator",
    "backlog_severity_score"
]

print("\nNotebook 03 derived metric columns:")
for idx, col in enumerate(notebook_03_metric_columns, start=1):
    print(f"{idx}. {col}")

# ------------------------------------------------------------
# 3. Create final capacity metrics summary
# ------------------------------------------------------------

capacity_metrics_summary = pd.DataFrame({
    "Metric Summary Check": [
        "Rows in Final Metrics Dataset",
        "Columns in Final Metrics Dataset",
        "Notebook 03 Metric Columns Created",
        "Total System Load Minimum",
        "Total System Load Maximum",
        "Net Daily Intake Minimum",
        "Net Daily Intake Maximum",
        "Care Load Growth Rate Minimum (%)",
        "Care Load Growth Rate Maximum (%)",
        "Positive Net Intake Days",
        "Maximum Consecutive Positive Net Intake Days",
        "Unique Backlog Indicator Labels",
        "Maximum Backlog Severity Score",
        "Logical Anomaly Rows Preserved",
        "Rows Deleted or Modified"
    ],
    "Result": [
        df_hhs_capacity.shape[0],
        df_hhs_capacity.shape[1],
        len(notebook_03_metric_columns),
        int(df_hhs_capacity["total_system_load"].min()),
        int(df_hhs_capacity["total_system_load"].max()),
        int(df_hhs_capacity["net_daily_intake"].min()),
        int(df_hhs_capacity["net_daily_intake"].max()),
        float(df_hhs_capacity["care_load_growth_rate_pct"].min()),
        float(df_hhs_capacity["care_load_growth_rate_pct"].max()),
        int(df_hhs_capacity["positive_net_intake_flag"].sum()),
        int(df_hhs_capacity["consecutive_positive_net_intake_days"].max()),
        int(df_hhs_capacity["backlog_indicator"].nunique()),
        int(df_hhs_capacity["backlog_severity_score"].max()),
        int(df_hhs_capacity["logical_constraint_anomaly_flag"].sum()),
        0
    ]
})

print("\nCapacity metrics summary:")
display(capacity_metrics_summary)

# ------------------------------------------------------------
# 4. Create final backlog indicator distribution
# ------------------------------------------------------------

backlog_indicator_distribution_final = (
    df_hhs_capacity["backlog_indicator"]
    .value_counts()
    .reset_index()
)

backlog_indicator_distribution_final.columns = [
    "Backlog Indicator",
    "Record Count"
]

backlog_indicator_distribution_final["Record Percentage"] = (
    backlog_indicator_distribution_final["Record Count"]
    / backlog_indicator_distribution_final["Record Count"].sum()
    * 100
).round(2)

print("\nFinal backlog indicator distribution:")
display(backlog_indicator_distribution_final)

# ------------------------------------------------------------
# 5. Create backlog severity score distribution
# ------------------------------------------------------------

backlog_severity_distribution_final = (
    df_hhs_capacity["backlog_severity_score"]
    .value_counts()
    .sort_index()
    .reset_index()
)

backlog_severity_distribution_final.columns = [
    "Backlog Severity Score",
    "Record Count"
]

backlog_severity_distribution_final["Record Percentage"] = (
    backlog_severity_distribution_final["Record Count"]
    / backlog_severity_distribution_final["Record Count"].sum()
    * 100
).round(2)

print("\nFinal backlog severity score distribution:")
display(backlog_severity_distribution_final)

# ------------------------------------------------------------
# 6. Define output file paths
# ------------------------------------------------------------

derived_metrics_output_path = DATA_CLEANED_DIR / "03_derived_capacity_metrics_uac_data.csv"
capacity_metrics_summary_output_path = DATA_PROCESSED_DIR / "03_capacity_metrics_summary.csv"
backlog_indicator_distribution_output_path = DATA_PROCESSED_DIR / "03_backlog_indicator_distribution.csv"
backlog_severity_distribution_output_path = DATA_PROCESSED_DIR / "03_backlog_severity_distribution.csv"

# ------------------------------------------------------------
# 7. Save derived metrics dataset
# ------------------------------------------------------------

df_hhs_capacity.to_csv(derived_metrics_output_path, index=False)

print("\nDerived capacity metrics dataset saved successfully.")
print(f"File: {derived_metrics_output_path}")

# ------------------------------------------------------------
# 8. Save capacity metrics summary
# ------------------------------------------------------------

capacity_metrics_summary.to_csv(capacity_metrics_summary_output_path, index=False)

print("\nCapacity metrics summary saved successfully.")
print(f"File: {capacity_metrics_summary_output_path}")

# ------------------------------------------------------------
# 9. Save backlog indicator distribution
# ------------------------------------------------------------

backlog_indicator_distribution_final.to_csv(
    backlog_indicator_distribution_output_path,
    index=False
)

print("\nBacklog indicator distribution saved successfully.")
print(f"File: {backlog_indicator_distribution_output_path}")

# ------------------------------------------------------------
# 10. Save backlog severity distribution
# ------------------------------------------------------------

backlog_severity_distribution_final.to_csv(
    backlog_severity_distribution_output_path,
    index=False
)

print("\nBacklog severity distribution saved successfully.")
print(f"File: {backlog_severity_distribution_output_path}")

# ------------------------------------------------------------
# 11. Saved outputs summary
# ------------------------------------------------------------

saved_capacity_outputs_summary = pd.DataFrame({
    "Output Name": [
        "Derived Capacity Metrics Dataset",
        "Capacity Metrics Summary",
        "Backlog Indicator Distribution",
        "Backlog Severity Distribution"
    ],
    "File Path": [
        str(derived_metrics_output_path),
        str(capacity_metrics_summary_output_path),
        str(backlog_indicator_distribution_output_path),
        str(backlog_severity_distribution_output_path)
    ],
    "Expected Purpose": [
        "Final Notebook 03 dataset for trend and temporal analysis in Notebook 04",
        "Summary of derived healthcare capacity metrics",
        "Distribution of backlog indicator categories",
        "Distribution of numeric backlog severity scores"
    ]
})

print("\nSaved capacity outputs summary:")
display(saved_capacity_outputs_summary)

Step 3E — Save Derived Healthcare Capacity Metrics Outputs
=====================================================================================
Output directories verified successfully.
Cleaned data directory: C:\Users\Mohit\OneDrive\Documents\Data Analytics\Unified Mentor Projects\System Capacity & Care Load Analytics for Unaccompanied Children\data\cleaned
Processed data directory: C:\Users\Mohit\OneDrive\Documents\Data Analytics\Unified Mentor Projects\System Capacity & Care Load Analytics for Unaccompanied Children\data\processed

Notebook 03 derived metric columns:
1. total_system_load
2. net_daily_intake
3. care_load_growth_rate_pct
4. positive_net_intake_flag
5. net_intake_direction
6. cumulative_net_intake_pressure
7. consecutive_positive_net_intake_days
8. backlog_indicator
9. backlog_severity_score

Capacity metrics summary:

                            Metric Summary Check    Result
0                  Rows in Final Metrics Dataset    720.00
1               Columns in Final Metrics Dataset     18.00
2             Notebook 03 Metric Columns Created      9.00
3                      Total System Load Minimum   2002.00
4                      Total System Load Maximum  11762.00
5                       Net Daily Intake Minimum   -465.00
6                       Net Daily Intake Maximum    206.00
7              Care Load Growth Rate Minimum (%)    -11.60
8              Care Load Growth Rate Maximum (%)      8.34
9                       Positive Net Intake Days    238.00
10  Maximum Consecutive Positive Net Intake Days     12.00
11               Unique Backlog Indicator Labels      4.00
12                Maximum Backlog Severity Score      3.00
13                Logical Anomaly Rows Preserved     86.00
14                      Rows Deleted or Modified      0.00

Final backlog indicator distribution:

             Backlog Indicator  Record Count  Record Percentage
0  No Current Backlog Pressure           482              66.94
1   Short-Term Intake Pressure           142              19.72
2   Sustained Backlog Pressure            69               9.58
3   Prolonged Backlog Pressure            27               3.75

Final backlog severity score distribution:

   Backlog Severity Score  Record Count  Record Percentage
0                       0           482              66.94
1                       1           142              19.72
2                       2            69               9.58
3                       3            27               3.75

Derived capacity metrics dataset saved successfully.
File: C:\Users\Mohit\OneDrive\Documents\Data Analytics\Unified Mentor Projects\System Capacity & Care Load Analytics for Unaccompanied Children\data\cleaned\03_derived_capacity_metrics_uac_data.csv

Capacity metrics summary saved successfully.
File: C:\Users\Mohit\OneDrive\Documents\Data Analytics\Unified Mentor Projects\System Capacity & Care Load Analytics for Unaccompanied Children\data\processed\03_capacity_metrics_summary.csv

Backlog indicator distribution saved successfully.
File: C:\Users\Mohit\OneDrive\Documents\Data Analytics\Unified Mentor Projects\System Capacity & Care Load Analytics for Unaccompanied Children\data\processed\03_backlog_indicator_distribution.csv

Backlog severity distribution saved successfully.
File: C:\Users\Mohit\OneDrive\Documents\Data Analytics\Unified Mentor Projects\System Capacity & Care Load Analytics for Unaccompanied Children\data\processed\03_backlog_severity_distribution.csv

Saved capacity outputs summary:

,Output Name,File Path,Expected Purpose
0,Derived Capacity Metrics Dataset,C:\Users\Mohit\OneDrive\Documents\Data Analytics\Unified Mentor Projects\System Capacity & Care ...,Final Notebook 03 dataset for trend and temporal analysis in Notebook 04
1,Capacity Metrics Summary,C:\Users\Mohit\OneDrive\Documents\Data Analytics\Unified Mentor Projects\System Capacity & Care ...,Summary of derived healthcare capacity metrics
2,Backlog Indicator Distribution,C:\Users\Mohit\OneDrive\Documents\Data Analytics\Unified Mentor Projects\System Capacity & Care ...,Distribution of backlog indicator categories
3,Backlog Severity Distribution,C:\Users\Mohit\OneDrive\Documents\Data Analytics\Unified Mentor Projects\System Capacity & Care ...,Distribution of numeric backlog severity scores