# 04 — Trend and Temporal Analysis

## Project: System Capacity & Care Load Analytics for Unaccompanied Children

### Step 4A — Load Derived Capacity Metrics Dataset and Confirm Trend Input Readiness

This notebook follows the project guideline section: **Trend & Temporal Analysis**.

The goal of this step is to:
- Load the derived healthcare capacity metrics dataset created in Notebook 03
- Confirm required trend input columns
- Confirm date readiness
- Confirm chronological order
- Confirm the dataset is ready for daily, weekly, and monthly trend analysis

No trend aggregation, sustained high-load detection, early vs late comparison, visualization, or business insight generation is performed in this step.

In [12]:
# ============================================================
# Step 4A — Load Derived Capacity Metrics Dataset and Confirm Trend Input Readiness
# Project: System Capacity & Care Load Analytics for Unaccompanied Children
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path

# Display settings for notebook readability
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 140)
pd.set_option("display.max_colwidth", 120)

print("Step 4A — Load Derived Capacity Metrics Dataset and Confirm Trend Input Readiness")
print("=" * 95)

# ------------------------------------------------------------
# 1. Project paths
# ------------------------------------------------------------

PROJECT_ROOT = Path.cwd().parent

DATA_CLEANED_DIR = PROJECT_ROOT / "data" / "cleaned"
DATA_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

DERIVED_METRICS_FILE_PATH = DATA_CLEANED_DIR / "03_derived_capacity_metrics_uac_data.csv"

print("Project paths configured successfully.")
print(f"Project root: {PROJECT_ROOT}")
print(f"Derived metrics input file: {DERIVED_METRICS_FILE_PATH}")

# ------------------------------------------------------------
# 2. Check if Notebook 03 output exists
# ------------------------------------------------------------

derived_metrics_file_exists = DERIVED_METRICS_FILE_PATH.exists()

print(f"\nDerived metrics input file exists: {derived_metrics_file_exists}")

if not derived_metrics_file_exists:
    raise FileNotFoundError(
        f"Derived capacity metrics dataset not found at: {DERIVED_METRICS_FILE_PATH}. "
        "Please complete Notebook 03 Step 3E before running Notebook 04."
    )

# ------------------------------------------------------------
# 3. Load derived capacity metrics dataset
# ------------------------------------------------------------

df_hhs_trend = pd.read_csv(DERIVED_METRICS_FILE_PATH)

print("\nDerived capacity metrics dataset loaded successfully.")
print(f"Dataset shape: {df_hhs_trend.shape[0]:,} rows × {df_hhs_trend.shape[1]:,} columns")

# ------------------------------------------------------------
# 4. Convert Date column back to datetime after CSV reload
# ------------------------------------------------------------

df_hhs_trend["Date"] = pd.to_datetime(df_hhs_trend["Date"], errors="coerce")

date_parse_errors = df_hhs_trend["Date"].isna().sum()

print(f"\nDate parse errors after loading derived metrics CSV: {date_parse_errors:,}")

if date_parse_errors > 0:
    print("\nRows with Date parse errors:")
    display(df_hhs_trend[df_hhs_trend["Date"].isna()])
else:
    print("Date column parsed successfully.")

# ------------------------------------------------------------
# 5. Required columns for trend and temporal analysis
# ------------------------------------------------------------

required_trend_input_columns = [
    "Date",
    "Children in CBP custody",
    "Children in HHS Care",
    "Children transferred out of CBP custody",
    "Children discharged from HHS Care",
    "total_system_load",
    "net_daily_intake",
    "care_load_growth_rate_pct",
    "backlog_indicator",
    "backlog_severity_score",
    "logical_constraint_anomaly_flag"
]

print("\nRequired trend input columns:")
for idx, col in enumerate(required_trend_input_columns, start=1):
    print(f"{idx}. {col}")

# ------------------------------------------------------------
# 6. Column availability check
# ------------------------------------------------------------

missing_trend_input_columns = [
    col for col in required_trend_input_columns
    if col not in df_hhs_trend.columns
]

print(f"\nMissing trend input columns: {len(missing_trend_input_columns)}")

if missing_trend_input_columns:
    print("Missing trend input columns:")
    print(missing_trend_input_columns)

# ------------------------------------------------------------
# 7. Chronological order and date range check
# ------------------------------------------------------------

is_chronological = df_hhs_trend["Date"].is_monotonic_increasing
start_date = df_hhs_trend["Date"].min()
end_date = df_hhs_trend["Date"].max()
unique_reporting_dates = df_hhs_trend["Date"].nunique()

print("\nDate readiness check:")
print(f"Start date: {start_date.date()}")
print(f"End date: {end_date.date()}")
print(f"Unique reporting dates: {unique_reporting_dates:,}")
print(f"Dataset chronological order: {is_chronological}")

# ------------------------------------------------------------
# 8. Data type review
# ------------------------------------------------------------

print("\nCurrent data types:")
display(df_hhs_trend.dtypes.to_frame(name="Data Type"))

# ------------------------------------------------------------
# 9. Preview trend input dataset
# ------------------------------------------------------------

trend_preview_columns = [
    "Date",
    "Children in CBP custody",
    "Children in HHS Care",
    "total_system_load",
    "net_daily_intake",
    "care_load_growth_rate_pct",
    "backlog_indicator",
    "backlog_severity_score",
    "logical_constraint_anomaly_flag"
]

print("\nTrend input dataset preview:")
display(df_hhs_trend[trend_preview_columns].head(10))

print("\nTrend input dataset tail:")
display(df_hhs_trend[trend_preview_columns].tail(10))

# ------------------------------------------------------------
# 10. Trend input readiness summary
# ------------------------------------------------------------

trend_input_readiness_summary = pd.DataFrame({
    "Readiness Check": [
        "Derived Metrics File Exists",
        "Rows Loaded",
        "Columns Loaded",
        "Expected Rows",
        "Expected Columns From Notebook 03",
        "Date Parse Errors",
        "Missing Trend Input Columns",
        "Date Column Type",
        "Start Date",
        "End Date",
        "Unique Reporting Dates",
        "Dataset Chronological Order",
        "Logical Anomaly Rows Preserved",
        "Backlog Indicator Labels Available"
    ],
    "Result": [
        derived_metrics_file_exists,
        df_hhs_trend.shape[0],
        df_hhs_trend.shape[1],
        720,
        18,
        int(date_parse_errors),
        len(missing_trend_input_columns),
        str(df_hhs_trend["Date"].dtype),
        start_date.date(),
        end_date.date(),
        unique_reporting_dates,
        is_chronological,
        int(df_hhs_trend["logical_constraint_anomaly_flag"].sum()),
        df_hhs_trend["backlog_indicator"].nunique()
    ]
})

print("\nTrend input readiness summary:")
display(trend_input_readiness_summary)

Step 4A — Load Derived Capacity Metrics Dataset and Confirm Trend Input Readiness
===============================================================================================
Project paths configured successfully.
Project root: C:\Users\Mohit\OneDrive\Documents\Data Analytics\Unified Mentor Projects\System Capacity & Care Load Analytics for Unaccompanied Children
Derived metrics input file: C:\Users\Mohit\OneDrive\Documents\Data Analytics\Unified Mentor Projects\System Capacity & Care Load Analytics for Unaccompanied Children\data\cleaned\03_derived_capacity_metrics_uac_data.csv

Derived metrics input file exists: True

Derived capacity metrics dataset loaded successfully.
Dataset shape: 720 rows × 18 columns

Date parse errors after loading derived metrics CSV: 0
Date column parsed successfully.

Required trend input columns:
1. Date
2. Children in CBP custody
3. Children in HHS Care
4. Children transferred out of CBP custody
5. Children discharged from HHS Care
6. total_system_load
7. net_daily_intake
8. care_load_growth_rate_pct
9. backlog_indicator
10. backlog_severity_score
11. logical_constraint_anomaly_flag

Missing trend input columns: 0

Date readiness check:
Start date: 2023-01-12
End date: 2025-12-21
Unique reporting dates: 720
Dataset chronological order: True

Current data types:

                                                      Data Type
Date                                             datetime64[ns]
Children apprehended and placed in CBP custody*           int64
Children in CBP custody                                   int64
Children transferred out of CBP custody                   int64
Children in HHS Care                                      int64
Children discharged from HHS Care                         int64
transfer_exceeds_cbp_custody_flag                          bool
discharge_exceeds_hhs_care_flag                            bool
logical_constraint_anomaly_flag                            bool
total_system_load                                         int64
net_daily_intake                                          int64
care_load_growth_rate_pct                               float64
positive_net_intake_flag                                   bool
net_intake_direction                                     object
cumulative_net_intake_pressure                            int64
consecutive_positive_net_intake_days                      int64
backlog_indicator                                        object
backlog_severity_score                                    int64

Trend input dataset preview:

,Date,Children in CBP custody,Children in HHS Care,total_system_load,net_daily_intake,care_load_growth_rate_pct,backlog_indicator,backlog_severity_score,logical_constraint_anomaly_flag
0,2023-01-12,53,6566,6619,-402,0.00,No Current Backlog Pressure,0,False
1,2023-01-22,49,7122,7171,-188,8.34,No Current Backlog Pressure,0,False
2,2023-01-23,50,7280,7330,-142,2.22,No Current Backlog Pressure,0,False
3,2023-01-24,42,7433,7475,-128,1.98,No Current Backlog Pressure,0,True
4,2023-01-25,22,7538,7560,-139,1.14,No Current Backlog Pressure,0,True
5,2023-01-29,45,7472,7517,-292,-0.57,No Current Backlog Pressure,0,False
6,2023-01-30,54,7743,7797,-167,3.72,No Current Backlog Pressure,0,False
7,2023-01-31,36,7803,7839,-122,0.54,No Current Backlog Pressure,0,False
8,2023-02-01,32,7903,7935,-204,1.22,No Current Backlog Pressure,0,False
9,2023-02-02,13,7879,7892,-275,-0.54,No Current Backlog Pressure,0,True

Trend input dataset tail:

,Date,Children in CBP custody,Children in HHS Care,total_system_load,net_daily_intake,care_load_growth_rate_pct,backlog_indicator,backlog_severity_score,logical_constraint_anomaly_flag
710,2025-12-08,27,2440,2467,5,0.57,Short-Term Intake Pressure,1,False
711,2025-12-09,30,2443,2473,-1,0.24,No Current Backlog Pressure,0,False
712,2025-12-10,54,2439,2493,-4,0.81,No Current Backlog Pressure,0,False
713,2025-12-11,47,2437,2484,-1,-0.36,No Current Backlog Pressure,0,False
714,2025-12-14,35,2462,2497,-4,0.52,No Current Backlog Pressure,0,False
715,2025-12-15,42,2470,2512,2,0.60,Short-Term Intake Pressure,1,False
716,2025-12-16,54,2468,2522,6,0.40,Short-Term Intake Pressure,1,False
717,2025-12-17,31,2481,2512,1,-0.40,Sustained Backlog Pressure,2,False
718,2025-12-18,50,2472,2522,-10,0.40,No Current Backlog Pressure,0,False
719,2025-12-21,18,2484,2502,-3,-0.79,No Current Backlog Pressure,0,False

Trend input readiness summary:

                       Readiness Check          Result
0          Derived Metrics File Exists            True
1                          Rows Loaded             720
2                       Columns Loaded              18
3                        Expected Rows             720
4    Expected Columns From Notebook 03              18
5                    Date Parse Errors               0
6          Missing Trend Input Columns               0
7                     Date Column Type  datetime64[ns]
8                           Start Date      2023-01-12
9                             End Date      2025-12-21
10              Unique Reporting Dates             720
11         Dataset Chronological Order            True
12      Logical Anomaly Rows Preserved              86
13  Backlog Indicator Labels Available               4

## Step 4B — Create Daily Trend Dataset

This step creates a clean daily trend dataset for system capacity monitoring.

The goal of this step is to:
- Keep one row per reporting date
- Preserve daily CBP and HHS care load values
- Preserve total system load
- Preserve daily inflow and outflow values
- Preserve net daily intake
- Preserve care load growth rate
- Preserve backlog and anomaly indicators for transparency

This step supports the project guideline requirement: **Daily care load trends**.

No weekly aggregation, monthly aggregation, sustained high-load detection, rolling averages, or stress-window analysis is performed in this step.

In [13]:
# ============================================================
# Step 4B — Create Daily Trend Dataset
# Project: System Capacity & Care Load Analytics for Unaccompanied Children
# ============================================================

print("Step 4B — Create Daily Trend Dataset")
print("=" * 80)

# ------------------------------------------------------------
# 1. Create working copy for daily trend dataset
# ------------------------------------------------------------

df_daily_trend = df_hhs_trend.copy()

print("Daily trend working copy created successfully.")
print(f"Input dataset shape: {df_daily_trend.shape[0]:,} rows × {df_daily_trend.shape[1]:,} columns")

# ------------------------------------------------------------
# 2. Define daily trend columns
# ------------------------------------------------------------

daily_trend_columns = [
    "Date",
    "Children apprehended and placed in CBP custody*",
    "Children in CBP custody",
    "Children transferred out of CBP custody",
    "Children in HHS Care",
    "Children discharged from HHS Care",
    "total_system_load",
    "net_daily_intake",
    "care_load_growth_rate_pct",
    "positive_net_intake_flag",
    "net_intake_direction",
    "cumulative_net_intake_pressure",
    "consecutive_positive_net_intake_days",
    "backlog_indicator",
    "backlog_severity_score",
    "logical_constraint_anomaly_flag"
]

print("\nDaily trend columns selected:")
for idx, col in enumerate(daily_trend_columns, start=1):
    print(f"{idx}. {col}")

# ------------------------------------------------------------
# 3. Validate required daily trend columns
# ------------------------------------------------------------

missing_daily_trend_columns = [
    col for col in daily_trend_columns
    if col not in df_daily_trend.columns
]

print(f"\nMissing daily trend columns: {len(missing_daily_trend_columns)}")

if missing_daily_trend_columns:
    print("Missing columns:")
    print(missing_daily_trend_columns)
    raise KeyError("Daily trend dataset cannot be created because required columns are missing.")

# ------------------------------------------------------------
# 4. Create final daily trend dataset
# ------------------------------------------------------------

df_daily_trend = df_daily_trend[daily_trend_columns].copy()

# Ensure chronological order remains intact
df_daily_trend = df_daily_trend.sort_values("Date").reset_index(drop=True)

print("\nDaily trend dataset created successfully.")
print(f"Daily trend dataset shape: {df_daily_trend.shape[0]:,} rows × {df_daily_trend.shape[1]:,} columns")

# ------------------------------------------------------------
# 5. Add simple calendar fields for future trend grouping
# ------------------------------------------------------------
# These fields support daily trend filtering and future weekly/monthly grouping,
# but no aggregation is performed in Step 4B.

df_daily_trend["year"] = df_daily_trend["Date"].dt.year
df_daily_trend["month"] = df_daily_trend["Date"].dt.month
df_daily_trend["month_name"] = df_daily_trend["Date"].dt.month_name()
df_daily_trend["year_month"] = df_daily_trend["Date"].dt.to_period("M").astype(str)
df_daily_trend["day_of_week"] = df_daily_trend["Date"].dt.day_name()

print("\nCalendar fields added successfully:")
print("1. year")
print("2. month")
print("3. month_name")
print("4. year_month")
print("5. day_of_week")

# ------------------------------------------------------------
# 6. Daily trend validation checks
# ------------------------------------------------------------

daily_trend_missing_values = df_daily_trend.isna().sum().sum()
daily_trend_duplicate_dates = df_daily_trend["Date"].duplicated().sum()
daily_trend_unique_dates = df_daily_trend["Date"].nunique()
daily_trend_chronological_order = df_daily_trend["Date"].is_monotonic_increasing

daily_trend_summary = pd.DataFrame({
    "Daily Trend Check": [
        "Rows in Daily Trend Dataset",
        "Columns in Daily Trend Dataset",
        "Unique Reporting Dates",
        "Duplicate Reporting Dates",
        "Total Missing Values",
        "Start Date",
        "End Date",
        "Chronological Order",
        "Minimum Total System Load",
        "Maximum Total System Load",
        "Minimum Net Daily Intake",
        "Maximum Net Daily Intake",
        "Logical Anomaly Rows Preserved",
        "Backlog Indicator Labels Available"
    ],
    "Result": [
        df_daily_trend.shape[0],
        df_daily_trend.shape[1],
        daily_trend_unique_dates,
        daily_trend_duplicate_dates,
        daily_trend_missing_values,
        df_daily_trend["Date"].min().date(),
        df_daily_trend["Date"].max().date(),
        daily_trend_chronological_order,
        int(df_daily_trend["total_system_load"].min()),
        int(df_daily_trend["total_system_load"].max()),
        int(df_daily_trend["net_daily_intake"].min()),
        int(df_daily_trend["net_daily_intake"].max()),
        int(df_daily_trend["logical_constraint_anomaly_flag"].sum()),
        df_daily_trend["backlog_indicator"].nunique()
    ]
})

# ------------------------------------------------------------
# 7. Preview daily trend dataset
# ------------------------------------------------------------

print("\nDaily trend dataset preview:")
display(df_daily_trend.head(10))

print("\nDaily trend dataset tail:")
display(df_daily_trend.tail(10))

print("\nDaily trend validation summary:")
display(daily_trend_summary)

Step 4B — Create Daily Trend Dataset
================================================================================
Daily trend working copy created successfully.
Input dataset shape: 720 rows × 18 columns

Daily trend columns selected:
1. Date
2. Children apprehended and placed in CBP custody*
3. Children in CBP custody
4. Children transferred out of CBP custody
5. Children in HHS Care
6. Children discharged from HHS Care
7. total_system_load
8. net_daily_intake
9. care_load_growth_rate_pct
10. positive_net_intake_flag
11. net_intake_direction
12. cumulative_net_intake_pressure
13. consecutive_positive_net_intake_days
14. backlog_indicator
15. backlog_severity_score
16. logical_constraint_anomaly_flag

Missing daily trend columns: 0

Daily trend dataset created successfully.
Daily trend dataset shape: 720 rows × 16 columns

Calendar fields added successfully:
1. year
2. month
3. month_name
4. year_month
5. day_of_week

Daily trend dataset preview:

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care,total_system_load,net_daily_intake,care_load_growth_rate_pct,positive_net_intake_flag,net_intake_direction,cumulative_net_intake_pressure,consecutive_positive_net_intake_days,backlog_indicator,backlog_severity_score,logical_constraint_anomaly_flag,year,month,month_name,year_month,day_of_week
0,2023-01-12,33,53,34,6566,436,6619,-402,0.00,False,Relief: Discharges Exceed Transfers,-402,0,No Current Backlog Pressure,0,False,2023,1,January,2023-01,Thursday
1,2023-01-22,32,49,39,7122,227,7171,-188,8.34,False,Relief: Discharges Exceed Transfers,-590,0,No Current Backlog Pressure,0,False,2023,1,January,2023-01,Sunday
2,2023-01-23,32,50,39,7280,181,7330,-142,2.22,False,Relief: Discharges Exceed Transfers,-732,0,No Current Backlog Pressure,0,False,2023,1,January,2023-01,Monday
3,2023-01-24,47,42,47,7433,175,7475,-128,1.98,False,Relief: Discharges Exceed Transfers,-860,0,No Current Backlog Pressure,0,True,2023,1,January,2023-01,Tuesday
4,2023-01-25,20,22,41,7538,180,7560,-139,1.14,False,Relief: Discharges Exceed Transfers,-999,0,No Current Backlog Pressure,0,True,2023,1,January,2023-01,Wednesday
5,2023-01-29,23,45,11,7472,303,7517,-292,-0.57,False,Relief: Discharges Exceed Transfers,-1291,0,No Current Backlog Pressure,0,False,2023,1,January,2023-01,Sunday
6,2023-01-30,34,54,29,7743,196,7797,-167,3.72,False,Relief: Discharges Exceed Transfers,-1458,0,No Current Backlog Pressure,0,False,2023,1,January,2023-01,Monday
7,2023-01-31,26,36,36,7803,158,7839,-122,0.54,False,Relief: Discharges Exceed Transfers,-1580,0,No Current Backlog Pressure,0,False,2023,1,January,2023-01,Tuesday
8,2023-02-01,25,32,27,7903,231,7935,-204,1.22,False,Relief: Discharges Exceed Transfers,-1784,0,No Current Backlog Pressure,0,False,2023,2,February,2023-02,Wednesday
9,2023-02-02,15,13,23,7879,298,7892,-275,-0.54,False,Relief: Discharges Exceed Transfers,-2059,0,No Current Backlog Pressure,0,True,2023,2,February,2023-02,Thursday

Daily trend dataset tail:

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care,total_system_load,net_daily_intake,care_load_growth_rate_pct,positive_net_intake_flag,net_intake_direction,cumulative_net_intake_pressure,consecutive_positive_net_intake_days,backlog_indicator,backlog_severity_score,logical_constraint_anomaly_flag,year,month,month_name,year_month,day_of_week
710,2025-12-08,9,27,9,2440,4,2467,5,0.57,True,Pressure: Transfers Exceed Discharges,-32198,2,Short-Term Intake Pressure,1,False,2025,12,December,2025-12,Monday
711,2025-12-09,4,30,7,2443,8,2473,-1,0.24,False,Relief: Discharges Exceed Transfers,-32199,0,No Current Backlog Pressure,0,False,2025,12,December,2025-12,Tuesday
712,2025-12-10,10,54,5,2439,9,2493,-4,0.81,False,Relief: Discharges Exceed Transfers,-32203,0,No Current Backlog Pressure,0,False,2025,12,December,2025-12,Wednesday
713,2025-12-11,7,47,9,2437,10,2484,-1,-0.36,False,Relief: Discharges Exceed Transfers,-32204,0,No Current Backlog Pressure,0,False,2025,12,December,2025-12,Thursday
714,2025-12-14,8,35,4,2462,8,2497,-4,0.52,False,Relief: Discharges Exceed Transfers,-32208,0,No Current Backlog Pressure,0,False,2025,12,December,2025-12,Sunday
715,2025-12-15,11,42,9,2470,7,2512,2,0.60,True,Pressure: Transfers Exceed Discharges,-32206,1,Short-Term Intake Pressure,1,False,2025,12,December,2025-12,Monday
716,2025-12-16,8,54,15,2468,9,2522,6,0.40,True,Pressure: Transfers Exceed Discharges,-32200,2,Short-Term Intake Pressure,1,False,2025,12,December,2025-12,Tuesday
717,2025-12-17,7,31,11,2481,10,2512,1,-0.40,True,Pressure: Transfers Exceed Discharges,-32199,3,Sustained Backlog Pressure,2,False,2025,12,December,2025-12,Wednesday
718,2025-12-18,11,50,6,2472,16,2522,-10,0.40,False,Relief: Discharges Exceed Transfers,-32209,0,No Current Backlog Pressure,0,False,2025,12,December,2025-12,Thursday
719,2025-12-21,6,18,11,2484,14,2502,-3,-0.79,False,Relief: Discharges Exceed Transfers,-32212,0,No Current Backlog Pressure,0,False,2025,12,December,2025-12,Sunday

Daily trend validation summary:

                     Daily Trend Check      Result
0          Rows in Daily Trend Dataset         720
1       Columns in Daily Trend Dataset          21
2               Unique Reporting Dates         720
3            Duplicate Reporting Dates           0
4                 Total Missing Values           0
5                           Start Date  2023-01-12
6                             End Date  2025-12-21
7                  Chronological Order        True
8            Minimum Total System Load        2002
9            Maximum Total System Load       11762
10            Minimum Net Daily Intake        -465
11            Maximum Net Daily Intake         206
12      Logical Anomaly Rows Preserved          86
13  Backlog Indicator Labels Available           4

## Step 4C — Weekly Care Load Trend Analysis

This step converts the validated daily trend dataset into a weekly-level care load trend dataset.

The objective of this step is to summarize daily system capacity movement into weekly reporting periods so that broader weekly patterns can be analyzed clearly in the next stages.

In this step, we will:

- Create a safe working copy of the daily trend dataset.
- Validate all required input columns for weekly trend analysis.
- Confirm that the Date column is in proper datetime format.
- Sort the dataset chronologically.
- Create weekly calendar fields:
  - `week_start_date`
  - `week_end_date`
- Aggregate daily metrics into weekly-level summaries.
- Calculate weekly measures such as:
  - reporting days
  - average CBP custody
  - average HHS care load
  - average total system load
  - minimum and maximum weekly system load
  - total transfers into HHS
  - total discharges from HHS
  - total net intake
  - average net daily intake
  - average care load growth rate
  - backlog pressure days
  - logical anomaly days
- Create a weekly backlog status label for interpretation.
- Validate the final weekly trend dataset.

This step does **not** create rolling averages, stress windows, or pressure indicators. Those belong to the later Pressure and Stress Identification stage according to the project methodology.

The output from this step will be used for weekly trend and temporal analysis.

In [14]:
# ============================================================
# Step 4C - Create Weekly Care Load Trend Dataset
# ============================================================

print("Step 4C - Create Weekly Care Load Trend Dataset")
print("=" * 80)

# ------------------------------------------------------------
# 1. Create safe working copy from daily trend dataset
# ------------------------------------------------------------

df_weekly_trend = df_daily_trend.copy()

print("Weekly trend working copy created successfully.")
print(f"Input daily trend dataset shape: {df_weekly_trend.shape[0]} rows × {df_weekly_trend.shape[1]} columns")

# ------------------------------------------------------------
# 2. Validate required columns for weekly trend analysis
# ------------------------------------------------------------

required_weekly_columns = [
    "Date",
    "Children apprehended and placed in CBP custody*",
    "Children in CBP custody",
    "Children transferred out of CBP custody",
    "Children in HHS Care",
    "Children discharged from HHS Care",
    "total_system_load",
    "net_daily_intake",
    "care_load_growth_rate_pct",
    "backlog_indicator",
    "backlog_severity_score",
    "logical_constraint_anomaly_flag"
]

missing_weekly_columns = [
    col for col in required_weekly_columns
    if col not in df_weekly_trend.columns
]

print("\nRequired weekly trend columns:")
for idx, col in enumerate(required_weekly_columns, start=1):
    print(f"{idx}. {col}")

print(f"\nMissing weekly trend input columns: {len(missing_weekly_columns)}")

if missing_weekly_columns:
    raise ValueError(f"Missing required weekly trend columns: {missing_weekly_columns}")

# ------------------------------------------------------------
# 3. Ensure Date column is datetime and sorted
# ------------------------------------------------------------

df_weekly_trend["Date"] = pd.to_datetime(df_weekly_trend["Date"], errors="coerce")

date_parse_errors_weekly = df_weekly_trend["Date"].isna().sum()

if date_parse_errors_weekly > 0:
    raise ValueError(f"Date parsing errors found in weekly trend dataset: {date_parse_errors_weekly}")

df_weekly_trend = df_weekly_trend.sort_values("Date").reset_index(drop=True)

print("\nDate column validated and dataset sorted chronologically.")
print(f"Start date: {df_weekly_trend['Date'].min().date()}")
print(f"End date: {df_weekly_trend['Date'].max().date()}")
print(f"Unique reporting dates: {df_weekly_trend['Date'].nunique()}")

# ------------------------------------------------------------
# 4. Create weekly calendar fields
# ------------------------------------------------------------

df_weekly_trend["week_start_date"] = df_weekly_trend["Date"].dt.to_period("W-MON").apply(lambda r: r.start_time)
df_weekly_trend["week_end_date"] = df_weekly_trend["Date"].dt.to_period("W-MON").apply(lambda r: r.end_time)

df_weekly_trend["week_start_date"] = df_weekly_trend["week_start_date"].dt.date
df_weekly_trend["week_end_date"] = df_weekly_trend["week_end_date"].dt.date

print("\nWeekly calendar fields created successfully:")
print("1. week_start_date")
print("2. week_end_date")

# ------------------------------------------------------------
# 5. Create weekly trend aggregation
# ------------------------------------------------------------

df_weekly_care_trend = (
    df_weekly_trend
    .groupby(["week_start_date", "week_end_date"], as_index=False)
    .agg(
        reporting_days=("Date", "nunique"),
        avg_children_apprehended_cbp=("Children apprehended and placed in CBP custody*", "mean"),
        total_children_apprehended_cbp=("Children apprehended and placed in CBP custody*", "sum"),
        avg_cbp_custody=("Children in CBP custody", "mean"),
        avg_hhs_care=("Children in HHS Care", "mean"),
        avg_total_system_load=("total_system_load", "mean"),
        min_total_system_load=("total_system_load", "min"),
        max_total_system_load=("total_system_load", "max"),
        total_transfers_to_hhs=("Children transferred out of CBP custody", "sum"),
        total_discharges_from_hhs=("Children discharged from HHS Care", "sum"),
        total_net_intake=("net_daily_intake", "sum"),
        avg_net_daily_intake=("net_daily_intake", "mean"),
        avg_care_load_growth_rate_pct=("care_load_growth_rate_pct", "mean"),
        backlog_pressure_days=("backlog_severity_score", lambda x: (x > 0).sum()),
        max_backlog_severity_score=("backlog_severity_score", "max"),
        logical_anomaly_days=("logical_constraint_anomaly_flag", "sum")
    )
)

# ------------------------------------------------------------
# 6. Add weekly backlog status label
# ------------------------------------------------------------

def classify_weekly_backlog(row):
    if row["backlog_pressure_days"] == 0:
        return "No Weekly Backlog Pressure"
    elif row["backlog_pressure_days"] <= 2:
        return "Low Weekly Backlog Pressure"
    elif row["backlog_pressure_days"] <= 4:
        return "Moderate Weekly Backlog Pressure"
    else:
        return "High Weekly Backlog Pressure"

df_weekly_care_trend["weekly_backlog_status"] = df_weekly_care_trend.apply(
    classify_weekly_backlog,
    axis=1
)

# ------------------------------------------------------------
# 7. Round weekly numeric metrics for clean output
# ------------------------------------------------------------

weekly_round_columns = [
    "avg_children_apprehended_cbp",
    "avg_cbp_custody",
    "avg_hhs_care",
    "avg_total_system_load",
    "avg_net_daily_intake",
    "avg_care_load_growth_rate_pct"
]

for col in weekly_round_columns:
    df_weekly_care_trend[col] = df_weekly_care_trend[col].round(2)

# ------------------------------------------------------------
# 8. Weekly validation summary
# ------------------------------------------------------------

weekly_trend_summary = pd.DataFrame({
    "Weekly Trend Check": [
        "Rows in Daily Trend Input",
        "Columns in Daily Trend Input",
        "Weekly Periods Created",
        "Minimum Reporting Days in a Week",
        "Maximum Reporting Days in a Week",
        "Average Weekly System Load Minimum",
        "Average Weekly System Load Maximum",
        "Total Net Intake Minimum",
        "Total Net Intake Maximum",
        "Weeks With Backlog Pressure",
        "Weeks With Logical Anomaly Days",
        "Rows Deleted or Modified"
    ],
    "Result": [
        df_weekly_trend.shape[0],
        df_weekly_trend.shape[1],
        df_weekly_care_trend.shape[0],
        df_weekly_care_trend["reporting_days"].min(),
        df_weekly_care_trend["reporting_days"].max(),
        df_weekly_care_trend["avg_total_system_load"].min(),
        df_weekly_care_trend["avg_total_system_load"].max(),
        df_weekly_care_trend["total_net_intake"].min(),
        df_weekly_care_trend["total_net_intake"].max(),
        (df_weekly_care_trend["backlog_pressure_days"] > 0).sum(),
        (df_weekly_care_trend["logical_anomaly_days"] > 0).sum(),
        0
    ]
})

print("\nWeekly trend dataset created successfully.")
print(f"Weekly trend dataset shape: {df_weekly_care_trend.shape[0]} rows × {df_weekly_care_trend.shape[1]} columns")

print("\nWeekly trend dataset preview:")
display(df_weekly_care_trend.head(10))

print("\nWeekly trend dataset tail:")
display(df_weekly_care_trend.tail(10))

print("\nWeekly trend validation summary:")
display(weekly_trend_summary)

Step 4C - Create Weekly Care Load Trend Dataset
================================================================================
Weekly trend working copy created successfully.
Input daily trend dataset shape: 720 rows × 21 columns

Required weekly trend columns:
1. Date
2. Children apprehended and placed in CBP custody*
3. Children in CBP custody
4. Children transferred out of CBP custody
5. Children in HHS Care
6. Children discharged from HHS Care
7. total_system_load
8. net_daily_intake
9. care_load_growth_rate_pct
10. backlog_indicator
11. backlog_severity_score
12. logical_constraint_anomaly_flag

Missing weekly trend input columns: 0

Date column validated and dataset sorted chronologically.
Start date: 2023-01-12
End date: 2025-12-21
Unique reporting dates: 720

Weekly calendar fields created successfully:
1. week_start_date
2. week_end_date

Weekly trend dataset created successfully.
Weekly trend dataset shape: 154 rows × 19 columns

Weekly trend dataset preview:

,week_start_date,week_end_date,reporting_days,avg_children_apprehended_cbp,total_children_apprehended_cbp,avg_cbp_custody,avg_hhs_care,avg_total_system_load,min_total_system_load,max_total_system_load,total_transfers_to_hhs,total_discharges_from_hhs,total_net_intake,avg_net_daily_intake,avg_care_load_growth_rate_pct,backlog_pressure_days,max_backlog_severity_score,logical_anomaly_days,weekly_backlog_status
0,2023-01-10,2023-01-16,1,33.00,33,53.00,6566.00,6619.00,6619,6619,34,436,-402,-402.0,0.00,0,0,0,No Weekly Backlog Pressure
1,2023-01-17,2023-01-23,2,32.00,64,49.50,7201.00,7250.50,7171,7330,78,408,-330,-165.0,5.28,0,0,0,No Weekly Backlog Pressure
2,2023-01-24,2023-01-30,4,31.00,124,40.75,7546.50,7587.25,7475,7797,128,854,-726,-181.5,1.57,0,0,2,No Weekly Backlog Pressure
3,2023-01-31,2023-02-06,5,18.60,93,24.20,7778.20,7802.40,7604,7935,113,1225,-1112,-222.4,-0.12,0,0,1,No Weekly Backlog Pressure
4,2023-02-07,2023-02-13,5,102.20,511,182.40,7719.00,7901.40,7637,8142,695,1431,-736,-147.2,0.05,0,0,0,No Weekly Backlog Pressure
5,2023-02-14,2023-02-20,4,133.75,535,230.50,7818.25,8048.75,8006,8102,729,1083,-354,-88.5,1.16,0,0,0,No Weekly Backlog Pressure
6,2023-02-21,2023-02-27,5,131.60,658,224.00,7853.60,8077.60,7799,8281,967,1402,-435,-87.0,-0.13,1,1,2,Low Weekly Backlog Pressure
7,2023-02-28,2023-03-06,3,109.67,329,200.33,7898.67,8099.00,8088,8112,554,842,-288,-96.0,0.24,0,0,1,No Weekly Backlog Pressure
8,2023-03-07,2023-03-13,4,119.75,479,234.25,7774.25,8008.50,7797,8093,675,1139,-464,-116.0,-0.93,0,0,0,No Weekly Backlog Pressure
9,2023-03-14,2023-03-20,5,154.20,771,276.60,7906.00,8182.60,8086,8269,917,1360,-443,-88.6,1.13,1,1,0,Low Weekly Backlog Pressure

Weekly trend dataset tail:

,week_start_date,week_end_date,reporting_days,avg_children_apprehended_cbp,total_children_apprehended_cbp,avg_cbp_custody,avg_hhs_care,avg_total_system_load,min_total_system_load,max_total_system_load,total_transfers_to_hhs,total_discharges_from_hhs,total_net_intake,avg_net_daily_intake,avg_care_load_growth_rate_pct,backlog_pressure_days,max_backlog_severity_score,logical_anomaly_days,weekly_backlog_status
144,2025-10-14,2025-10-20,5,8.60,43,33.00,2234.60,2267.6,2254,2282,64,46,18,3.60,0.31,3,2,0,Moderate Weekly Backlog Pressure
145,2025-10-21,2025-10-27,5,7.00,35,34.80,2267.20,2302.0,2290,2313,76,60,16,3.20,0.27,4,2,0,Moderate Weekly Backlog Pressure
146,2025-10-28,2025-11-03,5,4.60,23,22.60,2279.80,2302.4,2297,2308,44,54,-10,-2.00,-0.14,3,1,0,Moderate Weekly Backlog Pressure
147,2025-11-04,2025-11-10,4,7.75,31,35.00,2275.00,2310.0,2297,2327,28,38,-10,-2.50,0.33,2,1,0,Low Weekly Backlog Pressure
148,2025-11-11,2025-11-17,5,7.40,37,34.00,2319.20,2353.2,2333,2378,57,39,18,3.60,0.44,2,1,0,Low Weekly Backlog Pressure
149,2025-11-18,2025-11-24,5,7.80,39,42.60,2354.20,2396.8,2372,2421,50,45,5,1.00,0.28,1,1,0,Low Weekly Backlog Pressure
150,2025-11-25,2025-12-01,4,4.50,18,28.75,2397.25,2426.0,2413,2436,36,27,9,2.25,0.26,3,2,0,Moderate Weekly Backlog Pressure
151,2025-12-02,2025-12-08,5,8.00,40,31.20,2422.60,2453.8,2441,2467,43,44,-1,-0.20,0.25,3,1,0,Moderate Weekly Backlog Pressure
152,2025-12-09,2025-12-15,5,8.00,40,41.60,2450.20,2491.8,2473,2512,34,42,-8,-1.60,0.36,1,1,0,Low Weekly Backlog Pressure
153,2025-12-16,2025-12-22,4,8.00,32,38.25,2476.25,2514.5,2502,2522,43,49,-6,-1.50,-0.10,2,2,0,Low Weekly Backlog Pressure

Weekly trend validation summary:

                    Weekly Trend Check    Result
0            Rows in Daily Trend Input    720.00
1         Columns in Daily Trend Input     23.00
2               Weekly Periods Created    154.00
3     Minimum Reporting Days in a Week      1.00
4     Maximum Reporting Days in a Week      6.00
5   Average Weekly System Load Minimum   2013.80
6   Average Weekly System Load Maximum  11545.25
7             Total Net Intake Minimum  -1320.00
8             Total Net Intake Maximum    625.00
9          Weeks With Backlog Pressure     89.00
10     Weeks With Logical Anomaly Days     63.00
11            Rows Deleted or Modified      0.00

## Step 4D — Create Monthly Care Load Trend Dataset

This step creates a monthly-level trend dataset from the validated daily trend dataset.

The purpose of this step is to support the **Trend & Temporal Analysis** stage of the project by summarizing care load movement across calendar months.

This step focuses only on monthly aggregation and does not create rolling averages, stress windows, forecasting models, or pressure-window logic.

### What this step does

- Uses the daily trend dataset created in Step 4B
- Groups records by monthly reporting period
- Calculates monthly average and total care load indicators
- Summarizes CBP custody, HHS care, total system load, and net daily intake
- Counts backlog pressure days by month
- Counts logical anomaly days by month
- Validates the monthly trend output for completeness and chronological order

### Output of this step

This step creates a clean monthly trend dataset that can be used later for:
- Monthly care load trend analysis
- Calendar-period comparison
- Long-term system load movement
- Future forecasting preparation

In [15]:
# ============================================================
# Step 4D — Create Monthly Care Load Trend Dataset
# ============================================================

print("Step 4D — Create Monthly Care Load Trend Dataset")
print("=" * 70)

# ------------------------------------------------------------
# 1. Create working copy from Step 4B daily trend dataset
# ------------------------------------------------------------

df_monthly_source = df_daily_trend.copy()

print("Monthly trend working copy created successfully.")
print(f"Input daily trend dataset shape: {df_monthly_source.shape[0]} rows × {df_monthly_source.shape[1]} columns")


# ------------------------------------------------------------
# 2. Required columns for monthly trend dataset
# ------------------------------------------------------------

required_monthly_trend_columns = [
    "Date",
    "Children apprehended and placed in CBP custody*",
    "Children in CBP custody",
    "Children transferred out of CBP custody",
    "Children in HHS Care",
    "Children discharged from HHS Care",
    "total_system_load",
    "net_daily_intake",
    "care_load_growth_rate_pct",
    "backlog_indicator",
    "backlog_severity_score",
    "logical_constraint_anomaly_flag",
    "year",
    "month",
    "month_name",
    "year_month"
]

missing_monthly_trend_columns = [
    col for col in required_monthly_trend_columns
    if col not in df_monthly_source.columns
]

print("\nRequired monthly trend columns:")
for idx, col in enumerate(required_monthly_trend_columns, start=1):
    print(f"{idx}. {col}")

print(f"\nMissing monthly trend input columns: {len(missing_monthly_trend_columns)}")

if missing_monthly_trend_columns:
    raise ValueError(f"Missing required columns for Step 4D: {missing_monthly_trend_columns}")


# ------------------------------------------------------------
# 3. Validate Date column and chronological order
# ------------------------------------------------------------

df_monthly_source["Date"] = pd.to_datetime(df_monthly_source["Date"], errors="coerce")

monthly_date_parse_errors = int(df_monthly_source["Date"].isna().sum())

if monthly_date_parse_errors > 0:
    raise ValueError(f"Date parsing failed for {monthly_date_parse_errors} rows in Step 4D.")

df_monthly_source = df_monthly_source.sort_values("Date").reset_index(drop=True)

monthly_start_date = df_monthly_source["Date"].min()
monthly_end_date = df_monthly_source["Date"].max()
monthly_unique_dates = df_monthly_source["Date"].nunique()
monthly_chronological_order = bool(df_monthly_source["Date"].is_monotonic_increasing)

print("\nDate column validated and dataset sorted chronologically.")
print(f"Start date: {monthly_start_date.date()}")
print(f"End date: {monthly_end_date.date()}")
print(f"Unique reporting dates: {monthly_unique_dates}")
print(f"Chronological order: {monthly_chronological_order}")


# ------------------------------------------------------------
# 4. Create month period columns
# ------------------------------------------------------------

df_monthly_source["month_period"] = df_monthly_source["Date"].dt.to_period("M")
df_monthly_source["month_start_date"] = df_monthly_source["month_period"].dt.start_time
df_monthly_source["month_end_date"] = df_monthly_source["month_period"].dt.end_time.dt.normalize()

print("\nMonthly calendar fields created successfully:")
print("1. month_period")
print("2. month_start_date")
print("3. month_end_date")


# ------------------------------------------------------------
# 5. Create monthly care load trend dataset
# ------------------------------------------------------------

df_monthly_care_trend = (
    df_monthly_source
    .groupby("month_period", as_index=False)
    .agg(
        month_start_date=("month_start_date", "min"),
        month_end_date=("month_end_date", "max"),
        reporting_days=("Date", "count"),

        avg_children_apprehended_cbp=("Children apprehended and placed in CBP custody*", "mean"),
        total_children_apprehended_cbp=("Children apprehended and placed in CBP custody*", "sum"),

        avg_cbp_custody=("Children in CBP custody", "mean"),
        max_cbp_custody=("Children in CBP custody", "max"),

        avg_hhs_care=("Children in HHS Care", "mean"),
        max_hhs_care=("Children in HHS Care", "max"),

        avg_total_system_load=("total_system_load", "mean"),
        max_total_system_load=("total_system_load", "max"),
        min_total_system_load=("total_system_load", "min"),

        total_transfers_out_of_cbp=("Children transferred out of CBP custody", "sum"),
        total_discharges_from_hhs=("Children discharged from HHS Care", "sum"),

        total_net_intake=("net_daily_intake", "sum"),
        avg_net_daily_intake=("net_daily_intake", "mean"),
        min_net_daily_intake=("net_daily_intake", "min"),
        max_net_daily_intake=("net_daily_intake", "max"),

        avg_care_load_growth_rate_pct=("care_load_growth_rate_pct", "mean"),

        backlog_pressure_days=("backlog_severity_score", lambda x: int((x > 0).sum())),
        max_backlog_severity_score=("backlog_severity_score", "max"),
        logical_anomaly_days=("logical_constraint_anomaly_flag", lambda x: int(x.sum()))
    )
)

print("\nMonthly trend dataset created successfully.")
print(f"Monthly trend dataset shape: {df_monthly_care_trend.shape[0]} rows × {df_monthly_care_trend.shape[1]} columns")


# ------------------------------------------------------------
# 6. Add readable month fields
# ------------------------------------------------------------

df_monthly_care_trend["year"] = df_monthly_care_trend["month_start_date"].dt.year
df_monthly_care_trend["month"] = df_monthly_care_trend["month_start_date"].dt.month
df_monthly_care_trend["month_name"] = df_monthly_care_trend["month_start_date"].dt.month_name()
df_monthly_care_trend["year_month"] = df_monthly_care_trend["month_start_date"].dt.strftime("%Y-%m")

# Reorder columns for readability
monthly_column_order = [
    "month_period",
    "month_start_date",
    "month_end_date",
    "year",
    "month",
    "month_name",
    "year_month",
    "reporting_days",

    "avg_children_apprehended_cbp",
    "total_children_apprehended_cbp",

    "avg_cbp_custody",
    "max_cbp_custody",
    "avg_hhs_care",
    "max_hhs_care",

    "avg_total_system_load",
    "min_total_system_load",
    "max_total_system_load",

    "total_transfers_out_of_cbp",
    "total_discharges_from_hhs",

    "total_net_intake",
    "avg_net_daily_intake",
    "min_net_daily_intake",
    "max_net_daily_intake",

    "avg_care_load_growth_rate_pct",

    "backlog_pressure_days",
    "max_backlog_severity_score",
    "logical_anomaly_days"
]

df_monthly_care_trend = df_monthly_care_trend[monthly_column_order]

print("\nReadable month fields added successfully:")
print("1. year")
print("2. month")
print("3. month_name")
print("4. year_month")


# ------------------------------------------------------------
# 7. Round average columns for clean reporting
# ------------------------------------------------------------

monthly_average_columns = [
    "avg_children_apprehended_cbp",
    "avg_cbp_custody",
    "avg_hhs_care",
    "avg_total_system_load",
    "avg_net_daily_intake",
    "avg_care_load_growth_rate_pct"
]

df_monthly_care_trend[monthly_average_columns] = df_monthly_care_trend[monthly_average_columns].round(2)

print("\nMonthly average columns rounded successfully.")


# ------------------------------------------------------------
# 8. Monthly trend validation summary
# ------------------------------------------------------------

monthly_trend_summary = pd.DataFrame({
    "Monthly Trend Check": [
        "Rows in Daily Trend Input",
        "Columns in Daily Trend Input",
        "Monthly Periods Created",
        "Minimum Reporting Days in a Month",
        "Maximum Reporting Days in a Month",
        "Average Monthly System Load Minimum",
        "Average Monthly System Load Maximum",
        "Total Net Intake Minimum",
        "Total Net Intake Maximum",
        "Months With Backlog Pressure",
        "Months With Logical Anomaly Days",
        "Rows Deleted or Modified"
    ],
    "Result": [
        df_monthly_source.shape[0],
        df_monthly_source.shape[1],
        df_monthly_care_trend.shape[0],
        int(df_monthly_care_trend["reporting_days"].min()),
        int(df_monthly_care_trend["reporting_days"].max()),
        round(df_monthly_care_trend["avg_total_system_load"].min(), 2),
        round(df_monthly_care_trend["avg_total_system_load"].max(), 2),
        int(df_monthly_care_trend["total_net_intake"].min()),
        int(df_monthly_care_trend["total_net_intake"].max()),
        int((df_monthly_care_trend["backlog_pressure_days"] > 0).sum()),
        int((df_monthly_care_trend["logical_anomaly_days"] > 0).sum()),
        0
    ]
})

print("\nMonthly trend validation summary:")
display(monthly_trend_summary)


# ------------------------------------------------------------
# 9. Preview monthly trend dataset
# ------------------------------------------------------------

print("\nMonthly trend dataset preview:")
display(df_monthly_care_trend.head(10))

print("\nMonthly trend dataset tail:")
display(df_monthly_care_trend.tail(10))

Step 4D — Create Monthly Care Load Trend Dataset
======================================================================
Monthly trend working copy created successfully.
Input daily trend dataset shape: 720 rows × 21 columns

Required monthly trend columns:
1. Date
2. Children apprehended and placed in CBP custody*
3. Children in CBP custody
4. Children transferred out of CBP custody
5. Children in HHS Care
6. Children discharged from HHS Care
7. total_system_load
8. net_daily_intake
9. care_load_growth_rate_pct
10. backlog_indicator
11. backlog_severity_score
12. logical_constraint_anomaly_flag
13. year
14. month
15. month_name
16. year_month

Missing monthly trend input columns: 0

Date column validated and dataset sorted chronologically.
Start date: 2023-01-12
End date: 2025-12-21
Unique reporting dates: 720
Chronological order: True

Monthly calendar fields created successfully:
1. month_period
2. month_start_date
3. month_end_date

Monthly trend dataset created successfully.
Monthly trend dataset shape: 36 rows × 23 columns

Readable month fields added successfully:
1. year
2. month
3. month_name
4. year_month

Monthly average columns rounded successfully.

Monthly trend validation summary:

                    Monthly Trend Check    Result
0             Rows in Daily Trend Input    720.00
1          Columns in Daily Trend Input     24.00
2               Monthly Periods Created     36.00
3     Minimum Reporting Days in a Month      8.00
4     Maximum Reporting Days in a Month     23.00
5   Average Monthly System Load Minimum   2026.90
6   Average Monthly System Load Maximum  11255.26
7              Total Net Intake Minimum  -5609.00
8              Total Net Intake Maximum   1059.00
9          Months With Backlog Pressure     29.00
10     Months With Logical Anomaly Days     25.00
11             Rows Deleted or Modified      0.00

Monthly trend dataset preview:

,month_period,month_start_date,month_end_date,year,month,month_name,year_month,reporting_days,avg_children_apprehended_cbp,total_children_apprehended_cbp,avg_cbp_custody,max_cbp_custody,avg_hhs_care,max_hhs_care,avg_total_system_load,min_total_system_load,max_total_system_load,total_transfers_out_of_cbp,total_discharges_from_hhs,total_net_intake,avg_net_daily_intake,min_net_daily_intake,max_net_daily_intake,avg_care_load_growth_rate_pct,backlog_pressure_days,max_backlog_severity_score,logical_anomaly_days
0,2023-01,2023-01-01,2023-01-31,2023,1,January,2023-01,8,30.88,247,43.88,54,7369.62,7803,7413.50,6619,7839,276,1856,-1580,-197.50,-402,-122,2.17,0,0,2
1,2023-02,2023-02-01,2023-02-28,2023,2,February,2023-02,19,99.26,1886,171.32,314,7795.79,7978,7967.11,7604,8281,2637,5183,-2546,-134.00,-327,4,0.21,1,1,3
2,2023-03,2023-03-01,2023-03-31,2023,3,March,2023-03,19,130.47,2479,245.11,313,7945.37,8208,8190.47,7797,8453,3399,5375,-1976,-104.00,-190,33,0.21,1,1,1
3,2023-04,2023-04-01,2023-04-30,2023,4,April,2023-04,21,149.00,3129,250.19,367,7842.67,8352,8092.86,7641,8595,3967,5668,-1701,-81.00,-197,40,0.12,2,1,2
4,2023-05,2023-05-01,2023-05-31,2023,5,May,2023-05,22,124.82,2746,216.95,412,8187.14,8790,8404.09,7056,9084,3622,6256,-2634,-119.73,-344,-3,-0.81,0,0,6
5,2023-06,2023-06-01,2023-06-30,2023,6,June,2023-06,20,88.70,1774,145.65,259,6136.45,7002,6282.10,5730,7084,2416,4029,-1613,-80.65,-219,65,-0.60,2,1,4
6,2023-07,2023-07-01,2023-07-31,2023,7,July,2023-07,21,136.10,2858,245.29,314,6828.10,7800,7073.38,6188,8076,3897,4407,-510,-24.29,-125,93,1.23,5,1,3
7,2023-08,2023-08-01,2023-08-31,2023,8,August,2023-08,20,137.55,2751,237.20,367,9347.90,10280,9585.10,8349,10647,3587,6470,-2883,-144.15,-296,5,1.30,1,1,1
8,2023-09,2023-09-01,2023-09-30,2023,9,September,2023-09,19,168.11,3194,291.05,412,10701.32,11095,10992.37,10294,11382,3971,6546,-2575,-135.53,-254,-21,0.36,0,0,3
9,2023-10,2023-10-01,2023-10-31,2023,10,October,2023-10,22,67.55,1486,102.91,196,10205.32,11130,10308.23,9000,11200,2049,7658,-5609,-254.95,-374,-148,-0.88,0,0,8

Monthly trend dataset tail:

,month_period,month_start_date,month_end_date,year,month,month_name,year_month,reporting_days,avg_children_apprehended_cbp,total_children_apprehended_cbp,avg_cbp_custody,max_cbp_custody,avg_hhs_care,max_hhs_care,avg_total_system_load,min_total_system_load,max_total_system_load,total_transfers_out_of_cbp,total_discharges_from_hhs,total_net_intake,avg_net_daily_intake,min_net_daily_intake,max_net_daily_intake,avg_care_load_growth_rate_pct,backlog_pressure_days,max_backlog_severity_score,logical_anomaly_days
26,2025-03,2025-03-01,2025-03-31,2025,3,March,2025-03,22,7.68,169,21.45,34,2164.45,2297,2185.91,2125,2321,190,309,-119,-5.41,-36,13,-0.36,11,3,0
27,2025-04,2025-04-01,2025-04-30,2025,4,April,2025-04,23,8.22,189,24.87,40,2273.13,2309,2298.00,2227,2343,230,203,27,1.17,-7,13,0.24,11,2,0
28,2025-05,2025-05-01,2025-05-31,2025,5,May,2025-05,18,12.06,217,32.83,62,2406.94,2506,2439.78,2338,2544,252,205,47,2.61,-5,11,0.46,12,2,0
29,2025-06,2025-06-01,2025-06-30,2025,6,June,2025-06,17,7.24,123,19.06,28,2492.41,2528,2511.47,2429,2552,138,281,-143,-8.41,-28,5,-0.27,3,1,0
30,2025-07,2025-07-01,2025-07-31,2025,7,July,2025-07,21,3.33,70,13.95,21,2187.19,2391,2201.14,2067,2405,88,396,-308,-14.67,-36,-2,-0.76,0,0,0
31,2025-08,2025-08-01,2025-08-31,2025,8,August,2025-08,20,5.35,107,25.60,49,2001.30,2049,2026.90,2002,2075,147,254,-107,-5.35,-13,5,-0.12,1,1,0
32,2025-09,2025-09-01,2025-09-30,2025,9,September,2025-09,22,9.27,204,35.82,52,2082.23,2159,2118.05,2039,2191,260,237,23,1.05,-12,23,0.38,10,1,0
33,2025-10,2025-10-01,2025-10-31,2025,10,October,2025-10,21,8.00,168,34.33,55,2231.05,2287,2265.38,2196,2313,263,242,21,1.00,-13,10,0.24,12,2,0
34,2025-11,2025-11-01,2025-11-30,2025,11,November,2025-11,19,6.79,129,34.79,57,2325.89,2415,2360.68,2297,2433,182,159,23,1.21,-10,21,0.29,9,2,0
35,2025-12,2025-12-01,2025-12-31,2025,12,December,2025-12,15,7.73,116,36.20,54,2445.27,2484,2481.47,2436,2522,124,144,-20,-1.33,-10,6,0.19,6,2,0

## Step 4E — Calendar Period / Yearly Trend Comparison Dataset

This step creates a yearly comparison dataset from the daily trend dataset.

The purpose of this step is to support calendar-period comparison across the full timeline, especially early vs later reporting periods.

This step does not create rolling averages or forecasting features. It only summarizes yearly healthcare capacity movement using already-approved daily trend metrics.

Key outputs created in this step:

- Year-level care load summary
- Year-wise total system load comparison
- Year-wise net daily intake comparison
- Year-wise backlog pressure summary
- Year-wise logical anomaly tracking
- Early vs later timeline comparison base

This step supports the project guideline requirement:

**Trend & Temporal Analysis**
- Daily, weekly, and monthly care load trends
- Comparison across calendar periods
- Early vs late timeline comparison

In [16]:
# ============================================================
# Step 4E - Create Yearly / Calendar Period Trend Comparison Dataset
# ============================================================

print("Step 4E - Create Yearly / Calendar Period Trend Comparison Dataset")
print("=" * 85)

# ------------------------------------------------------------
# 1. Create safe working copy
# ------------------------------------------------------------

df_yearly_source = df_daily_trend.copy()

print("Yearly trend working copy created successfully.")
print(f"Input daily trend dataset shape: {df_yearly_source.shape[0]} rows × {df_yearly_source.shape[1]} columns")


# ------------------------------------------------------------
# 2. Required columns validation
# ------------------------------------------------------------

required_yearly_columns = [
    "Date",
    "year",
    "Children apprehended and placed in CBP custody*",
    "Children in CBP custody",
    "Children transferred out of CBP custody",
    "Children in HHS Care",
    "Children discharged from HHS Care",
    "total_system_load",
    "net_daily_intake",
    "care_load_growth_rate_pct",
    "backlog_indicator",
    "backlog_severity_score",
    "logical_constraint_anomaly_flag"
]

print("\nRequired yearly comparison columns:")
for idx, col in enumerate(required_yearly_columns, start=1):
    print(f"{idx}. {col}")

missing_yearly_columns = [
    col for col in required_yearly_columns
    if col not in df_yearly_source.columns
]

print(f"\nMissing yearly comparison input columns: {len(missing_yearly_columns)}")

if missing_yearly_columns:
    raise ValueError(f"Missing required columns for Step 4E: {missing_yearly_columns}")


# ------------------------------------------------------------
# 3. Date and chronological validation
# ------------------------------------------------------------

df_yearly_source["Date"] = pd.to_datetime(df_yearly_source["Date"], errors="coerce")

date_parse_errors = df_yearly_source["Date"].isna().sum()

if date_parse_errors > 0:
    raise ValueError(f"Date parse errors found in Step 4E: {date_parse_errors}")

df_yearly_source = df_yearly_source.sort_values("Date").reset_index(drop=True)

print("\nDate column validated and dataset sorted chronologically.")
print(f"Start date: {df_yearly_source['Date'].min().date()}")
print(f"End date: {df_yearly_source['Date'].max().date()}")
print(f"Unique reporting dates: {df_yearly_source['Date'].nunique()}")


# ------------------------------------------------------------
# 4. Yearly aggregation
# ------------------------------------------------------------

df_yearly_trend = (
    df_yearly_source
    .groupby("year", as_index=False)
    .agg(
        year_start_date=("Date", "min"),
        year_end_date=("Date", "max"),
        reporting_days=("Date", "nunique"),

        avg_children_apprehended_cbp=(
            "Children apprehended and placed in CBP custody*",
            "mean"
        ),
        total_children_apprehended_cbp=(
            "Children apprehended and placed in CBP custody*",
            "sum"
        ),

        avg_cbp_custody=("Children in CBP custody", "mean"),
        max_cbp_custody=("Children in CBP custody", "max"),

        avg_hhs_care=("Children in HHS Care", "mean"),
        max_hhs_care=("Children in HHS Care", "max"),

        avg_total_system_load=("total_system_load", "mean"),
        min_total_system_load=("total_system_load", "min"),
        max_total_system_load=("total_system_load", "max"),

        total_transfers_to_hhs=("Children transferred out of CBP custody", "sum"),
        total_discharges_from_hhs=("Children discharged from HHS Care", "sum"),

        avg_net_daily_intake=("net_daily_intake", "mean"),
        total_net_intake=("net_daily_intake", "sum"),
        min_net_daily_intake=("net_daily_intake", "min"),
        max_net_daily_intake=("net_daily_intake", "max"),

        avg_care_load_growth_rate_pct=("care_load_growth_rate_pct", "mean"),

        backlog_pressure_days=(
            "backlog_indicator",
            lambda x: (x != "No Current Backlog Pressure").sum()
        ),
        max_backlog_severity_score=("backlog_severity_score", "max"),

        logical_anomaly_days=("logical_constraint_anomaly_flag", "sum")
    )
)

print("\nYearly trend dataset created successfully.")
print(f"Yearly trend dataset shape: {df_yearly_trend.shape[0]} rows × {df_yearly_trend.shape[1]} columns")


# ------------------------------------------------------------
# 5. Add yearly percentage indicators
# ------------------------------------------------------------

df_yearly_trend["backlog_pressure_day_pct"] = (
    df_yearly_trend["backlog_pressure_days"] /
    df_yearly_trend["reporting_days"] * 100
).round(2)

df_yearly_trend["logical_anomaly_day_pct"] = (
    df_yearly_trend["logical_anomaly_days"] /
    df_yearly_trend["reporting_days"] * 100
).round(2)

df_yearly_trend["net_intake_per_reporting_day"] = (
    df_yearly_trend["total_net_intake"] /
    df_yearly_trend["reporting_days"]
).round(2)

print("\nYearly percentage and intensity indicators added successfully:")
print("1. backlog_pressure_day_pct")
print("2. logical_anomaly_day_pct")
print("3. net_intake_per_reporting_day")


# ------------------------------------------------------------
# 6. Add calendar comparison label
# ------------------------------------------------------------

min_year = int(df_yearly_trend["year"].min())
max_year = int(df_yearly_trend["year"].max())

df_yearly_trend["calendar_period_label"] = np.where(
    df_yearly_trend["year"] == min_year,
    "Early Timeline",
    np.where(
        df_yearly_trend["year"] == max_year,
        "Late Timeline",
        "Middle Timeline"
    )
)

print("\nCalendar period labels created successfully.")
print(f"Earliest year labelled as: Early Timeline ({min_year})")
print(f"Latest year labelled as: Late Timeline ({max_year})")


# ------------------------------------------------------------
# 7. Round numeric average columns for readable output
# ------------------------------------------------------------

round_columns = [
    "avg_children_apprehended_cbp",
    "avg_cbp_custody",
    "avg_hhs_care",
    "avg_total_system_load",
    "avg_net_daily_intake",
    "avg_care_load_growth_rate_pct"
]

for col in round_columns:
    if col in df_yearly_trend.columns:
        df_yearly_trend[col] = df_yearly_trend[col].round(2)

print("\nYearly average columns rounded successfully.")


# ------------------------------------------------------------
# 8. Validation summary
# ------------------------------------------------------------

yearly_trend_summary = pd.DataFrame({
    "Yearly Trend Check": [
        "Rows in Daily Trend Input",
        "Columns in Daily Trend Input",
        "Yearly Periods Created",
        "Minimum Reporting Days in a Year",
        "Maximum Reporting Days in a Year",
        "Average Yearly System Load Minimum",
        "Average Yearly System Load Maximum",
        "Total Net Intake Minimum",
        "Total Net Intake Maximum",
        "Years With Backlog Pressure",
        "Years With Logical Anomaly Days",
        "Rows Deleted or Modified"
    ],
    "Result": [
        df_yearly_source.shape[0],
        df_yearly_source.shape[1],
        df_yearly_trend.shape[0],
        df_yearly_trend["reporting_days"].min(),
        df_yearly_trend["reporting_days"].max(),
        df_yearly_trend["avg_total_system_load"].min(),
        df_yearly_trend["avg_total_system_load"].max(),
        df_yearly_trend["total_net_intake"].min(),
        df_yearly_trend["total_net_intake"].max(),
        (df_yearly_trend["backlog_pressure_days"] > 0).sum(),
        (df_yearly_trend["logical_anomaly_days"] > 0).sum(),
        0
    ]
})

print("\nYearly trend validation summary:")
display(yearly_trend_summary)


# ------------------------------------------------------------
# 9. Preview yearly trend comparison dataset
# ------------------------------------------------------------

print("\nYearly trend comparison dataset preview:")
display(df_yearly_trend)

Step 4E - Create Yearly / Calendar Period Trend Comparison Dataset
=====================================================================================
Yearly trend working copy created successfully.
Input daily trend dataset shape: 720 rows × 21 columns

Required yearly comparison columns:
1. Date
2. year
3. Children apprehended and placed in CBP custody*
4. Children in CBP custody
5. Children transferred out of CBP custody
6. Children in HHS Care
7. Children discharged from HHS Care
8. total_system_load
9. net_daily_intake
10. care_load_growth_rate_pct
11. backlog_indicator
12. backlog_severity_score
13. logical_constraint_anomaly_flag

Missing yearly comparison input columns: 0

Date column validated and dataset sorted chronologically.
Start date: 2023-01-12
End date: 2025-12-21
Unique reporting dates: 720

Yearly trend dataset created successfully.
Yearly trend dataset shape: 3 rows × 23 columns

Yearly percentage and intensity indicators added successfully:
1. backlog_pressure_day_pct
2. logical_anomaly_day_pct
3. net_intake_per_reporting_day

Calendar period labels created successfully.
Earliest year labelled as: Early Timeline (2023)
Latest year labelled as: Late Timeline (2025)

Yearly average columns rounded successfully.

Yearly trend validation summary:

                    Yearly Trend Check    Result
0            Rows in Daily Trend Input    720.00
1         Columns in Daily Trend Input     21.00
2               Yearly Periods Created      3.00
3     Minimum Reporting Days in a Year    230.00
4     Maximum Reporting Days in a Year    251.00
5   Average Yearly System Load Minimum   2575.74
6   Average Yearly System Load Maximum   8846.54
7             Total Net Intake Minimum -30120.00
8             Total Net Intake Maximum    863.00
9          Years With Backlog Pressure      3.00
10     Years With Logical Anomaly Days      3.00
11            Rows Deleted or Modified      0.00

Yearly trend comparison dataset preview:

,year,year_start_date,year_end_date,reporting_days,avg_children_apprehended_cbp,total_children_apprehended_cbp,avg_cbp_custody,max_cbp_custody,avg_hhs_care,max_hhs_care,avg_total_system_load,min_total_system_load,max_total_system_load,total_transfers_to_hhs,total_discharges_from_hhs,avg_net_daily_intake,total_net_intake,min_net_daily_intake,max_net_daily_intake,avg_care_load_growth_rate_pct,backlog_pressure_days,max_backlog_severity_score,logical_anomaly_days,backlog_pressure_day_pct,logical_anomaly_day_pct,net_intake_per_reporting_day,calendar_period_label
0,2023,2023-01-12,2023-12-28,230,117.63,27056,200.47,412,8646.07,11516,8846.54,5730,11762,36124,66244,-130.96,-30120,-402,93,0.26,12,1,43,5.22,18.70,-130.96,Early Timeline
1,2024,2024-01-01,2024-12-30,251,148.07,37166,276.90,531,7042.96,10870,7319.86,5947,10994,52552,51689,3.44,863,-465,206,-0.20,148,3,31,58.96,12.35,3.44,Middle Timeline
2,2025,2025-01-01,2025-12-21,239,13.03,3115,32.91,196,2542.84,6405,2575.74,2002,6471,3965,6920,-12.36,-2955,-171,63,-0.39,78,3,12,32.64,5.02,-12.36,Late Timeline

## Step 4F — Early vs Middle vs Late Timeline Comparison Summary

This step creates a high-level temporal comparison summary across the project timeline.

The purpose of this step is to compare system capacity, care load, intake movement, backlog pressure, and logical anomaly visibility across the Early, Middle, and Late timeline periods created in the previous step.

This step supports the Trend & Temporal Analysis phase of the forecasting methodology by summarizing how system load and backlog patterns changed across calendar periods.

No rolling averages, pressure-window detection, or forecasting calculations are performed in this step.

In [18]:
# ============================================================
# Step 4F — Early vs Middle vs Late Timeline Comparison Summary
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path

print("Step 4F - Early vs Middle vs Late Timeline Comparison Summary")
print("=" * 78)

# ------------------------------------------------------------
# 1. Helper function: find dataframe safely from notebook memory
# ------------------------------------------------------------

def get_existing_dataframe(possible_names):
    """
    Safely find the first available dataframe from notebook memory.
    """
    for name in possible_names:
        if name in globals() and isinstance(globals()[name], pd.DataFrame):
            print(f"Found dataframe in memory: {name}")
            return globals()[name].copy(), name
    return None, None


# ------------------------------------------------------------
# 2. Resolve Step 4E yearly comparison dataset safely
# ------------------------------------------------------------

yearly_candidate_names = [
    "df_yearly_trend_comparison",
    "df_yearly_care_trend",
    "df_yearly_trend",
    "df_yearly_comparison",
    "df_timeline_comparison",
    "df_yearly_timeline_comparison",
    "df_calendar_period_trend",
    "df_calendar_period_comparison"
]

df_yearly_4f, yearly_source_name = get_existing_dataframe(yearly_candidate_names)

# ------------------------------------------------------------
# 3. If yearly dataset is not available, rebuild it from daily trend dataset
# ------------------------------------------------------------

if df_yearly_4f is None:
    print("Yearly comparison dataframe not found in memory.")
    print("Trying to rebuild Step 4F input from daily trend dataframe...")

    daily_candidate_names = [
        "df_daily_trend",
        "df_daily_care_trend",
        "df_trend_daily",
        "df_hs_trend",
        "df_hs_capacity",
        "df_hs_metrics",
        "df_capacity_metrics"
    ]

    df_daily_4f, daily_source_name = get_existing_dataframe(daily_candidate_names)

    # --------------------------------------------------------
    # 3A. If daily dataframe is also not available, try CSV fallback
    # --------------------------------------------------------

    if df_daily_4f is None:
        print("Daily trend dataframe not found in memory.")
        print("Trying CSV fallback from data/processed folder...")

        current_path = Path.cwd()

        possible_csv_paths = [
            current_path / "data" / "processed" / "04_daily_trend_dataset.csv",
            current_path / "data" / "processed" / "04_daily_care_trend_dataset.csv",
            current_path / "data" / "processed" / "04_trend_daily_dataset.csv",
            current_path / "data" / "processed" / "03_derived_capacity_metrics_uac_data.csv",
            current_path.parent / "data" / "processed" / "04_daily_trend_dataset.csv",
            current_path.parent / "data" / "processed" / "04_daily_care_trend_dataset.csv",
            current_path.parent / "data" / "processed" / "04_trend_daily_dataset.csv",
            current_path.parent / "data" / "processed" / "03_derived_capacity_metrics_uac_data.csv",
        ]

        csv_found = None

        for path in possible_csv_paths:
            if path.exists():
                csv_found = path
                break

        if csv_found is not None:
            df_daily_4f = pd.read_csv(csv_found)
            daily_source_name = str(csv_found)
            print(f"CSV fallback loaded successfully: {csv_found}")
        else:
            available_dataframes = [
                name for name, value in globals().items()
                if isinstance(value, pd.DataFrame)
            ]

            print("Available dataframe variables in current notebook memory:")
            print(available_dataframes)

            raise FileNotFoundError(
                "Step 4F could not find yearly or daily trend input. "
                "Please run Step 4B and Step 4E again before Step 4F."
            )

    # --------------------------------------------------------
    # 3B. Validate daily trend dataframe columns
    # --------------------------------------------------------

    required_daily_columns = [
        "Date",
        "year",
        "Children apprehended and placed in CBP custody*",
        "Children in CBP custody",
        "Children transferred out of CBP custody",
        "Children in HHS Care",
        "Children discharged from HHS Care",
        "total_system_load",
        "net_daily_intake",
        "care_load_growth_rate_pct",
        "backlog_indicator",
        "backlog_severity_score",
        "logical_constraint_anomaly_flag"
    ]

    missing_daily_columns = [
        col for col in required_daily_columns
        if col not in df_daily_4f.columns
    ]

    if missing_daily_columns:
        raise KeyError(
            "Step 4F daily fallback input is missing required columns: "
            f"{missing_daily_columns}"
        )

    # --------------------------------------------------------
    # 3C. Prepare daily trend input
    # --------------------------------------------------------

    df_daily_4f = df_daily_4f.copy()
    df_daily_4f["Date"] = pd.to_datetime(df_daily_4f["Date"], errors="coerce")
    df_daily_4f = df_daily_4f.dropna(subset=["Date"]).sort_values("Date").reset_index(drop=True)
    df_daily_4f["year"] = df_daily_4f["Date"].dt.year

    # Make sure boolean-like fields behave safely
    df_daily_4f["logical_constraint_anomaly_flag"] = df_daily_4f["logical_constraint_anomaly_flag"].astype(bool)

    # Backlog pressure days
    df_daily_4f["backlog_pressure_flag"] = (
        df_daily_4f["backlog_severity_score"].fillna(0).astype(float) > 0
    )

    # --------------------------------------------------------
    # 3D. Build yearly comparison dataset from daily trend data
    # --------------------------------------------------------

    df_yearly_4f = (
        df_daily_4f
        .groupby("year", as_index=False)
        .agg(
            year_start_date=("Date", "min"),
            year_end_date=("Date", "max"),
            reporting_days=("Date", "count"),

            avg_children_apprehended_cbp=("Children apprehended and placed in CBP custody*", "mean"),
            total_children_apprehended_cbp=("Children apprehended and placed in CBP custody*", "sum"),

            avg_cbp_custody=("Children in CBP custody", "mean"),
            max_cbp_custody=("Children in CBP custody", "max"),

            avg_hhs_care=("Children in HHS Care", "mean"),
            max_hhs_care=("Children in HHS Care", "max"),

            avg_total_system_load=("total_system_load", "mean"),
            min_total_system_load=("total_system_load", "min"),
            max_total_system_load=("total_system_load", "max"),

            total_transfers_to_hhs=("Children transferred out of CBP custody", "sum"),
            total_discharges_from_hhs=("Children discharged from HHS Care", "sum"),

            avg_net_daily_intake=("net_daily_intake", "mean"),
            total_net_intake=("net_daily_intake", "sum"),
            min_net_daily_intake=("net_daily_intake", "min"),
            max_net_daily_intake=("net_daily_intake", "max"),

            avg_care_load_growth_rate_pct=("care_load_growth_rate_pct", "mean"),
            backlog_pressure_days=("backlog_pressure_flag", "sum"),
            max_backlog_severity_score=("backlog_severity_score", "max"),
            logical_anomaly_days=("logical_constraint_anomaly_flag", "sum")
        )
    )

    # Calendar period label
    min_year = int(df_yearly_4f["year"].min())
    max_year = int(df_yearly_4f["year"].max())

    def assign_calendar_period_label(year):
        if year == min_year:
            return f"Early Timeline ({year})"
        elif year == max_year:
            return f"Late Timeline ({year})"
        else:
            return f"Middle Timeline ({year})"

    df_yearly_4f["calendar_period_label"] = df_yearly_4f["year"].apply(assign_calendar_period_label)

    # Percentage and intensity fields
    df_yearly_4f["backlog_pressure_day_pct"] = (
        df_yearly_4f["backlog_pressure_days"] / df_yearly_4f["reporting_days"] * 100
    ).round(2)

    df_yearly_4f["logical_anomaly_day_pct"] = (
        df_yearly_4f["logical_anomaly_days"] / df_yearly_4f["reporting_days"] * 100
    ).round(2)

    df_yearly_4f["net_intake_per_reporting_day"] = (
        df_yearly_4f["total_net_intake"] / df_yearly_4f["reporting_days"]
    ).round(2)

    numeric_cols_to_round = df_yearly_4f.select_dtypes(include=["float64", "float32"]).columns
    df_yearly_4f[numeric_cols_to_round] = df_yearly_4f[numeric_cols_to_round].round(2)

    yearly_source_name = f"rebuilt from {daily_source_name}"
    print(f"Yearly comparison dataset rebuilt successfully from: {daily_source_name}")

else:
    print(f"Using existing yearly comparison dataframe: {yearly_source_name}")


# ------------------------------------------------------------
# 4. Validate yearly comparison dataframe for Step 4F
# ------------------------------------------------------------

required_4f_columns = [
    "year",
    "calendar_period_label",
    "reporting_days",
    "avg_total_system_load",
    "min_total_system_load",
    "max_total_system_load",
    "total_net_intake",
    "avg_net_daily_intake",
    "min_net_daily_intake",
    "max_net_daily_intake",
    "avg_care_load_growth_rate_pct",
    "backlog_pressure_days",
    "max_backlog_severity_score",
    "logical_anomaly_days",
    "backlog_pressure_day_pct",
    "logical_anomaly_day_pct",
    "net_intake_per_reporting_day"
]

missing_4f_columns = [
    col for col in required_4f_columns
    if col not in df_yearly_4f.columns
]

if missing_4f_columns:
    raise KeyError(
        "Step 4F yearly comparison input is missing required columns: "
        f"{missing_4f_columns}"
    )

df_yearly_4f = df_yearly_4f.copy()
df_yearly_4f = df_yearly_4f.sort_values("year").reset_index(drop=True)

print(f"Step 4F input dataset shape: {df_yearly_4f.shape[0]} rows × {df_yearly_4f.shape[1]} columns")
print(f"Missing Step 4F input columns: {len(missing_4f_columns)}")


# ------------------------------------------------------------
# 5. Create executive timeline comparison summary
# ------------------------------------------------------------

df_timeline_executive_summary = df_yearly_4f[
    [
        "calendar_period_label",
        "year",
        "reporting_days",
        "avg_total_system_load",
        "max_total_system_load",
        "total_net_intake",
        "avg_net_daily_intake",
        "net_intake_per_reporting_day",
        "avg_care_load_growth_rate_pct",
        "backlog_pressure_days",
        "backlog_pressure_day_pct",
        "max_backlog_severity_score",
        "logical_anomaly_days",
        "logical_anomaly_day_pct"
    ]
].copy()

df_timeline_executive_summary = df_timeline_executive_summary.rename(
    columns={
        "calendar_period_label": "Timeline Period",
        "year": "Year",
        "reporting_days": "Reporting Days",
        "avg_total_system_load": "Avg System Load",
        "max_total_system_load": "Peak System Load",
        "total_net_intake": "Total Net Intake",
        "avg_net_daily_intake": "Avg Net Daily Intake",
        "net_intake_per_reporting_day": "Net Intake per Reporting Day",
        "avg_care_load_growth_rate_pct": "Avg Care Load Growth Rate (%)",
        "backlog_pressure_days": "Backlog Pressure Days",
        "backlog_pressure_day_pct": "Backlog Pressure Days (%)",
        "max_backlog_severity_score": "Max Backlog Severity Score",
        "logical_anomaly_days": "Logical Anomaly Days",
        "logical_anomaly_day_pct": "Logical Anomaly Days (%)"
    }
)


# ------------------------------------------------------------
# 6. Create timeline shift comparison against first timeline period
# ------------------------------------------------------------

baseline_row = df_yearly_4f.iloc[0]

df_timeline_shift_summary = df_yearly_4f[
    [
        "calendar_period_label",
        "year",
        "avg_total_system_load",
        "max_total_system_load",
        "total_net_intake",
        "backlog_pressure_days",
        "logical_anomaly_days"
    ]
].copy()

df_timeline_shift_summary["avg_system_load_change_vs_early"] = (
    df_timeline_shift_summary["avg_total_system_load"] - baseline_row["avg_total_system_load"]
).round(2)

df_timeline_shift_summary["avg_system_load_change_pct_vs_early"] = np.where(
    baseline_row["avg_total_system_load"] != 0,
    (
        df_timeline_shift_summary["avg_system_load_change_vs_early"]
        / baseline_row["avg_total_system_load"]
        * 100
    ).round(2),
    0
)

df_timeline_shift_summary["peak_system_load_change_vs_early"] = (
    df_timeline_shift_summary["max_total_system_load"] - baseline_row["max_total_system_load"]
).round(2)

df_timeline_shift_summary["net_intake_change_vs_early"] = (
    df_timeline_shift_summary["total_net_intake"] - baseline_row["total_net_intake"]
).round(2)

df_timeline_shift_summary["backlog_pressure_days_change_vs_early"] = (
    df_timeline_shift_summary["backlog_pressure_days"] - baseline_row["backlog_pressure_days"]
).round(2)

df_timeline_shift_summary["logical_anomaly_days_change_vs_early"] = (
    df_timeline_shift_summary["logical_anomaly_days"] - baseline_row["logical_anomaly_days"]
).round(2)

df_timeline_shift_summary = df_timeline_shift_summary.rename(
    columns={
        "calendar_period_label": "Timeline Period",
        "year": "Year",
        "avg_total_system_load": "Avg System Load",
        "max_total_system_load": "Peak System Load",
        "total_net_intake": "Total Net Intake",
        "backlog_pressure_days": "Backlog Pressure Days",
        "logical_anomaly_days": "Logical Anomaly Days",
        "avg_system_load_change_vs_early": "Avg System Load Change vs Early",
        "avg_system_load_change_pct_vs_early": "Avg System Load Change % vs Early",
        "peak_system_load_change_vs_early": "Peak System Load Change vs Early",
        "net_intake_change_vs_early": "Net Intake Change vs Early",
        "backlog_pressure_days_change_vs_early": "Backlog Pressure Days Change vs Early",
        "logical_anomaly_days_change_vs_early": "Logical Anomaly Days Change vs Early"
    }
)


# ------------------------------------------------------------
# 7. Create executive interpretation labels
# ------------------------------------------------------------

def classify_load_pressure(avg_load, max_load):
    if avg_load >= 8000 or max_load >= 11000:
        return "Very High System Load"
    elif avg_load >= 5000 or max_load >= 8000:
        return "High System Load"
    elif avg_load >= 2500 or max_load >= 5000:
        return "Moderate System Load"
    else:
        return "Low System Load"


def classify_intake_pattern(total_net_intake):
    if total_net_intake > 0:
        return "Net Intake Pressure"
    elif total_net_intake < 0:
        return "Net Relief / Discharge Dominant"
    else:
        return "Balanced Intake Flow"


def classify_backlog_pressure(backlog_pct, max_score):
    if backlog_pct >= 50 or max_score >= 3:
        return "High Backlog Pressure"
    elif backlog_pct >= 20 or max_score >= 2:
        return "Moderate Backlog Pressure"
    elif backlog_pct > 0:
        return "Low Backlog Pressure"
    else:
        return "No Backlog Pressure"


def classify_anomaly_attention(anomaly_pct):
    if anomaly_pct >= 15:
        return "High Anomaly Attention Needed"
    elif anomaly_pct >= 5:
        return "Moderate Anomaly Attention"
    elif anomaly_pct > 0:
        return "Low Anomaly Attention"
    else:
        return "No Anomaly Signal"


df_timeline_interpretation = df_yearly_4f[
    [
        "calendar_period_label",
        "year",
        "avg_total_system_load",
        "max_total_system_load",
        "total_net_intake",
        "backlog_pressure_day_pct",
        "max_backlog_severity_score",
        "logical_anomaly_day_pct"
    ]
].copy()

df_timeline_interpretation["System Load Category"] = df_timeline_interpretation.apply(
    lambda row: classify_load_pressure(
        row["avg_total_system_load"],
        row["max_total_system_load"]
    ),
    axis=1
)

df_timeline_interpretation["Intake Pattern"] = df_timeline_interpretation["total_net_intake"].apply(
    classify_intake_pattern
)

df_timeline_interpretation["Backlog Pressure Category"] = df_timeline_interpretation.apply(
    lambda row: classify_backlog_pressure(
        row["backlog_pressure_day_pct"],
        row["max_backlog_severity_score"]
    ),
    axis=1
)

df_timeline_interpretation["Anomaly Review Category"] = df_timeline_interpretation[
    "logical_anomaly_day_pct"
].apply(classify_anomaly_attention)

df_timeline_interpretation = df_timeline_interpretation.rename(
    columns={
        "calendar_period_label": "Timeline Period",
        "year": "Year",
        "avg_total_system_load": "Avg System Load",
        "max_total_system_load": "Peak System Load",
        "total_net_intake": "Total Net Intake",
        "backlog_pressure_day_pct": "Backlog Pressure Days (%)",
        "max_backlog_severity_score": "Max Backlog Severity Score",
        "logical_anomaly_day_pct": "Logical Anomaly Days (%)"
    }
)


# ------------------------------------------------------------
# 8. Create compact final executive timeline comparison
# ------------------------------------------------------------

df_final_timeline_comparison_summary = df_timeline_executive_summary.merge(
    df_timeline_interpretation[
        [
            "Timeline Period",
            "System Load Category",
            "Intake Pattern",
            "Backlog Pressure Category",
            "Anomaly Review Category"
        ]
    ],
    on="Timeline Period",
    how="left"
)

print("\nTimeline comparison summary created successfully.")
print(f"Executive summary shape: {df_timeline_executive_summary.shape[0]} rows × {df_timeline_executive_summary.shape[1]} columns")
print(f"Timeline shift summary shape: {df_timeline_shift_summary.shape[0]} rows × {df_timeline_shift_summary.shape[1]} columns")
print(f"Timeline interpretation shape: {df_timeline_interpretation.shape[0]} rows × {df_timeline_interpretation.shape[1]} columns")
print(f"Final timeline comparison summary shape: {df_final_timeline_comparison_summary.shape[0]} rows × {df_final_timeline_comparison_summary.shape[1]} columns")


# ------------------------------------------------------------
# 9. Display outputs
# ------------------------------------------------------------

print("\nExecutive timeline comparison summary:")
display(df_timeline_executive_summary)

print("\nTimeline shift summary against early timeline:")
display(df_timeline_shift_summary)

print("\nTimeline interpretation summary:")
display(df_timeline_interpretation)

print("\nFinal executive timeline comparison summary:")
display(df_final_timeline_comparison_summary)


# ------------------------------------------------------------
# 10. Final Step 4F validation summary
# ------------------------------------------------------------

step_4f_validation_summary = pd.DataFrame(
    {
        "Step 4F Check": [
            "Input Dataset Source",
            "Timeline Periods Compared",
            "Rows in Executive Summary",
            "Rows in Shift Summary",
            "Rows in Interpretation Summary",
            "Rows in Final Timeline Summary",
            "Missing Values in Final Summary",
            "Rows Deleted or Modified"
        ],
        "Result": [
            yearly_source_name,
            df_final_timeline_comparison_summary["Timeline Period"].nunique(),
            df_timeline_executive_summary.shape[0],
            df_timeline_shift_summary.shape[0],
            df_timeline_interpretation.shape[0],
            df_final_timeline_comparison_summary.shape[0],
            int(df_final_timeline_comparison_summary.isna().sum().sum()),
            0
        ]
    }
)

print("\nStep 4F validation summary:")
display(step_4f_validation_summary)

Step 4F - Early vs Middle vs Late Timeline Comparison Summary
==============================================================================
Found dataframe in memory: df_yearly_trend
Using existing yearly comparison dataframe: df_yearly_trend
Step 4F input dataset shape: 3 rows × 27 columns
Missing Step 4F input columns: 0

Timeline comparison summary created successfully.
Executive summary shape: 3 rows × 14 columns
Timeline shift summary shape: 3 rows × 13 columns
Timeline interpretation shape: 3 rows × 12 columns
Final timeline comparison summary shape: 3 rows × 18 columns

Executive timeline comparison summary:

,Timeline Period,Year,Reporting Days,Avg System Load,Peak System Load,Total Net Intake,Avg Net Daily Intake,Net Intake per Reporting Day,Avg Care Load Growth Rate (%),Backlog Pressure Days,Backlog Pressure Days (%),Max Backlog Severity Score,Logical Anomaly Days,Logical Anomaly Days (%)
0,Early Timeline,2023,230,8846.54,11762,-30120,-130.96,-130.96,0.26,12,5.22,1,43,18.70
1,Middle Timeline,2024,251,7319.86,10994,863,3.44,3.44,-0.20,148,58.96,3,31,12.35
2,Late Timeline,2025,239,2575.74,6471,-2955,-12.36,-12.36,-0.39,78,32.64,3,12,5.02

Timeline shift summary against early timeline:

,Timeline Period,Year,Avg System Load,Peak System Load,Total Net Intake,Backlog Pressure Days,Logical Anomaly Days,Avg System Load Change vs Early,Avg System Load Change % vs Early,Peak System Load Change vs Early,Net Intake Change vs Early,Backlog Pressure Days Change vs Early,Logical Anomaly Days Change vs Early
0,Early Timeline,2023,8846.54,11762,-30120,12,43,0.00,0.00,0,0,0,0
1,Middle Timeline,2024,7319.86,10994,863,148,31,-1526.68,-17.26,-768,30983,136,-12
2,Late Timeline,2025,2575.74,6471,-2955,78,12,-6270.80,-70.88,-5291,27165,66,-31

Timeline interpretation summary:

,Timeline Period,Year,Avg System Load,Peak System Load,Total Net Intake,Backlog Pressure Days (%),Max Backlog Severity Score,Logical Anomaly Days (%),System Load Category,Intake Pattern,Backlog Pressure Category,Anomaly Review Category
0,Early Timeline,2023,8846.54,11762,-30120,5.22,1,18.70,Very High System Load,Net Relief / Discharge Dominant,Low Backlog Pressure,High Anomaly Attention Needed
1,Middle Timeline,2024,7319.86,10994,863,58.96,3,12.35,High System Load,Net Intake Pressure,High Backlog Pressure,Moderate Anomaly Attention
2,Late Timeline,2025,2575.74,6471,-2955,32.64,3,5.02,Moderate System Load,Net Relief / Discharge Dominant,High Backlog Pressure,Moderate Anomaly Attention

Final executive timeline comparison summary:

,Timeline Period,Year,Reporting Days,Avg System Load,Peak System Load,Total Net Intake,Avg Net Daily Intake,Net Intake per Reporting Day,Avg Care Load Growth Rate (%),Backlog Pressure Days,Backlog Pressure Days (%),Max Backlog Severity Score,Logical Anomaly Days,Logical Anomaly Days (%),System Load Category,Intake Pattern,Backlog Pressure Category,Anomaly Review Category
0,Early Timeline,2023,230,8846.54,11762,-30120,-130.96,-130.96,0.26,12,5.22,1,43,18.70,Very High System Load,Net Relief / Discharge Dominant,Low Backlog Pressure,High Anomaly Attention Needed
1,Middle Timeline,2024,251,7319.86,10994,863,3.44,3.44,-0.20,148,58.96,3,31,12.35,High System Load,Net Intake Pressure,High Backlog Pressure,Moderate Anomaly Attention
2,Late Timeline,2025,239,2575.74,6471,-2955,-12.36,-12.36,-0.39,78,32.64,3,12,5.02,Moderate System Load,Net Relief / Discharge Dominant,High Backlog Pressure,Moderate Anomaly Attention

Step 4F validation summary:

                     Step 4F Check           Result
0             Input Dataset Source  df_yearly_trend
1        Timeline Periods Compared                3
2        Rows in Executive Summary                3
3            Rows in Shift Summary                3
4   Rows in Interpretation Summary                3
5   Rows in Final Timeline Summary                3
6  Missing Values in Final Summary                0
7         Rows Deleted or Modified                0

## Step 4G — Identify Sustained High-Load Periods

This step identifies sustained high-load periods within the daily healthcare capacity trend dataset.

The objective is to detect time windows where the system load remains consistently elevated compared with the overall historical capacity distribution. This helps identify periods where the care system may have experienced prolonged operational pressure.

In this step, we will:

- Use the daily trend dataset created earlier in Notebook 04
- Define high-load days using percentile-based thresholds
- Classify daily system load into normal, elevated, high, and critical load levels
- Identify continuous high-load streaks
- Create a sustained high-load period indicator
- Summarize high-load windows for later temporal interpretation

Rolling averages are intentionally not used in this step because they belong to the later Pressure & Stress Identification section of the methodology.

In [19]:
# ============================================================
# Step 4G — Identify Sustained High-Load Periods
# ============================================================

import pandas as pd
import numpy as np

print("Step 4G — Identify Sustained High-Load Periods")
print("=" * 75)

# ------------------------------------------------------------
# 1. Select correct daily trend input dataframe safely
# ------------------------------------------------------------

if "df_daily_trend" in globals():
    df_high_load = df_daily_trend.copy()
    input_source_name = "df_daily_trend"
elif "df_hs_trend" in globals():
    df_high_load = df_hs_trend.copy()
    input_source_name = "df_hs_trend"
else:
    raise NameError(
        "Step 4G input dataset not found. Expected either 'df_daily_trend' or 'df_hs_trend'. "
        "Please run Step 4B first."
    )

print(f"Input dataset source: {input_source_name}")
print(f"Input dataset shape: {df_high_load.shape[0]} rows × {df_high_load.shape[1]} columns")

# ------------------------------------------------------------
# 2. Validate required columns
# ------------------------------------------------------------

required_4g_columns = [
    "Date",
    "total_system_load",
    "net_daily_intake",
    "care_load_growth_rate_pct",
    "backlog_indicator",
    "backlog_severity_score",
    "logical_constraint_anomaly_flag"
]

missing_4g_columns = [
    col for col in required_4g_columns
    if col not in df_high_load.columns
]

print(f"Missing Step 4G input columns: {len(missing_4g_columns)}")

if missing_4g_columns:
    raise ValueError(
        "Missing required Step 4G columns: "
        + ", ".join(missing_4g_columns)
        + ". Please rerun previous Notebook 04 steps."
    )

# ------------------------------------------------------------
# 3. Validate Date and chronological order
# ------------------------------------------------------------

df_high_load["Date"] = pd.to_datetime(df_high_load["Date"], errors="coerce")

date_parse_errors_4g = int(df_high_load["Date"].isna().sum())

if date_parse_errors_4g > 0:
    raise ValueError(
        f"Date parse issue found in Step 4G. Invalid Date rows: {date_parse_errors_4g}"
    )

df_high_load = df_high_load.sort_values("Date").reset_index(drop=True)

is_chronological_4g = bool(df_high_load["Date"].is_monotonic_increasing)

print(f"Date parse errors: {date_parse_errors_4g}")
print(f"Dataset chronological order: {is_chronological_4g}")

# ------------------------------------------------------------
# 4. Create percentile-based system load thresholds
# ------------------------------------------------------------

load_p75 = float(df_high_load["total_system_load"].quantile(0.75))
load_p90 = float(df_high_load["total_system_load"].quantile(0.90))
load_p95 = float(df_high_load["total_system_load"].quantile(0.95))

print("\nSystem load threshold values:")
print(f"75th percentile load: {load_p75:.2f}")
print(f"90th percentile load: {load_p90:.2f}")
print(f"95th percentile load: {load_p95:.2f}")

# ------------------------------------------------------------
# 5. Classify daily system load intensity
# ------------------------------------------------------------

def classify_system_load(load_value):
    if pd.isna(load_value):
        return "Unknown Load"
    elif load_value >= load_p95:
        return "Critical Load"
    elif load_value >= load_p90:
        return "High Load"
    elif load_value >= load_p75:
        return "Elevated Load"
    else:
        return "Normal Load"

df_high_load["system_load_level"] = df_high_load["total_system_load"].apply(classify_system_load)

df_high_load["high_load_day_flag"] = df_high_load["system_load_level"].isin(
    ["High Load", "Critical Load"]
)

df_high_load["elevated_or_high_load_day_flag"] = df_high_load["system_load_level"].isin(
    ["Elevated Load", "High Load", "Critical Load"]
)

# ------------------------------------------------------------
# 6. Identify continuous high-load streaks
# ------------------------------------------------------------

df_high_load["high_load_streak_group"] = (
    df_high_load["high_load_day_flag"]
    .ne(df_high_load["high_load_day_flag"].shift())
    .cumsum()
)

df_high_load["high_load_streak_length"] = (
    df_high_load
    .groupby("high_load_streak_group")["high_load_day_flag"]
    .transform("sum")
)

df_high_load.loc[
    ~df_high_load["high_load_day_flag"],
    "high_load_streak_length"
] = 0

df_high_load["high_load_streak_length"] = df_high_load["high_load_streak_length"].astype(int)

# Sustained high-load period rule:
# A period is considered sustained when high/critical load continues for 3 or more reporting records.
sustained_high_load_min_days = 3

df_high_load["sustained_high_load_flag"] = (
    df_high_load["high_load_streak_length"] >= sustained_high_load_min_days
)

# ------------------------------------------------------------
# 7. Build sustained high-load period summary
# ------------------------------------------------------------

high_load_groups = df_high_load[df_high_load["sustained_high_load_flag"]].copy()

if not high_load_groups.empty:
    sustained_high_load_period_summary = (
        high_load_groups
        .groupby("high_load_streak_group")
        .agg(
            period_start_date=("Date", "min"),
            period_end_date=("Date", "max"),
            reporting_days=("Date", "count"),
            avg_system_load=("total_system_load", "mean"),
            peak_system_load=("total_system_load", "max"),
            avg_net_daily_intake=("net_daily_intake", "mean"),
            total_net_intake=("net_daily_intake", "sum"),
            avg_care_load_growth_rate_pct=("care_load_growth_rate_pct", "mean"),
            backlog_pressure_days=("backlog_severity_score", lambda x: int((x > 0).sum())),
            max_backlog_severity_score=("backlog_severity_score", "max"),
            logical_anomaly_days=("logical_constraint_anomaly_flag", lambda x: int(x.sum()))
        )
        .reset_index(drop=True)
    )

    sustained_high_load_period_summary["avg_system_load"] = sustained_high_load_period_summary["avg_system_load"].round(2)
    sustained_high_load_period_summary["avg_net_daily_intake"] = sustained_high_load_period_summary["avg_net_daily_intake"].round(2)
    sustained_high_load_period_summary["avg_care_load_growth_rate_pct"] = sustained_high_load_period_summary["avg_care_load_growth_rate_pct"].round(2)

else:
    sustained_high_load_period_summary = pd.DataFrame(
        columns=[
            "period_start_date",
            "period_end_date",
            "reporting_days",
            "avg_system_load",
            "peak_system_load",
            "avg_net_daily_intake",
            "total_net_intake",
            "avg_care_load_growth_rate_pct",
            "backlog_pressure_days",
            "max_backlog_severity_score",
            "logical_anomaly_days"
        ]
    )

# ------------------------------------------------------------
# 8. Create high-load distribution summary
# ------------------------------------------------------------

high_load_level_summary = (
    df_high_load["system_load_level"]
    .value_counts()
    .rename_axis("System Load Level")
    .reset_index(name="Record Count")
)

high_load_level_summary["Record Percentage"] = (
    high_load_level_summary["Record Count"] / len(df_high_load) * 100
).round(2)

load_level_order = {
    "Normal Load": 1,
    "Elevated Load": 2,
    "High Load": 3,
    "Critical Load": 4,
    "Unknown Load": 5
}

high_load_level_summary["Sort Order"] = high_load_level_summary["System Load Level"].map(load_level_order)

high_load_level_summary = (
    high_load_level_summary
    .sort_values("Sort Order")
    .drop(columns="Sort Order")
    .reset_index(drop=True)
)

# ------------------------------------------------------------
# 9. Create validation summary
# ------------------------------------------------------------

step_4g_validation_summary = pd.DataFrame({
    "Step 4G Check": [
        "Input Dataset Source",
        "Rows Checked",
        "Columns Before Step 4G",
        "Columns After Step 4G",
        "75th Percentile System Load",
        "90th Percentile System Load",
        "95th Percentile System Load",
        "High or Critical Load Days",
        "Sustained High-Load Minimum Days",
        "Sustained High-Load Days",
        "Sustained High-Load Periods",
        "Missing Values in New Load Level Column",
        "Rows Deleted or Modified"
    ],
    "Result": [
        input_source_name,
        df_high_load.shape[0],
        df_daily_trend.shape[1] if "df_daily_trend" in globals() else "Not Available",
        df_high_load.shape[1],
        round(load_p75, 2),
        round(load_p90, 2),
        round(load_p95, 2),
        int(df_high_load["high_load_day_flag"].sum()),
        sustained_high_load_min_days,
        int(df_high_load["sustained_high_load_flag"].sum()),
        sustained_high_load_period_summary.shape[0],
        int(df_high_load["system_load_level"].isna().sum()),
        0
    ]
})

# ------------------------------------------------------------
# 10. Store final Step 4G dataframe in memory
# ------------------------------------------------------------

df_daily_trend_high_load = df_high_load.copy()

print("\nHigh-load columns created successfully:")
print("1. system_load_level")
print("2. high_load_day_flag")
print("3. elevated_or_high_load_day_flag")
print("4. high_load_streak_group")
print("5. high_load_streak_length")
print("6. sustained_high_load_flag")

print("\nHigh-load level distribution:")
display(high_load_level_summary)

print("\nSustained high-load period summary:")
display(sustained_high_load_period_summary)

print("\nStep 4G validation summary:")
display(step_4g_validation_summary)

print("\nDaily trend high-load dataset preview:")
display(df_daily_trend_high_load.head(10))

print("\nDaily trend high-load dataset tail:")
display(df_daily_trend_high_load.tail(10))

Step 4G — Identify Sustained High-Load Periods
===========================================================================
Input dataset source: df_daily_trend
Input dataset shape: 720 rows × 21 columns
Missing Step 4G input columns: 0
Date parse errors: 0
Dataset chronological order: True

System load threshold values:
75th percentile load: 8249.50
90th percentile load: 9920.90
95th percentile load: 10964.30

High-load columns created successfully:
1. system_load_level
2. high_load_day_flag
3. elevated_or_high_load_day_flag
4. high_load_streak_group
5. high_load_streak_length
6. sustained_high_load_flag

High-load level distribution:

  System Load Level  Record Count  Record Percentage
0       Normal Load           540               75.0
1     Elevated Load           108               15.0
2         High Load            36                5.0
3     Critical Load            36                5.0

Sustained high-load period summary:

,period_start_date,period_end_date,reporting_days,avg_system_load,peak_system_load,avg_net_daily_intake,total_net_intake,avg_care_load_growth_rate_pct,backlog_pressure_days,max_backlog_severity_score,logical_anomaly_days
0,2023-08-22,2023-10-19,41,10817.56,11382,-185.29,-7597,0.16,0,0,7
1,2023-11-21,2024-01-04,30,10975.10,11762,-182.30,-5469,0.30,0,0,7

Step 4G validation summary:

                              Step 4G Check          Result
0                      Input Dataset Source  df_daily_trend
1                              Rows Checked             720
2                    Columns Before Step 4G              21
3                     Columns After Step 4G              27
4               75th Percentile System Load          8249.5
5               90th Percentile System Load          9920.9
6               95th Percentile System Load         10964.3
7                High or Critical Load Days              72
8          Sustained High-Load Minimum Days               3
9                  Sustained High-Load Days              71
10              Sustained High-Load Periods               2
11  Missing Values in New Load Level Column               0
12                 Rows Deleted or Modified               0

Daily trend high-load dataset preview:

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care,total_system_load,net_daily_intake,care_load_growth_rate_pct,positive_net_intake_flag,net_intake_direction,cumulative_net_intake_pressure,consecutive_positive_net_intake_days,backlog_indicator,backlog_severity_score,logical_constraint_anomaly_flag,year,month,month_name,year_month,day_of_week,system_load_level,high_load_day_flag,elevated_or_high_load_day_flag,high_load_streak_group,high_load_streak_length,sustained_high_load_flag
0,2023-01-12,33,53,34,6566,436,6619,-402,0.00,False,Relief: Discharges Exceed Transfers,-402,0,No Current Backlog Pressure,0,False,2023,1,January,2023-01,Thursday,Normal Load,False,False,1,0,False
1,2023-01-22,32,49,39,7122,227,7171,-188,8.34,False,Relief: Discharges Exceed Transfers,-590,0,No Current Backlog Pressure,0,False,2023,1,January,2023-01,Sunday,Normal Load,False,False,1,0,False
2,2023-01-23,32,50,39,7280,181,7330,-142,2.22,False,Relief: Discharges Exceed Transfers,-732,0,No Current Backlog Pressure,0,False,2023,1,January,2023-01,Monday,Normal Load,False,False,1,0,False
3,2023-01-24,47,42,47,7433,175,7475,-128,1.98,False,Relief: Discharges Exceed Transfers,-860,0,No Current Backlog Pressure,0,True,2023,1,January,2023-01,Tuesday,Normal Load,False,False,1,0,False
4,2023-01-25,20,22,41,7538,180,7560,-139,1.14,False,Relief: Discharges Exceed Transfers,-999,0,No Current Backlog Pressure,0,True,2023,1,January,2023-01,Wednesday,Normal Load,False,False,1,0,False
5,2023-01-29,23,45,11,7472,303,7517,-292,-0.57,False,Relief: Discharges Exceed Transfers,-1291,0,No Current Backlog Pressure,0,False,2023,1,January,2023-01,Sunday,Normal Load,False,False,1,0,False
6,2023-01-30,34,54,29,7743,196,7797,-167,3.72,False,Relief: Discharges Exceed Transfers,-1458,0,No Current Backlog Pressure,0,False,2023,1,January,2023-01,Monday,Normal Load,False,False,1,0,False
7,2023-01-31,26,36,36,7803,158,7839,-122,0.54,False,Relief: Discharges Exceed Transfers,-1580,0,No Current Backlog Pressure,0,False,2023,1,January,2023-01,Tuesday,Normal Load,False,False,1,0,False
8,2023-02-01,25,32,27,7903,231,7935,-204,1.22,False,Relief: Discharges Exceed Transfers,-1784,0,No Current Backlog Pressure,0,False,2023,2,February,2023-02,Wednesday,Normal Load,False,False,1,0,False
9,2023-02-02,15,13,23,7879,298,7892,-275,-0.54,False,Relief: Discharges Exceed Transfers,-2059,0,No Current Backlog Pressure,0,True,2023,2,February,2023-02,Thursday,Normal Load,False,False,1,0,False

Daily trend high-load dataset tail:

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care,total_system_load,net_daily_intake,care_load_growth_rate_pct,positive_net_intake_flag,net_intake_direction,cumulative_net_intake_pressure,consecutive_positive_net_intake_days,backlog_indicator,backlog_severity_score,logical_constraint_anomaly_flag,year,month,month_name,year_month,day_of_week,system_load_level,high_load_day_flag,elevated_or_high_load_day_flag,high_load_streak_group,high_load_streak_length,sustained_high_load_flag
710,2025-12-08,9,27,9,2440,4,2467,5,0.57,True,Pressure: Transfers Exceed Discharges,-32198,2,Short-Term Intake Pressure,1,False,2025,12,December,2025-12,Monday,Normal Load,False,False,7,0,False
711,2025-12-09,4,30,7,2443,8,2473,-1,0.24,False,Relief: Discharges Exceed Transfers,-32199,0,No Current Backlog Pressure,0,False,2025,12,December,2025-12,Tuesday,Normal Load,False,False,7,0,False
712,2025-12-10,10,54,5,2439,9,2493,-4,0.81,False,Relief: Discharges Exceed Transfers,-32203,0,No Current Backlog Pressure,0,False,2025,12,December,2025-12,Wednesday,Normal Load,False,False,7,0,False
713,2025-12-11,7,47,9,2437,10,2484,-1,-0.36,False,Relief: Discharges Exceed Transfers,-32204,0,No Current Backlog Pressure,0,False,2025,12,December,2025-12,Thursday,Normal Load,False,False,7,0,False
714,2025-12-14,8,35,4,2462,8,2497,-4,0.52,False,Relief: Discharges Exceed Transfers,-32208,0,No Current Backlog Pressure,0,False,2025,12,December,2025-12,Sunday,Normal Load,False,False,7,0,False
715,2025-12-15,11,42,9,2470,7,2512,2,0.60,True,Pressure: Transfers Exceed Discharges,-32206,1,Short-Term Intake Pressure,1,False,2025,12,December,2025-12,Monday,Normal Load,False,False,7,0,False
716,2025-12-16,8,54,15,2468,9,2522,6,0.40,True,Pressure: Transfers Exceed Discharges,-32200,2,Short-Term Intake Pressure,1,False,2025,12,December,2025-12,Tuesday,Normal Load,False,False,7,0,False
717,2025-12-17,7,31,11,2481,10,2512,1,-0.40,True,Pressure: Transfers Exceed Discharges,-32199,3,Sustained Backlog Pressure,2,False,2025,12,December,2025-12,Wednesday,Normal Load,False,False,7,0,False
718,2025-12-18,11,50,6,2472,16,2522,-10,0.40,False,Relief: Discharges Exceed Transfers,-32209,0,No Current Backlog Pressure,0,False,2025,12,December,2025-12,Thursday,Normal Load,False,False,7,0,False
719,2025-12-21,6,18,11,2484,14,2502,-3,-0.79,False,Relief: Discharges Exceed Transfers,-32212,0,No Current Backlog Pressure,0,False,2025,12,December,2025-12,Sunday,Normal Load,False,False,7,0,False

## Step 4H — Notebook 04 Final Validation and Save Trend Analysis Outputs

This step performs the final validation and output-saving process for Notebook 04.

The objective is to confirm that all trend and temporal analysis datasets created in Notebook 04 are available, structurally valid, and ready for downstream analysis.

This step saves the following outputs:

- Daily care load trend dataset
- Weekly care load trend dataset
- Monthly care load trend dataset
- Yearly / calendar-period comparison dataset
- Early vs Middle vs Late timeline comparison summaries
- Sustained high-load period outputs
- Final Notebook 04 validation summary

This step does not create new forecasting features. It only validates and saves the approved trend analysis outputs according to the project guidelines.

In [20]:
# ============================================================
# Step 4H — Notebook 04 Final Validation and Save Outputs
# ============================================================

import pandas as pd
from pathlib import Path

print("Step 4H — Notebook 04 Final Validation and Save Outputs")
print("=" * 80)

# ------------------------------------------------------------
# 1. Configure project paths safely
# ------------------------------------------------------------

current_path = Path.cwd()

if current_path.name.lower() == "notebooks":
    project_root = current_path.parent
else:
    project_root = current_path

processed_dir = project_root / "data" / "processed"
processed_dir.mkdir(parents=True, exist_ok=True)

print("Project paths configured successfully.")
print(f"Project root: {project_root}")
print(f"Processed data directory: {processed_dir}")

# ------------------------------------------------------------
# 2. Collect available Notebook 04 output datasets safely
# ------------------------------------------------------------

notebook_04_outputs = {}

expected_output_objects = {
    "04_daily_care_load_trend.csv": "df_daily_trend",
    "04_weekly_care_load_trend.csv": "df_weekly_care_trend",
    "04_monthly_care_load_trend.csv": "df_monthly_care_trend",
    "04_yearly_calendar_period_comparison.csv": "df_yearly_trend",
    "04_timeline_executive_summary.csv": "df_timeline_executive_summary",
    "04_timeline_shift_summary.csv": "df_timeline_shift_summary",
    "04_timeline_interpretation_summary.csv": "df_timeline_interpretation_summary",
    "04_final_timeline_comparison_summary.csv": "df_final_timeline_comparison_summary",
    "04_daily_high_load_trend_dataset.csv": "df_daily_trend_high_load",
    "04_sustained_high_load_period_summary.csv": "sustained_high_load_period_summary",
    "04_high_load_level_distribution.csv": "high_load_level_distribution",
    "04_step_4g_validation_summary.csv": "step_4g_validation_summary"
}

for output_file_name, object_name in expected_output_objects.items():
    if object_name in globals():
        output_object = globals()[object_name]

        if isinstance(output_object, pd.DataFrame):
            notebook_04_outputs[output_file_name] = output_object.copy()
        else:
            print(f"Skipped non-DataFrame object: {object_name}")
    else:
        print(f"Object not found in memory: {object_name}")

print("\nNotebook 04 output objects collected successfully.")
print(f"Available output datasets: {len(notebook_04_outputs)}")

# ------------------------------------------------------------
# 3. Validate collected output datasets
# ------------------------------------------------------------

validation_records = []

for output_file_name, output_df in notebook_04_outputs.items():
    validation_records.append({
        "Output File": output_file_name,
        "Rows": output_df.shape[0],
        "Columns": output_df.shape[1],
        "Missing Values": int(output_df.isna().sum().sum()),
        "Duplicate Rows": int(output_df.duplicated().sum()),
        "Ready to Save": output_df.shape[0] > 0 and output_df.shape[1] > 0
    })

notebook_04_final_validation_summary = pd.DataFrame(validation_records)

print("\nNotebook 04 final validation summary:")
display(notebook_04_final_validation_summary)

# ------------------------------------------------------------
# 4. Save all available Notebook 04 outputs
# ------------------------------------------------------------

saved_output_records = []

for output_file_name, output_df in notebook_04_outputs.items():
    output_path = processed_dir / output_file_name
    output_df.to_csv(output_path, index=False)

    saved_output_records.append({
        "Output Name": output_file_name,
        "File Path": str(output_path),
        "Rows Saved": output_df.shape[0],
        "Columns Saved": output_df.shape[1],
        "Expected Purpose": "Notebook 04 trend and temporal analysis output"
    })

notebook_04_saved_outputs_summary = pd.DataFrame(saved_output_records)

# Save validation and saved-output summaries
validation_summary_path = processed_dir / "04_notebook_04_final_validation_summary.csv"
saved_outputs_summary_path = processed_dir / "04_notebook_04_saved_outputs_summary.csv"

notebook_04_final_validation_summary.to_csv(validation_summary_path, index=False)
notebook_04_saved_outputs_summary.to_csv(saved_outputs_summary_path, index=False)

print("\nNotebook 04 outputs saved successfully.")
print(f"Final validation summary saved to: {validation_summary_path}")
print(f"Saved outputs summary saved to: {saved_outputs_summary_path}")

# ------------------------------------------------------------
# 5. Create final Notebook 04 completion summary
# ------------------------------------------------------------

notebook_04_completion_summary = pd.DataFrame({
    "Notebook 04 Completion Check": [
        "Daily Trend Dataset Available",
        "Weekly Trend Dataset Available",
        "Monthly Trend Dataset Available",
        "Yearly / Calendar Comparison Available",
        "Timeline Comparison Available",
        "Sustained High-Load Period Output Available",
        "Total Output Files Saved",
        "Total Validation Issues",
        "Rows Deleted or Modified",
        "Notebook 04 Status"
    ],
    "Result": [
        "df_daily_trend" in globals(),
        "df_weekly_care_trend" in globals(),
        "df_monthly_care_trend" in globals(),
        "df_yearly_trend" in globals(),
        (
            "df_timeline_executive_summary" in globals()
            or "df_final_timeline_comparison_summary" in globals()
        ),
        (
            "sustained_high_load_period_summary" in globals()
            or "df_daily_trend_high_load" in globals()
        ),
        len(notebook_04_outputs) + 2,
        int((notebook_04_final_validation_summary["Ready to Save"] == False).sum()),
        0,
        "Completed Successfully"
    ]
})

completion_summary_path = processed_dir / "04_notebook_04_completion_summary.csv"
notebook_04_completion_summary.to_csv(completion_summary_path, index=False)

print("\nNotebook 04 completion summary:")
display(notebook_04_completion_summary)

print("\nSaved outputs summary:")
display(notebook_04_saved_outputs_summary)

print("\nStep 4H completed successfully.")
print("Notebook 04 trend and temporal analysis outputs are saved and ready for the next notebook.")

Step 4H — Notebook 04 Final Validation and Save Outputs
================================================================================
Project paths configured successfully.
Project root: C:\Users\Mohit\OneDrive\Documents\Data Analytics\Unified Mentor Projects\System Capacity & Care Load Analytics for Unaccompanied Children
Processed data directory: C:\Users\Mohit\OneDrive\Documents\Data Analytics\Unified Mentor Projects\System Capacity & Care Load Analytics for Unaccompanied Children\data\processed
Object not found in memory: df_timeline_interpretation_summary
Object not found in memory: high_load_level_distribution

Notebook 04 output objects collected successfully.
Available output datasets: 10

Notebook 04 final validation summary:

                                 Output File  Rows  Columns  Missing Values  Duplicate Rows  Ready to Save
0               04_daily_care_load_trend.csv   720       21               0               0           True
1              04_weekly_care_load_trend.csv   154       19               0               0           True
2             04_monthly_care_load_trend.csv    36       27               0               0           True
3   04_yearly_calendar_period_comparison.csv     3       27               0               0           True
4          04_timeline_executive_summary.csv     3       14               0               0           True
5              04_timeline_shift_summary.csv     3       13               0               0           True
6   04_final_timeline_comparison_summary.csv     3       18               0               0           True
7       04_daily_high_load_trend_dataset.csv   720       27               0               0           True
8  04_sustained_high_load_period_summary.csv     2       11               0               0           True
9          04_step_4g_validation_summary.csv    13        2               0               0           True

Notebook 04 outputs saved successfully.
Final validation summary saved to: C:\Users\Mohit\OneDrive\Documents\Data Analytics\Unified Mentor Projects\System Capacity & Care Load Analytics for Unaccompanied Children\data\processed\04_notebook_04_final_validation_summary.csv
Saved outputs summary saved to: C:\Users\Mohit\OneDrive\Documents\Data Analytics\Unified Mentor Projects\System Capacity & Care Load Analytics for Unaccompanied Children\data\processed\04_notebook_04_saved_outputs_summary.csv

Notebook 04 completion summary:

                  Notebook 04 Completion Check                  Result
0                Daily Trend Dataset Available                    True
1               Weekly Trend Dataset Available                    True
2              Monthly Trend Dataset Available                    True
3       Yearly / Calendar Comparison Available                    True
4                Timeline Comparison Available                    True
5  Sustained High-Load Period Output Available                    True
6                     Total Output Files Saved                      12
7                      Total Validation Issues                       0
8                     Rows Deleted or Modified                       0
9                           Notebook 04 Status  Completed Successfully

Saved outputs summary:

,Output Name,File Path,Rows Saved,Columns Saved,Expected Purpose
0,04_daily_care_load_trend.csv,C:\Users\Mohit\OneDrive\Documents\Data Analytics\Unified Mentor Projects\System Capacity & Care Load Analytics for U...,720,21,Notebook 04 trend and temporal analysis output
1,04_weekly_care_load_trend.csv,C:\Users\Mohit\OneDrive\Documents\Data Analytics\Unified Mentor Projects\System Capacity & Care Load Analytics for U...,154,19,Notebook 04 trend and temporal analysis output
2,04_monthly_care_load_trend.csv,C:\Users\Mohit\OneDrive\Documents\Data Analytics\Unified Mentor Projects\System Capacity & Care Load Analytics for U...,36,27,Notebook 04 trend and temporal analysis output
3,04_yearly_calendar_period_comparison.csv,C:\Users\Mohit\OneDrive\Documents\Data Analytics\Unified Mentor Projects\System Capacity & Care Load Analytics for U...,3,27,Notebook 04 trend and temporal analysis output
4,04_timeline_executive_summary.csv,C:\Users\Mohit\OneDrive\Documents\Data Analytics\Unified Mentor Projects\System Capacity & Care Load Analytics for U...,3,14,Notebook 04 trend and temporal analysis output
5,04_timeline_shift_summary.csv,C:\Users\Mohit\OneDrive\Documents\Data Analytics\Unified Mentor Projects\System Capacity & Care Load Analytics for U...,3,13,Notebook 04 trend and temporal analysis output
6,04_final_timeline_comparison_summary.csv,C:\Users\Mohit\OneDrive\Documents\Data Analytics\Unified Mentor Projects\System Capacity & Care Load Analytics for U...,3,18,Notebook 04 trend and temporal analysis output
7,04_daily_high_load_trend_dataset.csv,C:\Users\Mohit\OneDrive\Documents\Data Analytics\Unified Mentor Projects\System Capacity & Care Load Analytics for U...,720,27,Notebook 04 trend and temporal analysis output
8,04_sustained_high_load_period_summary.csv,C:\Users\Mohit\OneDrive\Documents\Data Analytics\Unified Mentor Projects\System Capacity & Care Load Analytics for U...,2,11,Notebook 04 trend and temporal analysis output
9,04_step_4g_validation_summary.csv,C:\Users\Mohit\OneDrive\Documents\Data Analytics\Unified Mentor Projects\System Capacity & Care Load Analytics for U...,13,2,Notebook 04 trend and temporal analysis output

Step 4H completed successfully.
Notebook 04 trend and temporal analysis outputs are saved and ready for the next notebook.