# Step 5A — Load Notebook 04 Outputs and Confirm Pressure Analysis Readiness

This step starts Notebook 05 by loading the finalized trend and temporal analysis outputs created in Notebook 04.

The purpose of this step is to confirm that all required Notebook 04 datasets are available, correctly structured, and ready for pressure and stress identification.

In this step, we will:

- Configure project paths
- Load Notebook 04 saved outputs
- Validate required files
- Confirm row and column counts
- Check date parsing and chronological ordering
- Confirm readiness for rolling averages, variability analysis, prolonged strain windows, and high-pressure date windows

This step does not create new pressure metrics yet. It only prepares and validates the input foundation for Notebook 05.

In [1]:
# ============================================================
# Notebook 05: Pressure and Stress Identification
# Step 5A — Load Notebook 04 Outputs and Confirm Pressure Analysis Readiness
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path
from IPython.display import display

print("Step 5A - Load Notebook 04 Outputs and Confirm Pressure Analysis Readiness")
print("=" * 90)

# ------------------------------------------------------------
# 1. Configure project paths
# ------------------------------------------------------------

project_root = Path.cwd()

# Move upward until project-level data folder is found
while not (project_root / "data").exists() and project_root != project_root.parent:
    project_root = project_root.parent

processed_data_dir = project_root / "data" / "processed"

print("Project paths configured successfully.")
print(f"Project root: {project_root}")
print(f"Processed data directory: {processed_data_dir}")

# ------------------------------------------------------------
# 2. Define required Notebook 04 output files
# ------------------------------------------------------------

notebook_04_files = {
    "daily_trend": "04_daily_care_load_trend.csv",
    "weekly_trend": "04_weekly_care_load_trend.csv",
    "monthly_trend": "04_monthly_care_load_trend.csv",
    "yearly_calendar_comparison": "04_yearly_calendar_period_comparison.csv",
    "timeline_executive_summary": "04_timeline_executive_summary.csv",
    "timeline_shift_summary": "04_timeline_shift_summary.csv",
    "final_timeline_comparison": "04_final_timeline_comparison_summary.csv",
    "daily_high_load_trend": "04_daily_high_load_trend_dataset.csv",
    "sustained_high_load_periods": "04_sustained_high_load_period_summary.csv",
    "step_4g_validation": "04_step_4g_validation_summary.csv",
}

notebook_04_paths = {
    key: processed_data_dir / file_name
    for key, file_name in notebook_04_files.items()
}

print("\nRequired Notebook 04 output files:")
for key, path in notebook_04_paths.items():
    print(f"- {key}: {path.name}")

# ------------------------------------------------------------
# 3. Validate file availability
# ------------------------------------------------------------

file_availability_records = []

for key, path in notebook_04_paths.items():
    file_availability_records.append({
        "Dataset Key": key,
        "Expected File": path.name,
        "File Exists": path.exists(),
        "File Path": str(path)
    })

file_availability_summary = pd.DataFrame(file_availability_records)

missing_files = file_availability_summary.loc[
    file_availability_summary["File Exists"] == False,
    "Expected File"
].tolist()

print("\nNotebook 04 file availability summary:")
display(file_availability_summary)

if missing_files:
    raise FileNotFoundError(
        "Missing required Notebook 04 output files:\n"
        + "\n".join(missing_files)
        + "\n\nPlease complete Notebook 04 Step 4H before running Notebook 05."
    )

print("All required Notebook 04 output files are available.")

# ------------------------------------------------------------
# 4. Load Notebook 04 output datasets
# ------------------------------------------------------------

df_daily_trend = pd.read_csv(notebook_04_paths["daily_trend"])
df_weekly_trend = pd.read_csv(notebook_04_paths["weekly_trend"])
df_monthly_trend = pd.read_csv(notebook_04_paths["monthly_trend"])
df_yearly_calendar_comparison = pd.read_csv(notebook_04_paths["yearly_calendar_comparison"])
df_timeline_executive_summary = pd.read_csv(notebook_04_paths["timeline_executive_summary"])
df_timeline_shift_summary = pd.read_csv(notebook_04_paths["timeline_shift_summary"])
df_final_timeline_comparison = pd.read_csv(notebook_04_paths["final_timeline_comparison"])
df_daily_high_load_trend = pd.read_csv(notebook_04_paths["daily_high_load_trend"])
df_sustained_high_load_periods = pd.read_csv(notebook_04_paths["sustained_high_load_periods"])
df_step_4g_validation = pd.read_csv(notebook_04_paths["step_4g_validation"])

print("\nNotebook 04 output datasets loaded successfully.")

# ------------------------------------------------------------
# 5. Confirm dataset shapes
# ------------------------------------------------------------

loaded_dataset_summary = pd.DataFrame([
    {
        "Dataset Name": "df_daily_trend",
        "Rows": df_daily_trend.shape[0],
        "Columns": df_daily_trend.shape[1],
        "Purpose": "Daily care load trend input for rolling averages and pressure analysis"
    },
    {
        "Dataset Name": "df_weekly_trend",
        "Rows": df_weekly_trend.shape[0],
        "Columns": df_weekly_trend.shape[1],
        "Purpose": "Weekly trend summary for medium-term pressure review"
    },
    {
        "Dataset Name": "df_monthly_trend",
        "Rows": df_monthly_trend.shape[0],
        "Columns": df_monthly_trend.shape[1],
        "Purpose": "Monthly trend summary for broader temporal comparison"
    },
    {
        "Dataset Name": "df_yearly_calendar_comparison",
        "Rows": df_yearly_calendar_comparison.shape[0],
        "Columns": df_yearly_calendar_comparison.shape[1],
        "Purpose": "Early, middle, and late timeline comparison"
    },
    {
        "Dataset Name": "df_timeline_executive_summary",
        "Rows": df_timeline_executive_summary.shape[0],
        "Columns": df_timeline_executive_summary.shape[1],
        "Purpose": "Executive timeline comparison summary"
    },
    {
        "Dataset Name": "df_timeline_shift_summary",
        "Rows": df_timeline_shift_summary.shape[0],
        "Columns": df_timeline_shift_summary.shape[1],
        "Purpose": "Timeline shift comparison against early timeline"
    },
    {
        "Dataset Name": "df_final_timeline_comparison",
        "Rows": df_final_timeline_comparison.shape[0],
        "Columns": df_final_timeline_comparison.shape[1],
        "Purpose": "Final combined timeline comparison output"
    },
    {
        "Dataset Name": "df_daily_high_load_trend",
        "Rows": df_daily_high_load_trend.shape[0],
        "Columns": df_daily_high_load_trend.shape[1],
        "Purpose": "Daily trend dataset with high-load flags from Notebook 04"
    },
    {
        "Dataset Name": "df_sustained_high_load_periods",
        "Rows": df_sustained_high_load_periods.shape[0],
        "Columns": df_sustained_high_load_periods.shape[1],
        "Purpose": "Sustained high-load periods identified in Notebook 04"
    },
    {
        "Dataset Name": "df_step_4g_validation",
        "Rows": df_step_4g_validation.shape[0],
        "Columns": df_step_4g_validation.shape[1],
        "Purpose": "Step 4G validation summary"
    },
])

print("\nLoaded Notebook 04 dataset shape summary:")
display(loaded_dataset_summary)

# ------------------------------------------------------------
# 6. Validate required pressure input columns
# ------------------------------------------------------------

required_pressure_input_columns = [
    "Date",
    "Children in CBP custody",
    "Children in HHS Care",
    "Children transferred out of CBP custody",
    "Children discharged from HHS Care",
    "total_system_load",
    "net_daily_intake",
    "care_load_growth_rate_pct",
    "backlog_indicator",
    "backlog_severity_score",
    "logical_constraint_anomaly_flag"
]

missing_daily_columns = [
    col for col in required_pressure_input_columns
    if col not in df_daily_trend.columns
]

missing_high_load_columns = [
    col for col in required_pressure_input_columns
    if col not in df_daily_high_load_trend.columns
]

pressure_input_column_summary = pd.DataFrame([
    {
        "Dataset": "df_daily_trend",
        "Required Columns": len(required_pressure_input_columns),
        "Missing Columns": len(missing_daily_columns),
        "Missing Column Names": ", ".join(missing_daily_columns) if missing_daily_columns else "None"
    },
    {
        "Dataset": "df_daily_high_load_trend",
        "Required Columns": len(required_pressure_input_columns),
        "Missing Columns": len(missing_high_load_columns),
        "Missing Column Names": ", ".join(missing_high_load_columns) if missing_high_load_columns else "None"
    }
])

print("\nPressure input column validation summary:")
display(pressure_input_column_summary)

if missing_daily_columns:
    raise KeyError(
        "df_daily_trend is missing required pressure input columns:\n"
        + "\n".join(missing_daily_columns)
    )

if missing_high_load_columns:
    raise KeyError(
        "df_daily_high_load_trend is missing required pressure input columns:\n"
        + "\n".join(missing_high_load_columns)
    )

print("Required pressure input columns are available.")

# ------------------------------------------------------------
# 7. Validate Date column parsing and chronological order
# ------------------------------------------------------------

date_validation_records = []

date_datasets = {
    "df_daily_trend": df_daily_trend,
    "df_daily_high_load_trend": df_daily_high_load_trend
}

for dataset_name, dataset in date_datasets.items():
    dataset["Date"] = pd.to_datetime(dataset["Date"], errors="coerce")
    
    date_validation_records.append({
        "Dataset": dataset_name,
        "Rows": dataset.shape[0],
        "Date Parse Errors": int(dataset["Date"].isna().sum()),
        "Start Date": dataset["Date"].min(),
        "End Date": dataset["Date"].max(),
        "Unique Reporting Dates": dataset["Date"].nunique(),
        "Chronological Order": bool(dataset["Date"].is_monotonic_increasing),
        "Duplicate Dates": int(dataset["Date"].duplicated().sum())
    })

date_validation_summary = pd.DataFrame(date_validation_records)

print("\nDate validation summary:")
display(date_validation_summary)

if date_validation_summary["Date Parse Errors"].sum() > 0:
    raise ValueError("Date parsing errors found. Please check Notebook 04 output files.")

if date_validation_summary["Duplicate Dates"].sum() > 0:
    raise ValueError("Duplicate dates found in daily pressure input datasets.")

# Sort safely to guarantee chronological order
df_daily_trend = df_daily_trend.sort_values("Date").reset_index(drop=True)
df_daily_high_load_trend = df_daily_high_load_trend.sort_values("Date").reset_index(drop=True)

print("Date fields validated and datasets sorted chronologically.")

# ------------------------------------------------------------
# 8. Confirm numeric fields for pressure analysis
# ------------------------------------------------------------

numeric_pressure_columns = [
    "Children in CBP custody",
    "Children in HHS Care",
    "Children transferred out of CBP custody",
    "Children discharged from HHS Care",
    "total_system_load",
    "net_daily_intake",
    "care_load_growth_rate_pct",
    "backlog_severity_score"
]

numeric_validation_records = []

for col in numeric_pressure_columns:
    numeric_validation_records.append({
        "Column": col,
        "Available": col in df_daily_trend.columns,
        "Data Type": str(df_daily_trend[col].dtype) if col in df_daily_trend.columns else "Missing",
        "Missing Values": int(df_daily_trend[col].isna().sum()) if col in df_daily_trend.columns else None,
        "Minimum": df_daily_trend[col].min() if col in df_daily_trend.columns else None,
        "Maximum": df_daily_trend[col].max() if col in df_daily_trend.columns else None
    })

numeric_pressure_validation_summary = pd.DataFrame(numeric_validation_records)

print("\nNumeric pressure field validation summary:")
display(numeric_pressure_validation_summary)

# ------------------------------------------------------------
# 9. Create Notebook 05 readiness summary
# ------------------------------------------------------------

notebook_05_readiness_summary = pd.DataFrame([
    {
        "Readiness Check": "Notebook 04 Required Files Available",
        "Result": len(missing_files) == 0
    },
    {
        "Readiness Check": "Daily Trend Dataset Loaded",
        "Result": df_daily_trend.shape[0] > 0
    },
    {
        "Readiness Check": "Daily High-Load Dataset Loaded",
        "Result": df_daily_high_load_trend.shape[0] > 0
    },
    {
        "Readiness Check": "Required Pressure Columns Available",
        "Result": len(missing_daily_columns) == 0 and len(missing_high_load_columns) == 0
    },
    {
        "Readiness Check": "Date Parse Errors",
        "Result": int(date_validation_summary["Date Parse Errors"].sum())
    },
    {
        "Readiness Check": "Duplicate Daily Dates",
        "Result": int(date_validation_summary["Duplicate Dates"].sum())
    },
    {
        "Readiness Check": "Daily Records Available",
        "Result": df_daily_trend.shape[0]
    },
    {
        "Readiness Check": "Start Date",
        "Result": df_daily_trend["Date"].min()
    },
    {
        "Readiness Check": "End Date",
        "Result": df_daily_trend["Date"].max()
    },
    {
        "Readiness Check": "Notebook 05 Status",
        "Result": "Ready for Pressure and Stress Identification"
    }
])

print("\nNotebook 05 pressure analysis readiness summary:")
display(notebook_05_readiness_summary)

# ------------------------------------------------------------
# 10. Preview core pressure input dataset
# ------------------------------------------------------------

pressure_preview_columns = [
    "Date",
    "Children in CBP custody",
    "Children in HHS Care",
    "total_system_load",
    "net_daily_intake",
    "care_load_growth_rate_pct",
    "backlog_indicator",
    "backlog_severity_score",
    "logical_constraint_anomaly_flag"
]

print("\nPressure input dataset preview:")
display(df_daily_trend[pressure_preview_columns].head(10))

print("\nPressure input dataset tail:")
display(df_daily_trend[pressure_preview_columns].tail(10))

print("\nStep 5A completed successfully.")
print("Notebook 05 inputs are ready for Step 5B.")

Step 5A - Load Notebook 04 Outputs and Confirm Pressure Analysis Readiness
==========================================================================================
Project paths configured successfully.
Project root: C:\Users\Mohit\OneDrive\Documents\Data Analytics\Unified Mentor Projects\System Capacity & Care Load Analytics for Unaccompanied Children
Processed data directory: C:\Users\Mohit\OneDrive\Documents\Data Analytics\Unified Mentor Projects\System Capacity & Care Load Analytics for Unaccompanied Children\data\processed

Required Notebook 04 output files:
- daily_trend: 04_daily_care_load_trend.csv
- weekly_trend: 04_weekly_care_load_trend.csv
- monthly_trend: 04_monthly_care_load_trend.csv
- yearly_calendar_comparison: 04_yearly_calendar_period_comparison.csv
- timeline_executive_summary: 04_timeline_executive_summary.csv
- timeline_shift_summary: 04_timeline_shift_summary.csv
- final_timeline_comparison: 04_final_timeline_comparison_summary.csv
- daily_high_load_trend: 04_daily_high_load_trend_dataset.csv
- sustained_high_load_periods: 04_sustained_high_load_period_summary.csv
- step_4g_validation: 04_step_4g_validation_summary.csv

Notebook 04 file availability summary:

,Dataset Key,Expected File,File Exists,File Path
0,daily_trend,04_daily_care_load_trend.csv,True,C:\Users\Mohit\OneDrive\Documents\Data Analyti...
1,weekly_trend,04_weekly_care_load_trend.csv,True,C:\Users\Mohit\OneDrive\Documents\Data Analyti...
2,monthly_trend,04_monthly_care_load_trend.csv,True,C:\Users\Mohit\OneDrive\Documents\Data Analyti...
3,yearly_calendar_comparison,04_yearly_calendar_period_comparison.csv,True,C:\Users\Mohit\OneDrive\Documents\Data Analyti...
4,timeline_executive_summary,04_timeline_executive_summary.csv,True,C:\Users\Mohit\OneDrive\Documents\Data Analyti...
5,timeline_shift_summary,04_timeline_shift_summary.csv,True,C:\Users\Mohit\OneDrive\Documents\Data Analyti...
6,final_timeline_comparison,04_final_timeline_comparison_summary.csv,True,C:\Users\Mohit\OneDrive\Documents\Data Analyti...
7,daily_high_load_trend,04_daily_high_load_trend_dataset.csv,True,C:\Users\Mohit\OneDrive\Documents\Data Analyti...
8,sustained_high_load_periods,04_sustained_high_load_period_summary.csv,True,C:\Users\Mohit\OneDrive\Documents\Data Analyti...
9,step_4g_validation,04_step_4g_validation_summary.csv,True,C:\Users\Mohit\OneDrive\Documents\Data Analyti...

All required Notebook 04 output files are available.

Notebook 04 output datasets loaded successfully.

Loaded Notebook 04 dataset shape summary:

,Dataset Name,Rows,Columns,Purpose
0,df_daily_trend,720,21,Daily care load trend input for rolling averag...
1,df_weekly_trend,154,19,Weekly trend summary for medium-term pressure ...
2,df_monthly_trend,36,27,Monthly trend summary for broader temporal com...
3,df_yearly_calendar_comparison,3,27,"Early, middle, and late timeline comparison"
4,df_timeline_executive_summary,3,14,Executive timeline comparison summary
5,df_timeline_shift_summary,3,13,Timeline shift comparison against early timeline
6,df_final_timeline_comparison,3,18,Final combined timeline comparison output
7,df_daily_high_load_trend,720,27,Daily trend dataset with high-load flags from ...
8,df_sustained_high_load_periods,2,11,Sustained high-load periods identified in Note...
9,df_step_4g_validation,13,2,Step 4G validation summary

Pressure input column validation summary:

,Dataset,Required Columns,Missing Columns,Missing Column Names
0,df_daily_trend,11,0,None
1,df_daily_high_load_trend,11,0,None

Required pressure input columns are available.

Date validation summary:

,Dataset,Rows,Date Parse Errors,Start Date,End Date,Unique Reporting Dates,Chronological Order,Duplicate Dates
0,df_daily_trend,720,0,2023-01-12,2025-12-21,720,True,0
1,df_daily_high_load_trend,720,0,2023-01-12,2025-12-21,720,True,0

Date fields validated and datasets sorted chronologically.

Numeric pressure field validation summary:

,Column,Available,Data Type,Missing Values,Minimum,Maximum
0,Children in CBP custody,True,int64,0,7.0,531.00
1,Children in HHS Care,True,int64,0,1972.0,11516.00
2,Children transferred out of CBP custody,True,int64,0,0.0,440.00
3,Children discharged from HHS Care,True,int64,0,0.0,505.00
4,total_system_load,True,int64,0,2002.0,11762.00
5,net_daily_intake,True,int64,0,-465.0,206.00
6,care_load_growth_rate_pct,True,float64,0,-11.6,8.34
7,backlog_severity_score,True,int64,0,0.0,3.00

Notebook 05 pressure analysis readiness summary:

,Readiness Check,Result
0,Notebook 04 Required Files Available,True
1,Daily Trend Dataset Loaded,True
2,Daily High-Load Dataset Loaded,True
3,Required Pressure Columns Available,True
4,Date Parse Errors,0
5,Duplicate Daily Dates,0
6,Daily Records Available,720
7,Start Date,2023-01-12 00:00:00
8,End Date,2025-12-21 00:00:00
9,Notebook 05 Status,Ready for Pressure and Stress Identification

Pressure input dataset preview:

,Date,Children in CBP custody,Children in HHS Care,total_system_load,net_daily_intake,care_load_growth_rate_pct,backlog_indicator,backlog_severity_score,logical_constraint_anomaly_flag
0,2023-01-12,53,6566,6619,-402,0.00,No Current Backlog Pressure,0,False
1,2023-01-22,49,7122,7171,-188,8.34,No Current Backlog Pressure,0,False
2,2023-01-23,50,7280,7330,-142,2.22,No Current Backlog Pressure,0,False
3,2023-01-24,42,7433,7475,-128,1.98,No Current Backlog Pressure,0,True
4,2023-01-25,22,7538,7560,-139,1.14,No Current Backlog Pressure,0,True
5,2023-01-29,45,7472,7517,-292,-0.57,No Current Backlog Pressure,0,False
6,2023-01-30,54,7743,7797,-167,3.72,No Current Backlog Pressure,0,False
7,2023-01-31,36,7803,7839,-122,0.54,No Current Backlog Pressure,0,False
8,2023-02-01,32,7903,7935,-204,1.22,No Current Backlog Pressure,0,False
9,2023-02-02,13,7879,7892,-275,-0.54,No Current Backlog Pressure,0,True

Pressure input dataset tail:

,Date,Children in CBP custody,Children in HHS Care,total_system_load,net_daily_intake,care_load_growth_rate_pct,backlog_indicator,backlog_severity_score,logical_constraint_anomaly_flag
710,2025-12-08,27,2440,2467,5,0.57,Short-Term Intake Pressure,1,False
711,2025-12-09,30,2443,2473,-1,0.24,No Current Backlog Pressure,0,False
712,2025-12-10,54,2439,2493,-4,0.81,No Current Backlog Pressure,0,False
713,2025-12-11,47,2437,2484,-1,-0.36,No Current Backlog Pressure,0,False
714,2025-12-14,35,2462,2497,-4,0.52,No Current Backlog Pressure,0,False
715,2025-12-15,42,2470,2512,2,0.60,Short-Term Intake Pressure,1,False
716,2025-12-16,54,2468,2522,6,0.40,Short-Term Intake Pressure,1,False
717,2025-12-17,31,2481,2512,1,-0.40,Sustained Backlog Pressure,2,False
718,2025-12-18,50,2472,2522,-10,0.40,No Current Backlog Pressure,0,False
719,2025-12-21,18,2484,2502,-3,-0.79,No Current Backlog Pressure,0,False

Step 5A completed successfully.
Notebook 05 inputs are ready for Step 5B.

### Step 5B — Create Rolling Average Pressure Metrics

This step creates rolling average pressure metrics from the daily care-load dataset.

The goal is to smooth daily fluctuations and identify short-term and medium-term pressure patterns using 7-day and 14-day rolling averages.

In this step, we will:

- Create a safe working copy of the daily pressure dataset
- Validate date order before rolling calculations
- Calculate 7-day and 14-day rolling averages for key pressure fields
- Compare current daily load against rolling baseline values
- Create rolling pressure gap indicators
- Preserve all original rows without deleting or modifying source records

These rolling metrics will support later pressure and stress identification steps, especially prolonged strain windows and high-pressure date analysis.

In [2]:
# ============================================================
# Step 5B - Create Rolling Average Pressure Metrics
# Notebook: 05_pressure_and_stress_identification.ipynb
# ============================================================

import pandas as pd
import numpy as np

print("Step 5B - Create Rolling Average Pressure Metrics")
print("=" * 80)

# ------------------------------------------------------------
# 1. Validate Step 5A input dataset
# ------------------------------------------------------------

if "df_daily_trend" not in globals():
    raise NameError(
        "df_daily_trend not found in memory. Please run Step 5A first."
    )

df_pressure_rolling = df_daily_trend.copy()

print("Pressure rolling working copy created successfully.")
print(f"Input dataset shape: {df_pressure_rolling.shape[0]} rows × {df_pressure_rolling.shape[1]} columns")

# ------------------------------------------------------------
# 2. Validate required columns
# ------------------------------------------------------------

required_5b_columns = [
    "Date",
    "total_system_load",
    "net_daily_intake",
    "care_load_growth_rate_pct",
    "backlog_severity_score",
    "logical_constraint_anomaly_flag"
]

missing_5b_columns = [
    col for col in required_5b_columns
    if col not in df_pressure_rolling.columns
]

print(f"Missing Step 5B input columns: {len(missing_5b_columns)}")

if missing_5b_columns:
    raise ValueError(
        f"Missing required Step 5B columns: {missing_5b_columns}"
    )

# ------------------------------------------------------------
# 3. Date validation and chronological sorting
# ------------------------------------------------------------

df_pressure_rolling["Date"] = pd.to_datetime(
    df_pressure_rolling["Date"],
    errors="coerce"
)

date_parse_errors = df_pressure_rolling["Date"].isna().sum()

if date_parse_errors > 0:
    raise ValueError(
        f"Date parse errors found: {date_parse_errors}. Please fix Date column before Step 5B."
    )

df_pressure_rolling = df_pressure_rolling.sort_values("Date").reset_index(drop=True)

is_chronological = df_pressure_rolling["Date"].is_monotonic_increasing
duplicate_dates = df_pressure_rolling["Date"].duplicated().sum()

print(f"Date parse errors: {date_parse_errors}")
print(f"Dataset chronological order: {is_chronological}")
print(f"Duplicate dates: {duplicate_dates}")

if not is_chronological:
    raise ValueError("Date column is not in chronological order after sorting.")

# ------------------------------------------------------------
# 4. Ensure numeric pressure fields
# ------------------------------------------------------------

numeric_pressure_columns = [
    "total_system_load",
    "net_daily_intake",
    "care_load_growth_rate_pct",
    "backlog_severity_score"
]

for col in numeric_pressure_columns:
    df_pressure_rolling[col] = pd.to_numeric(
        df_pressure_rolling[col],
        errors="coerce"
    )

numeric_missing_summary = pd.DataFrame({
    "Column": numeric_pressure_columns,
    "Missing Values": [df_pressure_rolling[col].isna().sum() for col in numeric_pressure_columns],
    "Minimum": [df_pressure_rolling[col].min() for col in numeric_pressure_columns],
    "Maximum": [df_pressure_rolling[col].max() for col in numeric_pressure_columns]
})

print("\nNumeric pressure field validation summary:")
display(numeric_missing_summary)

# ------------------------------------------------------------
# 5. Create 7-day rolling average metrics
# ------------------------------------------------------------

df_pressure_rolling["rolling_7d_avg_system_load"] = (
    df_pressure_rolling["total_system_load"]
    .rolling(window=7, min_periods=1)
    .mean()
)

df_pressure_rolling["rolling_7d_avg_net_intake"] = (
    df_pressure_rolling["net_daily_intake"]
    .rolling(window=7, min_periods=1)
    .mean()
)

df_pressure_rolling["rolling_7d_avg_growth_rate_pct"] = (
    df_pressure_rolling["care_load_growth_rate_pct"]
    .rolling(window=7, min_periods=1)
    .mean()
)

df_pressure_rolling["rolling_7d_avg_backlog_severity"] = (
    df_pressure_rolling["backlog_severity_score"]
    .rolling(window=7, min_periods=1)
    .mean()
)

# ------------------------------------------------------------
# 6. Create 14-day rolling average metrics
# ------------------------------------------------------------

df_pressure_rolling["rolling_14d_avg_system_load"] = (
    df_pressure_rolling["total_system_load"]
    .rolling(window=14, min_periods=1)
    .mean()
)

df_pressure_rolling["rolling_14d_avg_net_intake"] = (
    df_pressure_rolling["net_daily_intake"]
    .rolling(window=14, min_periods=1)
    .mean()
)

df_pressure_rolling["rolling_14d_avg_growth_rate_pct"] = (
    df_pressure_rolling["care_load_growth_rate_pct"]
    .rolling(window=14, min_periods=1)
    .mean()
)

df_pressure_rolling["rolling_14d_avg_backlog_severity"] = (
    df_pressure_rolling["backlog_severity_score"]
    .rolling(window=14, min_periods=1)
    .mean()
)

# ------------------------------------------------------------
# 7. Create pressure gap metrics
# ------------------------------------------------------------

df_pressure_rolling["system_load_vs_7d_avg_gap"] = (
    df_pressure_rolling["total_system_load"] -
    df_pressure_rolling["rolling_7d_avg_system_load"]
)

df_pressure_rolling["system_load_vs_14d_avg_gap"] = (
    df_pressure_rolling["total_system_load"] -
    df_pressure_rolling["rolling_14d_avg_system_load"]
)

df_pressure_rolling["net_intake_vs_7d_avg_gap"] = (
    df_pressure_rolling["net_daily_intake"] -
    df_pressure_rolling["rolling_7d_avg_net_intake"]
)

df_pressure_rolling["net_intake_vs_14d_avg_gap"] = (
    df_pressure_rolling["net_daily_intake"] -
    df_pressure_rolling["rolling_14d_avg_net_intake"]
)

# ------------------------------------------------------------
# 8. Create pressure direction indicators
# ------------------------------------------------------------

df_pressure_rolling["above_7d_system_load_avg_flag"] = (
    df_pressure_rolling["system_load_vs_7d_avg_gap"] > 0
)

df_pressure_rolling["above_14d_system_load_avg_flag"] = (
    df_pressure_rolling["system_load_vs_14d_avg_gap"] > 0
)

df_pressure_rolling["positive_7d_net_intake_pressure_flag"] = (
    df_pressure_rolling["rolling_7d_avg_net_intake"] > 0
)

df_pressure_rolling["positive_14d_net_intake_pressure_flag"] = (
    df_pressure_rolling["rolling_14d_avg_net_intake"] > 0
)

# ------------------------------------------------------------
# 9. Create rolling pressure level classification
# ------------------------------------------------------------

def classify_rolling_pressure(row):
    if (
        row["above_14d_system_load_avg_flag"] == True
        and row["positive_14d_net_intake_pressure_flag"] == True
        and row["rolling_14d_avg_backlog_severity"] >= 2
    ):
        return "Sustained Rolling Pressure"
    elif (
        row["above_7d_system_load_avg_flag"] == True
        and row["positive_7d_net_intake_pressure_flag"] == True
    ):
        return "Short-Term Rolling Pressure"
    elif row["above_7d_system_load_avg_flag"] == True:
        return "Load Above Rolling Average"
    else:
        return "Normal Rolling Pressure"

df_pressure_rolling["rolling_pressure_level"] = df_pressure_rolling.apply(
    classify_rolling_pressure,
    axis=1
)

# ------------------------------------------------------------
# 10. Round rolling metrics for readability
# ------------------------------------------------------------

rolling_numeric_columns = [
    "rolling_7d_avg_system_load",
    "rolling_7d_avg_net_intake",
    "rolling_7d_avg_growth_rate_pct",
    "rolling_7d_avg_backlog_severity",
    "rolling_14d_avg_system_load",
    "rolling_14d_avg_net_intake",
    "rolling_14d_avg_growth_rate_pct",
    "rolling_14d_avg_backlog_severity",
    "system_load_vs_7d_avg_gap",
    "system_load_vs_14d_avg_gap",
    "net_intake_vs_7d_avg_gap",
    "net_intake_vs_14d_avg_gap"
]

for col in rolling_numeric_columns:
    df_pressure_rolling[col] = df_pressure_rolling[col].round(2)

# ------------------------------------------------------------
# 11. Create rolling pressure distribution summary
# ------------------------------------------------------------

rolling_pressure_distribution = (
    df_pressure_rolling["rolling_pressure_level"]
    .value_counts()
    .reset_index()
)

rolling_pressure_distribution.columns = [
    "Rolling Pressure Level",
    "Record Count"
]

rolling_pressure_distribution["Record Percentage"] = (
    rolling_pressure_distribution["Record Count"] /
    len(df_pressure_rolling) * 100
).round(2)

# ------------------------------------------------------------
# 12. Create Step 5B validation summary
# ------------------------------------------------------------

new_5b_columns = [
    "rolling_7d_avg_system_load",
    "rolling_7d_avg_net_intake",
    "rolling_7d_avg_growth_rate_pct",
    "rolling_7d_avg_backlog_severity",
    "rolling_14d_avg_system_load",
    "rolling_14d_avg_net_intake",
    "rolling_14d_avg_growth_rate_pct",
    "rolling_14d_avg_backlog_severity",
    "system_load_vs_7d_avg_gap",
    "system_load_vs_14d_avg_gap",
    "net_intake_vs_7d_avg_gap",
    "net_intake_vs_14d_avg_gap",
    "above_7d_system_load_avg_flag",
    "above_14d_system_load_avg_flag",
    "positive_7d_net_intake_pressure_flag",
    "positive_14d_net_intake_pressure_flag",
    "rolling_pressure_level"
]

step_5b_validation_summary = pd.DataFrame({
    "Step 5B Check": [
        "Input Dataset Source",
        "Rows Checked",
        "Columns Before Step 5B",
        "Columns After Step 5B",
        "New Rolling Columns Created",
        "Missing Required Input Columns",
        "Date Parse Errors",
        "Duplicate Dates",
        "Chronological Order",
        "Missing Values in New Rolling Columns",
        "Rows Deleted or Modified"
    ],
    "Result": [
        "df_daily_trend",
        df_pressure_rolling.shape[0],
        df_daily_trend.shape[1],
        df_pressure_rolling.shape[1],
        len(new_5b_columns),
        len(missing_5b_columns),
        int(date_parse_errors),
        int(duplicate_dates),
        bool(is_chronological),
        int(df_pressure_rolling[new_5b_columns].isna().sum().sum()),
        0
    ]
})

# ------------------------------------------------------------
# 13. Preview outputs
# ------------------------------------------------------------

pressure_rolling_preview_columns = [
    "Date",
    "total_system_load",
    "net_daily_intake",
    "care_load_growth_rate_pct",
    "backlog_severity_score",
    "rolling_7d_avg_system_load",
    "rolling_14d_avg_system_load",
    "system_load_vs_7d_avg_gap",
    "system_load_vs_14d_avg_gap",
    "rolling_7d_avg_net_intake",
    "rolling_14d_avg_net_intake",
    "rolling_pressure_level"
]

print("\nRolling pressure metrics created successfully.")
print(f"Final Step 5B dataset shape: {df_pressure_rolling.shape[0]} rows × {df_pressure_rolling.shape[1]} columns")

print("\nRolling pressure level distribution:")
display(rolling_pressure_distribution)

print("\nStep 5B validation summary:")
display(step_5b_validation_summary)

print("\nRolling pressure dataset preview:")
display(df_pressure_rolling[pressure_rolling_preview_columns].head(10))

print("\nRolling pressure dataset tail:")
display(df_pressure_rolling[pressure_rolling_preview_columns].tail(10))

print("\nStep 5B completed successfully.")
print("Rolling average pressure metrics are ready for Step 5C.")

Step 5B - Create Rolling Average Pressure Metrics
================================================================================
Pressure rolling working copy created successfully.
Input dataset shape: 720 rows × 21 columns
Missing Step 5B input columns: 0
Date parse errors: 0
Dataset chronological order: True
Duplicate dates: 0

Numeric pressure field validation summary:

                      Column  Missing Values  Minimum   Maximum
0          total_system_load               0   2002.0  11762.00
1           net_daily_intake               0   -465.0    206.00
2  care_load_growth_rate_pct               0    -11.6      8.34
3     backlog_severity_score               0      0.0      3.00

Rolling pressure metrics created successfully.
Final Step 5B dataset shape: 720 rows × 38 columns

Rolling pressure level distribution:

        Rolling Pressure Level  Record Count  Record Percentage
0      Normal Rolling Pressure           327              45.42
1   Load Above Rolling Average           203              28.19
2  Short-Term Rolling Pressure           177              24.58
3   Sustained Rolling Pressure            13               1.81

Step 5B validation summary:

                            Step 5B Check          Result
0                    Input Dataset Source  df_daily_trend
1                            Rows Checked             720
2                  Columns Before Step 5B              21
3                   Columns After Step 5B              38
4             New Rolling Columns Created              17
5          Missing Required Input Columns               0
6                       Date Parse Errors               0
7                         Duplicate Dates               0
8                     Chronological Order            True
9   Missing Values in New Rolling Columns               0
10               Rows Deleted or Modified               0

Rolling pressure dataset preview:

,Date,total_system_load,net_daily_intake,care_load_growth_rate_pct,backlog_severity_score,rolling_7d_avg_system_load,rolling_14d_avg_system_load,system_load_vs_7d_avg_gap,system_load_vs_14d_avg_gap,rolling_7d_avg_net_intake,rolling_14d_avg_net_intake,rolling_pressure_level
0,2023-01-12,6619,-402,0.00,0,6619.00,6619.00,0.00,0.00,-402.00,-402.00,Normal Rolling Pressure
1,2023-01-22,7171,-188,8.34,0,6895.00,6895.00,276.00,276.00,-295.00,-295.00,Load Above Rolling Average
2,2023-01-23,7330,-142,2.22,0,7040.00,7040.00,290.00,290.00,-244.00,-244.00,Load Above Rolling Average
3,2023-01-24,7475,-128,1.98,0,7148.75,7148.75,326.25,326.25,-215.00,-215.00,Load Above Rolling Average
4,2023-01-25,7560,-139,1.14,0,7231.00,7231.00,329.00,329.00,-199.80,-199.80,Load Above Rolling Average
5,2023-01-29,7517,-292,-0.57,0,7278.67,7278.67,238.33,238.33,-215.17,-215.17,Load Above Rolling Average
6,2023-01-30,7797,-167,3.72,0,7352.71,7352.71,444.29,444.29,-208.29,-208.29,Load Above Rolling Average
7,2023-01-31,7839,-122,0.54,0,7527.00,7413.50,312.00,425.50,-168.29,-197.50,Load Above Rolling Average
8,2023-02-01,7935,-204,1.22,0,7636.14,7471.44,298.86,463.56,-170.57,-198.22,Load Above Rolling Average
9,2023-02-02,7892,-275,-0.54,0,7716.43,7513.50,175.57,378.50,-189.57,-205.90,Load Above Rolling Average

Rolling pressure dataset tail:

,Date,total_system_load,net_daily_intake,care_load_growth_rate_pct,backlog_severity_score,rolling_7d_avg_system_load,rolling_14d_avg_system_load,system_load_vs_7d_avg_gap,system_load_vs_14d_avg_gap,rolling_7d_avg_net_intake,rolling_14d_avg_net_intake,rolling_pressure_level
710,2025-12-08,2467,5,0.57,1,2448.29,2425.50,18.71,41.50,0.57,0.93,Short-Term Rolling Pressure
711,2025-12-09,2473,-1,0.24,0,2454.00,2431.93,19.00,41.07,-1.00,1.14,Load Above Rolling Average
712,2025-12-10,2493,-4,0.81,0,2462.14,2440.57,30.86,52.43,-0.86,1.36,Load Above Rolling Average
713,2025-12-11,2484,-1,-0.36,0,2468.29,2446.79,15.71,37.21,-0.71,1.36,Load Above Rolling Average
714,2025-12-14,2497,-4,0.52,0,2474.86,2452.21,22.14,44.79,-1.43,-0.43,Load Above Rolling Average
715,2025-12-15,2512,2,0.60,1,2482.71,2459.43,29.29,52.57,-0.29,0.00,Load Above Rolling Average
716,2025-12-16,2522,6,0.40,1,2492.57,2466.57,29.43,55.43,0.43,0.21,Short-Term Rolling Pressure
717,2025-12-17,2512,1,-0.40,2,2499.00,2473.64,13.00,38.36,-0.14,0.21,Load Above Rolling Average
718,2025-12-18,2522,-10,0.40,0,2506.00,2480.00,16.00,42.00,-1.43,-1.21,Load Above Rolling Average
719,2025-12-21,2502,-3,-0.79,0,2507.29,2484.71,-5.29,17.29,-1.29,-1.07,Normal Rolling Pressure

Step 5B completed successfully.
Rolling average pressure metrics are ready for Step 5C.

## Step 5C — Create Variability / Volatility Pressure Metrics

This step creates variability and volatility-based pressure metrics to identify unstable care load patterns across the system.

In this step, we calculate rolling variability indicators for key pressure fields such as total system load, net daily intake, and care load growth rate. These metrics help detect short-term fluctuations, unstable operating windows, and early signs of system pressure that may not be visible through simple averages alone.

The output from this step will support later pressure and stress identification by adding volatility-focused features to the rolling pressure dataset.

In [3]:
# ============================================================
# Step 5C - Create Variability / Volatility Pressure Metrics
# ============================================================

import pandas as pd
import numpy as np

print("Step 5C - Create Variability / Volatility Pressure Metrics")
print("=" * 75)

# ------------------------------------------------------------
# 1. Select safest available input dataset
# ------------------------------------------------------------

if "df_pressure_rolling" in globals():
    df_pressure_volatility = df_pressure_rolling.copy()
    input_dataset_source = "df_pressure_rolling"
elif "df_daily_trend_high_load" in globals():
    df_pressure_volatility = df_daily_trend_high_load.copy()
    input_dataset_source = "df_daily_trend_high_load"
elif "df_daily_trend" in globals():
    df_pressure_volatility = df_daily_trend.copy()
    input_dataset_source = "df_daily_trend"
else:
    raise NameError(
        "No valid Step 5C input dataset found. Expected one of: "
        "'df_pressure_rolling', 'df_daily_trend_high_load', or 'df_daily_trend'. "
        "Please run Step 5A and Step 5B first."
    )

print(f"Pressure volatility working copy created successfully.")
print(f"Input dataset source: {input_dataset_source}")
print(f"Input dataset shape: {df_pressure_volatility.shape[0]} rows × {df_pressure_volatility.shape[1]} columns")

# ------------------------------------------------------------
# 2. Validate required columns
# ------------------------------------------------------------

required_5c_columns = [
    "Date",
    "total_system_load",
    "net_daily_intake",
    "care_load_growth_rate_pct",
    "backlog_severity_score"
]

missing_5c_columns = [
    col for col in required_5c_columns
    if col not in df_pressure_volatility.columns
]

print(f"Missing Step 5C input columns: {len(missing_5c_columns)}")

if missing_5c_columns:
    raise ValueError(f"Missing required Step 5C columns: {missing_5c_columns}")

# ------------------------------------------------------------
# 3. Validate and sort Date column
# ------------------------------------------------------------

df_pressure_volatility["Date"] = pd.to_datetime(
    df_pressure_volatility["Date"],
    errors="coerce"
)

date_parse_errors_5c = int(df_pressure_volatility["Date"].isna().sum())

if date_parse_errors_5c > 0:
    raise ValueError(
        f"Date parse errors found in Step 5C: {date_parse_errors_5c}. "
        "Please fix Date values before continuing."
    )

df_pressure_volatility = (
    df_pressure_volatility
    .sort_values("Date")
    .reset_index(drop=True)
)

duplicate_dates_5c = int(df_pressure_volatility["Date"].duplicated().sum())
is_chronological_5c = bool(df_pressure_volatility["Date"].is_monotonic_increasing)

print(f"Date parse errors: {date_parse_errors_5c}")
print(f"Dataset chronological order: {is_chronological_5c}")
print(f"Duplicate dates: {duplicate_dates_5c}")

# ------------------------------------------------------------
# 4. Validate numeric fields
# ------------------------------------------------------------

numeric_pressure_fields_5c = [
    "total_system_load",
    "net_daily_intake",
    "care_load_growth_rate_pct",
    "backlog_severity_score"
]

for col in numeric_pressure_fields_5c:
    df_pressure_volatility[col] = pd.to_numeric(
        df_pressure_volatility[col],
        errors="coerce"
    )

numeric_validation_5c = pd.DataFrame({
    "Column": numeric_pressure_fields_5c,
    "Missing Values": [int(df_pressure_volatility[col].isna().sum()) for col in numeric_pressure_fields_5c],
    "Minimum": [df_pressure_volatility[col].min() for col in numeric_pressure_fields_5c],
    "Maximum": [df_pressure_volatility[col].max() for col in numeric_pressure_fields_5c]
})

print("\nNumeric volatility field validation summary:")
display(numeric_validation_5c)

# ------------------------------------------------------------
# 5. Create rolling volatility metrics
# ------------------------------------------------------------

# 7-day volatility metrics
df_pressure_volatility["rolling_7d_std_system_load"] = (
    df_pressure_volatility["total_system_load"]
    .rolling(window=7, min_periods=1)
    .std()
    .fillna(0)
)

df_pressure_volatility["rolling_7d_std_net_intake"] = (
    df_pressure_volatility["net_daily_intake"]
    .rolling(window=7, min_periods=1)
    .std()
    .fillna(0)
)

df_pressure_volatility["rolling_7d_std_growth_rate"] = (
    df_pressure_volatility["care_load_growth_rate_pct"]
    .rolling(window=7, min_periods=1)
    .std()
    .fillna(0)
)

# 14-day volatility metrics
df_pressure_volatility["rolling_14d_std_system_load"] = (
    df_pressure_volatility["total_system_load"]
    .rolling(window=14, min_periods=1)
    .std()
    .fillna(0)
)

df_pressure_volatility["rolling_14d_std_net_intake"] = (
    df_pressure_volatility["net_daily_intake"]
    .rolling(window=14, min_periods=1)
    .std()
    .fillna(0)
)

df_pressure_volatility["rolling_14d_std_growth_rate"] = (
    df_pressure_volatility["care_load_growth_rate_pct"]
    .rolling(window=14, min_periods=1)
    .std()
    .fillna(0)
)

# ------------------------------------------------------------
# 6. Create rolling range / swing metrics
# ------------------------------------------------------------

df_pressure_volatility["rolling_7d_system_load_range"] = (
    df_pressure_volatility["total_system_load"]
    .rolling(window=7, min_periods=1)
    .max()
    -
    df_pressure_volatility["total_system_load"]
    .rolling(window=7, min_periods=1)
    .min()
)

df_pressure_volatility["rolling_14d_system_load_range"] = (
    df_pressure_volatility["total_system_load"]
    .rolling(window=14, min_periods=1)
    .max()
    -
    df_pressure_volatility["total_system_load"]
    .rolling(window=14, min_periods=1)
    .min()
)

df_pressure_volatility["rolling_7d_net_intake_range"] = (
    df_pressure_volatility["net_daily_intake"]
    .rolling(window=7, min_periods=1)
    .max()
    -
    df_pressure_volatility["net_daily_intake"]
    .rolling(window=7, min_periods=1)
    .min()
)

df_pressure_volatility["rolling_14d_net_intake_range"] = (
    df_pressure_volatility["net_daily_intake"]
    .rolling(window=14, min_periods=1)
    .max()
    -
    df_pressure_volatility["net_daily_intake"]
    .rolling(window=14, min_periods=1)
    .min()
)

# ------------------------------------------------------------
# 7. Create volatility intensity score
# ------------------------------------------------------------

load_volatility_threshold_75 = df_pressure_volatility["rolling_14d_std_system_load"].quantile(0.75)
load_volatility_threshold_90 = df_pressure_volatility["rolling_14d_std_system_load"].quantile(0.90)

intake_volatility_threshold_75 = df_pressure_volatility["rolling_14d_std_net_intake"].quantile(0.75)
intake_volatility_threshold_90 = df_pressure_volatility["rolling_14d_std_net_intake"].quantile(0.90)

growth_volatility_threshold_75 = df_pressure_volatility["rolling_14d_std_growth_rate"].quantile(0.75)
growth_volatility_threshold_90 = df_pressure_volatility["rolling_14d_std_growth_rate"].quantile(0.90)

df_pressure_volatility["system_load_volatility_flag"] = np.select(
    [
        df_pressure_volatility["rolling_14d_std_system_load"] >= load_volatility_threshold_90,
        df_pressure_volatility["rolling_14d_std_system_load"] >= load_volatility_threshold_75
    ],
    [
        "High Load Volatility",
        "Moderate Load Volatility"
    ],
    default="Stable Load Volatility"
)

df_pressure_volatility["net_intake_volatility_flag"] = np.select(
    [
        df_pressure_volatility["rolling_14d_std_net_intake"] >= intake_volatility_threshold_90,
        df_pressure_volatility["rolling_14d_std_net_intake"] >= intake_volatility_threshold_75
    ],
    [
        "High Intake Volatility",
        "Moderate Intake Volatility"
    ],
    default="Stable Intake Volatility"
)

df_pressure_volatility["growth_rate_volatility_flag"] = np.select(
    [
        df_pressure_volatility["rolling_14d_std_growth_rate"] >= growth_volatility_threshold_90,
        df_pressure_volatility["rolling_14d_std_growth_rate"] >= growth_volatility_threshold_75
    ],
    [
        "High Growth Volatility",
        "Moderate Growth Volatility"
    ],
    default="Stable Growth Volatility"
)

# Composite numeric volatility score
df_pressure_volatility["volatility_pressure_score"] = (
    np.where(df_pressure_volatility["rolling_14d_std_system_load"] >= load_volatility_threshold_90, 2,
    np.where(df_pressure_volatility["rolling_14d_std_system_load"] >= load_volatility_threshold_75, 1, 0))
    +
    np.where(df_pressure_volatility["rolling_14d_std_net_intake"] >= intake_volatility_threshold_90, 2,
    np.where(df_pressure_volatility["rolling_14d_std_net_intake"] >= intake_volatility_threshold_75, 1, 0))
    +
    np.where(df_pressure_volatility["rolling_14d_std_growth_rate"] >= growth_volatility_threshold_90, 2,
    np.where(df_pressure_volatility["rolling_14d_std_growth_rate"] >= growth_volatility_threshold_75, 1, 0))
    +
    np.where(df_pressure_volatility["backlog_severity_score"] >= 2, 1, 0)
)

df_pressure_volatility["volatility_pressure_level"] = np.select(
    [
        df_pressure_volatility["volatility_pressure_score"] >= 5,
        df_pressure_volatility["volatility_pressure_score"] >= 3,
        df_pressure_volatility["volatility_pressure_score"] >= 1
    ],
    [
        "High Volatility Pressure",
        "Moderate Volatility Pressure",
        "Low Volatility Pressure"
    ],
    default="Stable Pressure"
)

print("\nVolatility pressure metrics created successfully.")

# ------------------------------------------------------------
# 8. Create volatility distribution summary
# ------------------------------------------------------------

volatility_pressure_distribution = (
    df_pressure_volatility["volatility_pressure_level"]
    .value_counts()
    .reset_index()
)

volatility_pressure_distribution.columns = [
    "Volatility Pressure Level",
    "Record Count"
]

volatility_pressure_distribution["Record Percentage"] = (
    volatility_pressure_distribution["Record Count"]
    / len(df_pressure_volatility)
    * 100
).round(2)

volatility_order = {
    "Stable Pressure": 1,
    "Low Volatility Pressure": 2,
    "Moderate Volatility Pressure": 3,
    "High Volatility Pressure": 4
}

volatility_pressure_distribution["Sort Order"] = (
    volatility_pressure_distribution["Volatility Pressure Level"]
    .map(volatility_order)
)

volatility_pressure_distribution = (
    volatility_pressure_distribution
    .sort_values("Sort Order")
    .drop(columns="Sort Order")
    .reset_index(drop=True)
)

print("\nVolatility pressure level distribution:")
display(volatility_pressure_distribution)

# ------------------------------------------------------------
# 9. Create Step 5C validation summary
# ------------------------------------------------------------

new_5c_columns = [
    "rolling_7d_std_system_load",
    "rolling_7d_std_net_intake",
    "rolling_7d_std_growth_rate",
    "rolling_14d_std_system_load",
    "rolling_14d_std_net_intake",
    "rolling_14d_std_growth_rate",
    "rolling_7d_system_load_range",
    "rolling_14d_system_load_range",
    "rolling_7d_net_intake_range",
    "rolling_14d_net_intake_range",
    "system_load_volatility_flag",
    "net_intake_volatility_flag",
    "growth_rate_volatility_flag",
    "volatility_pressure_score",
    "volatility_pressure_level"
]

missing_new_5c_columns = [
    col for col in new_5c_columns
    if col not in df_pressure_volatility.columns
]

missing_values_new_5c = int(
    df_pressure_volatility[new_5c_columns].isna().sum().sum()
) if not missing_new_5c_columns else None

step_5c_validation_summary = pd.DataFrame({
    "Step 5C Check": [
        "Input Dataset Source",
        "Rows Checked",
        "Columns Before Step 5C",
        "Columns After Step 5C",
        "New Volatility Columns Created",
        "Missing Required Input Columns",
        "Missing New Volatility Columns",
        "Missing Values in New Volatility Columns",
        "Date Parse Errors",
        "Duplicate Dates",
        "Chronological Order",
        "Rows Deleted or Modified"
    ],
    "Result": [
        input_dataset_source,
        df_pressure_volatility.shape[0],
        df_pressure_rolling.shape[1] if "df_pressure_rolling" in globals() else "Not Available",
        df_pressure_volatility.shape[1],
        len(new_5c_columns),
        len(missing_5c_columns),
        len(missing_new_5c_columns),
        missing_values_new_5c,
        date_parse_errors_5c,
        duplicate_dates_5c,
        is_chronological_5c,
        0
    ]
})

print("\nStep 5C validation summary:")
display(step_5c_validation_summary)

# ------------------------------------------------------------
# 10. Preview final volatility pressure dataset
# ------------------------------------------------------------

pressure_volatility_preview_columns = [
    "Date",
    "total_system_load",
    "net_daily_intake",
    "care_load_growth_rate_pct",
    "backlog_severity_score",
    "rolling_7d_std_system_load",
    "rolling_14d_std_system_load",
    "rolling_7d_std_net_intake",
    "rolling_14d_std_net_intake",
    "rolling_7d_system_load_range",
    "rolling_14d_system_load_range",
    "system_load_volatility_flag",
    "net_intake_volatility_flag",
    "growth_rate_volatility_flag",
    "volatility_pressure_score",
    "volatility_pressure_level"
]

pressure_volatility_preview_columns = [
    col for col in pressure_volatility_preview_columns
    if col in df_pressure_volatility.columns
]

print("\nVolatility pressure dataset preview:")
display(df_pressure_volatility[pressure_volatility_preview_columns].head(10))

print("\nVolatility pressure dataset tail:")
display(df_pressure_volatility[pressure_volatility_preview_columns].tail(10))

print("\nStep 5C completed successfully.")
print("Variability / volatility pressure metrics are ready for Step 5D.")

Step 5C - Create Variability / Volatility Pressure Metrics
===========================================================================
Pressure volatility working copy created successfully.
Input dataset source: df_pressure_rolling
Input dataset shape: 720 rows × 38 columns
Missing Step 5C input columns: 0
Date parse errors: 0
Dataset chronological order: True
Duplicate dates: 0

Numeric volatility field validation summary:

                      Column  Missing Values  Minimum   Maximum
0          total_system_load               0   2002.0  11762.00
1           net_daily_intake               0   -465.0    206.00
2  care_load_growth_rate_pct               0    -11.6      8.34
3     backlog_severity_score               0      0.0      3.00

Volatility pressure metrics created successfully.

Volatility pressure level distribution:

      Volatility Pressure Level  Record Count  Record Percentage
0               Stable Pressure           335              46.53
1       Low Volatility Pressure           263              36.53
2  Moderate Volatility Pressure            85              11.81
3      High Volatility Pressure            37               5.14

Step 5C validation summary:

                               Step 5C Check               Result
0                       Input Dataset Source  df_pressure_rolling
1                               Rows Checked                  720
2                     Columns Before Step 5C                   38
3                      Columns After Step 5C                   53
4             New Volatility Columns Created                   15
5             Missing Required Input Columns                    0
6             Missing New Volatility Columns                    0
7   Missing Values in New Volatility Columns                    0
8                          Date Parse Errors                    0
9                            Duplicate Dates                    0
10                       Chronological Order                 True
11                  Rows Deleted or Modified                    0

Volatility pressure dataset preview:

,Date,total_system_load,net_daily_intake,care_load_growth_rate_pct,backlog_severity_score,rolling_7d_std_system_load,rolling_14d_std_system_load,rolling_7d_std_net_intake,rolling_14d_std_net_intake,rolling_7d_system_load_range,rolling_14d_system_load_range,system_load_volatility_flag,net_intake_volatility_flag,growth_rate_volatility_flag,volatility_pressure_score,volatility_pressure_level
0,2023-01-12,6619,-402,0.00,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,Stable Load Volatility,Stable Intake Volatility,Stable Growth Volatility,0,Stable Pressure
1,2023-01-22,7171,-188,8.34,0,390.322943,390.322943,151.320851,151.320851,552.0,552.0,Moderate Load Volatility,High Intake Volatility,High Growth Volatility,5,High Volatility Pressure
2,2023-01-23,7330,-142,2.22,0,373.163503,373.163503,138.751577,138.751577,711.0,711.0,Moderate Load Volatility,High Intake Volatility,High Growth Volatility,5,High Volatility Pressure
3,2023-01-24,7475,-128,1.98,0,374.353109,374.353109,127.273983,127.273983,856.0,856.0,Moderate Load Volatility,High Intake Volatility,High Growth Volatility,5,High Volatility Pressure
4,2023-01-25,7560,-139,1.14,0,372.733819,372.733819,115.343834,115.343834,941.0,941.0,Moderate Load Volatility,High Intake Volatility,High Growth Volatility,5,High Volatility Pressure
5,2023-01-29,7517,-292,-0.57,0,353.237975,353.237975,109.818790,109.818790,941.0,941.0,Moderate Load Volatility,High Intake Volatility,High Growth Volatility,5,High Volatility Pressure
6,2023-01-30,7797,-167,3.72,0,377.309208,377.309208,101.889997,101.889997,1178.0,1178.0,Moderate Load Volatility,High Intake Volatility,High Growth Volatility,5,High Volatility Pressure
7,2023-01-31,7839,-122,0.54,0,237.936266,389.337900,59.174077,99.142034,668.0,1220.0,Moderate Load Volatility,High Intake Volatility,High Growth Volatility,5,High Volatility Pressure
8,2023-02-01,7935,-204,1.22,0,222.120409,403.551766,60.359636,92.764187,605.0,1316.0,Moderate Load Volatility,High Intake Volatility,Moderate Growth Volatility,4,Moderate Volatility Pressure
9,2023-02-02,7892,-275,-0.54,0,192.632515,403.045696,70.025846,90.766428,460.0,1316.0,Moderate Load Volatility,High Intake Volatility,Moderate Growth Volatility,4,Moderate Volatility Pressure

Volatility pressure dataset tail:

,Date,total_system_load,net_daily_intake,care_load_growth_rate_pct,backlog_severity_score,rolling_7d_std_system_load,rolling_14d_std_system_load,rolling_7d_std_net_intake,rolling_14d_std_net_intake,rolling_7d_system_load_range,rolling_14d_system_load_range,system_load_volatility_flag,net_intake_volatility_flag,growth_rate_volatility_flag,volatility_pressure_score,volatility_pressure_level
710,2025-12-08,2467,5,0.57,1,12.202654,28.294468,5.623082,7.405448,34.0,95.0,Stable Load Volatility,Stable Intake Volatility,Stable Growth Volatility,0,Stable Pressure
711,2025-12-09,2473,-1,0.24,0,13.178265,28.119154,3.785939,7.294436,37.0,101.0,Stable Load Volatility,Stable Intake Volatility,Stable Growth Volatility,0,Stable Pressure
712,2025-12-10,2493,-4,0.81,0,17.199114,26.849192,3.625308,7.077670,52.0,96.0,Stable Load Volatility,Stable Intake Volatility,Stable Growth Volatility,0,Stable Pressure
713,2025-12-11,2484,-1,-0.36,0,16.028249,26.044868,3.592320,7.077670,42.0,82.0,Stable Load Volatility,Stable Intake Volatility,Stable Growth Volatility,0,Stable Pressure
714,2025-12-14,2497,-4,0.52,0,17.150593,28.096478,3.690399,4.380275,44.0,86.0,Stable Load Volatility,Stable Intake Volatility,Stable Growth Volatility,0,Stable Pressure
715,2025-12-15,2512,2,0.60,1,19.972600,29.625130,3.251373,4.296689,59.0,99.0,Stable Load Volatility,Stable Intake Volatility,Stable Growth Volatility,0,Stable Pressure
716,2025-12-16,2522,6,0.40,1,19.890175,31.876479,4.035556,4.526479,55.0,109.0,Stable Load Volatility,Stable Intake Volatility,Stable Growth Volatility,0,Stable Pressure
717,2025-12-17,2512,1,-0.40,2,17.358955,30.004121,3.532165,4.526479,49.0,89.0,Stable Load Volatility,Stable Intake Volatility,Stable Growth Volatility,1,Low Volatility Pressure
718,2025-12-18,2522,-10,0.40,0,14.821156,30.158555,5.159365,4.353223,38.0,86.0,Stable Load Volatility,Stable Intake Volatility,Stable Growth Volatility,0,Stable Pressure
719,2025-12-21,2502,-3,-0.79,0,13.864995,27.819275,5.089672,4.251050,38.0,81.0,Stable Load Volatility,Stable Intake Volatility,Stable Growth Volatility,0,Stable Pressure

Step 5C completed successfully.
Variability / volatility pressure metrics are ready for Step 5D.

## Step 5D — Create Pressure Spike / Sudden Change Indicators

This step identifies sudden pressure spikes and sharp day-over-day changes in the care load system.

The purpose of this step is to detect short-term stress signals that may not be fully visible through rolling averages or volatility metrics alone.

In this step, we will:

- Create daily change metrics for system load, net intake, HHS care load, and CBP custody load
- Calculate percentage change indicators
- Flag sudden system load spikes
- Flag sudden intake pressure changes
- Classify spike intensity levels
- Create a combined pressure spike score
- Validate that no rows are deleted or modified
- Prepare the spike indicator dataset for the next step

In [4]:
# ------------------------------------------------------------
# Step 5D — Create Pressure Spike / Sudden Change Indicators
# ------------------------------------------------------------

import pandas as pd
import numpy as np

print("Step 5D - Create Pressure Spike / Sudden Change Indicators")
print("=" * 80)

# ------------------------------------------------------------
# 1. Select safest available input dataset
# ------------------------------------------------------------

if "df_pressure_volatility" in globals():
    df_pressure_spike = df_pressure_volatility.copy()
    input_dataset_source = "df_pressure_volatility"
elif "df_pressure_rolling" in globals():
    df_pressure_spike = df_pressure_rolling.copy()
    input_dataset_source = "df_pressure_rolling"
elif "df_daily_trend" in globals():
    df_pressure_spike = df_daily_trend.copy()
    input_dataset_source = "df_daily_trend"
else:
    raise NameError(
        "No valid pressure dataset found. Expected one of: "
        "'df_pressure_volatility', 'df_pressure_rolling', or 'df_daily_trend'. "
        "Please run previous steps first."
    )

rows_before_5d = df_pressure_spike.shape[0]
cols_before_5d = df_pressure_spike.shape[1]

print(f"Pressure spike working copy created successfully.")
print(f"Input dataset source: {input_dataset_source}")
print(f"Input dataset shape: {rows_before_5d} rows × {cols_before_5d} columns")

# ------------------------------------------------------------
# 2. Validate required input columns
# ------------------------------------------------------------

required_5d_columns = [
    "Date",
    "total_system_load",
    "net_daily_intake",
    "care_load_growth_rate_pct",
    "backlog_severity_score"
]

optional_5d_columns = [
    "Children in CBP custody",
    "Children in HHS Care",
    "Children transferred out of CBP custody",
    "Children discharged from HHS Care"
]

missing_5d_columns = [
    col for col in required_5d_columns
    if col not in df_pressure_spike.columns
]

print(f"Missing Step 5D required input columns: {len(missing_5d_columns)}")

if len(missing_5d_columns) > 0:
    print("Missing columns:")
    for col in missing_5d_columns:
        print(f"- {col}")
    raise KeyError("Step 5D cannot continue because required input columns are missing.")

# ------------------------------------------------------------
# 3. Date validation and chronological sorting
# ------------------------------------------------------------

df_pressure_spike["Date"] = pd.to_datetime(df_pressure_spike["Date"], errors="coerce")

date_parse_errors_5d = int(df_pressure_spike["Date"].isna().sum())

if date_parse_errors_5d > 0:
    raise ValueError(
        f"Step 5D found {date_parse_errors_5d} invalid Date values. "
        "Please fix Date column before continuing."
    )

df_pressure_spike = df_pressure_spike.sort_values("Date").reset_index(drop=True)

chronological_order_5d = df_pressure_spike["Date"].is_monotonic_increasing
duplicate_dates_5d = int(df_pressure_spike["Date"].duplicated().sum())

print(f"Date parse errors: {date_parse_errors_5d}")
print(f"Dataset chronological order: {chronological_order_5d}")
print(f"Duplicate dates: {duplicate_dates_5d}")

# ------------------------------------------------------------
# 4. Create absolute day-over-day change metrics
# ------------------------------------------------------------

df_pressure_spike["daily_system_load_change"] = (
    df_pressure_spike["total_system_load"].diff().fillna(0)
)

df_pressure_spike["daily_net_intake_change"] = (
    df_pressure_spike["net_daily_intake"].diff().fillna(0)
)

df_pressure_spike["daily_growth_rate_change"] = (
    df_pressure_spike["care_load_growth_rate_pct"].diff().fillna(0)
)

df_pressure_spike["daily_backlog_severity_change"] = (
    df_pressure_spike["backlog_severity_score"].diff().fillna(0)
)

# Optional operational change metrics
if "Children in CBP custody" in df_pressure_spike.columns:
    df_pressure_spike["daily_cbp_custody_change"] = (
        df_pressure_spike["Children in CBP custody"].diff().fillna(0)
    )
else:
    df_pressure_spike["daily_cbp_custody_change"] = 0

if "Children in HHS Care" in df_pressure_spike.columns:
    df_pressure_spike["daily_hhs_care_change"] = (
        df_pressure_spike["Children in HHS Care"].diff().fillna(0)
    )
else:
    df_pressure_spike["daily_hhs_care_change"] = 0

# ------------------------------------------------------------
# 5. Create percentage change indicators
# ------------------------------------------------------------

df_pressure_spike["system_load_pct_change"] = (
    df_pressure_spike["total_system_load"]
    .pct_change()
    .replace([np.inf, -np.inf], 0)
    .fillna(0) * 100
)

df_pressure_spike["net_intake_pct_change"] = (
    df_pressure_spike["net_daily_intake"]
    .replace(0, np.nan)
    .pct_change()
    .replace([np.inf, -np.inf], 0)
    .fillna(0) * 100
)

df_pressure_spike["cbp_custody_pct_change"] = (
    df_pressure_spike["Children in CBP custody"]
    .pct_change()
    .replace([np.inf, -np.inf], 0)
    .fillna(0) * 100
    if "Children in CBP custody" in df_pressure_spike.columns
    else 0
)

df_pressure_spike["hhs_care_pct_change"] = (
    df_pressure_spike["Children in HHS Care"]
    .pct_change()
    .replace([np.inf, -np.inf], 0)
    .fillna(0) * 100
    if "Children in HHS Care" in df_pressure_spike.columns
    else 0
)

# ------------------------------------------------------------
# 6. Create spike thresholds using distribution-based logic
# ------------------------------------------------------------

system_load_change_abs = df_pressure_spike["daily_system_load_change"].abs()
net_intake_change_abs = df_pressure_spike["daily_net_intake_change"].abs()
growth_rate_change_abs = df_pressure_spike["daily_growth_rate_change"].abs()

system_load_spike_threshold = system_load_change_abs.quantile(0.90)
major_system_load_spike_threshold = system_load_change_abs.quantile(0.95)

net_intake_spike_threshold = net_intake_change_abs.quantile(0.90)
major_net_intake_spike_threshold = net_intake_change_abs.quantile(0.95)

growth_rate_spike_threshold = growth_rate_change_abs.quantile(0.90)
major_growth_rate_spike_threshold = growth_rate_change_abs.quantile(0.95)

print("\nSpike threshold values:")
print(f"90th percentile system load change: {system_load_spike_threshold:.2f}")
print(f"95th percentile system load change: {major_system_load_spike_threshold:.2f}")
print(f"90th percentile net intake change: {net_intake_spike_threshold:.2f}")
print(f"95th percentile net intake change: {major_net_intake_spike_threshold:.2f}")
print(f"90th percentile growth rate change: {growth_rate_spike_threshold:.2f}")
print(f"95th percentile growth rate change: {major_growth_rate_spike_threshold:.2f}")

# ------------------------------------------------------------
# 7. Create spike flags
# ------------------------------------------------------------

df_pressure_spike["system_load_spike_flag"] = (
    system_load_change_abs >= system_load_spike_threshold
)

df_pressure_spike["major_system_load_spike_flag"] = (
    system_load_change_abs >= major_system_load_spike_threshold
)

df_pressure_spike["net_intake_spike_flag"] = (
    net_intake_change_abs >= net_intake_spike_threshold
)

df_pressure_spike["major_net_intake_spike_flag"] = (
    net_intake_change_abs >= major_net_intake_spike_threshold
)

df_pressure_spike["growth_rate_spike_flag"] = (
    growth_rate_change_abs >= growth_rate_spike_threshold
)

df_pressure_spike["major_growth_rate_spike_flag"] = (
    growth_rate_change_abs >= major_growth_rate_spike_threshold
)

df_pressure_spike["backlog_severity_jump_flag"] = (
    df_pressure_spike["daily_backlog_severity_change"] > 0
)

# ------------------------------------------------------------
# 8. Create directional spike interpretation
# ------------------------------------------------------------

def classify_system_load_direction(change_value):
    if change_value > 0:
        return "System Load Increase"
    elif change_value < 0:
        return "System Load Decrease"
    else:
        return "No System Load Change"

def classify_net_intake_direction(change_value):
    if change_value > 0:
        return "Net Intake Increase"
    elif change_value < 0:
        return "Net Intake Decrease"
    else:
        return "No Net Intake Change"

df_pressure_spike["system_load_change_direction"] = (
    df_pressure_spike["daily_system_load_change"].apply(classify_system_load_direction)
)

df_pressure_spike["net_intake_change_direction"] = (
    df_pressure_spike["daily_net_intake_change"].apply(classify_net_intake_direction)
)

# ------------------------------------------------------------
# 9. Create combined spike score
# ------------------------------------------------------------

df_pressure_spike["pressure_spike_score"] = (
    df_pressure_spike["system_load_spike_flag"].astype(int)
    + df_pressure_spike["major_system_load_spike_flag"].astype(int)
    + df_pressure_spike["net_intake_spike_flag"].astype(int)
    + df_pressure_spike["major_net_intake_spike_flag"].astype(int)
    + df_pressure_spike["growth_rate_spike_flag"].astype(int)
    + df_pressure_spike["major_growth_rate_spike_flag"].astype(int)
    + df_pressure_spike["backlog_severity_jump_flag"].astype(int)
)

# ------------------------------------------------------------
# 10. Classify pressure spike level
# ------------------------------------------------------------

def classify_pressure_spike_level(score):
    if score >= 5:
        return "Critical Pressure Spike"
    elif score >= 3:
        return "High Pressure Spike"
    elif score >= 1:
        return "Moderate Pressure Spike"
    else:
        return "No Major Spike"

df_pressure_spike["pressure_spike_level"] = (
    df_pressure_spike["pressure_spike_score"].apply(classify_pressure_spike_level)
)

# ------------------------------------------------------------
# 11. Create spike risk category
# ------------------------------------------------------------

def classify_spike_risk(row):
    if (
        row["major_system_load_spike_flag"]
        and row["system_load_change_direction"] == "System Load Increase"
    ):
        return "Major Load Increase Risk"
    elif (
        row["major_net_intake_spike_flag"]
        and row["net_intake_change_direction"] == "Net Intake Increase"
    ):
        return "Major Intake Increase Risk"
    elif row["backlog_severity_jump_flag"]:
        return "Backlog Severity Escalation"
    elif row["pressure_spike_score"] >= 3:
        return "Multi-Factor Spike Risk"
    elif row["pressure_spike_score"] >= 1:
        return "Moderate Spike Watch"
    else:
        return "No Spike Risk"

df_pressure_spike["pressure_spike_risk_category"] = (
    df_pressure_spike.apply(classify_spike_risk, axis=1)
)

# ------------------------------------------------------------
# 12. Create spike distribution summaries
# ------------------------------------------------------------

pressure_spike_level_distribution = (
    df_pressure_spike["pressure_spike_level"]
    .value_counts()
    .rename_axis("Pressure Spike Level")
    .reset_index(name="Record Count")
)

pressure_spike_level_distribution["Record Percentage"] = (
    pressure_spike_level_distribution["Record Count"] / len(df_pressure_spike) * 100
).round(2)

spike_risk_category_distribution = (
    df_pressure_spike["pressure_spike_risk_category"]
    .value_counts()
    .rename_axis("Pressure Spike Risk Category")
    .reset_index(name="Record Count")
)

spike_risk_category_distribution["Record Percentage"] = (
    spike_risk_category_distribution["Record Count"] / len(df_pressure_spike) * 100
).round(2)

# ------------------------------------------------------------
# 13. Create validation summary
# ------------------------------------------------------------

new_5d_columns = [
    "daily_system_load_change",
    "daily_net_intake_change",
    "daily_growth_rate_change",
    "daily_backlog_severity_change",
    "daily_cbp_custody_change",
    "daily_hhs_care_change",
    "system_load_pct_change",
    "net_intake_pct_change",
    "cbp_custody_pct_change",
    "hhs_care_pct_change",
    "system_load_spike_flag",
    "major_system_load_spike_flag",
    "net_intake_spike_flag",
    "major_net_intake_spike_flag",
    "growth_rate_spike_flag",
    "major_growth_rate_spike_flag",
    "backlog_severity_jump_flag",
    "system_load_change_direction",
    "net_intake_change_direction",
    "pressure_spike_score",
    "pressure_spike_level",
    "pressure_spike_risk_category"
]

missing_new_5d_columns = [
    col for col in new_5d_columns
    if col not in df_pressure_spike.columns
]

missing_values_new_5d_columns = int(
    df_pressure_spike[new_5d_columns].isna().sum().sum()
)

rows_after_5d = df_pressure_spike.shape[0]
cols_after_5d = df_pressure_spike.shape[1]

rows_deleted_or_modified_5d = rows_before_5d - rows_after_5d

step_5d_validation_summary = pd.DataFrame({
    "Step 5D Check": [
        "Input Dataset Source",
        "Rows Checked",
        "Columns Before Step 5D",
        "Columns After Step 5D",
        "New Spike Columns Created",
        "Missing Required Input Columns",
        "Missing New Spike Columns",
        "Missing Values in New Spike Columns",
        "Date Parse Errors",
        "Duplicate Dates",
        "Chronological Order",
        "Rows Deleted or Modified"
    ],
    "Result": [
        input_dataset_source,
        rows_after_5d,
        cols_before_5d,
        cols_after_5d,
        len(new_5d_columns),
        len(missing_5d_columns),
        len(missing_new_5d_columns),
        missing_values_new_5d_columns,
        date_parse_errors_5d,
        duplicate_dates_5d,
        chronological_order_5d,
        rows_deleted_or_modified_5d
    ]
})

# ------------------------------------------------------------
# 14. Preview columns
# ------------------------------------------------------------

pressure_spike_preview_columns = [
    "Date",
    "total_system_load",
    "daily_system_load_change",
    "system_load_pct_change",
    "net_daily_intake",
    "daily_net_intake_change",
    "net_intake_pct_change",
    "care_load_growth_rate_pct",
    "daily_growth_rate_change",
    "backlog_severity_score",
    "pressure_spike_score",
    "pressure_spike_level",
    "pressure_spike_risk_category"
]

pressure_spike_preview_columns = [
    col for col in pressure_spike_preview_columns
    if col in df_pressure_spike.columns
]

# ------------------------------------------------------------
# 15. Final display outputs
# ------------------------------------------------------------

print("\nPressure spike indicators created successfully.")
print(f"Final Step 5D dataset shape: {rows_after_5d} rows × {cols_after_5d} columns")

print("\nPressure spike level distribution:")
display(pressure_spike_level_distribution)

print("\nPressure spike risk category distribution:")
display(spike_risk_category_distribution)

print("\nStep 5D validation summary:")
display(step_5d_validation_summary)

print("\nPressure spike dataset preview:")
display(df_pressure_spike[pressure_spike_preview_columns].head(10))

print("\nPressure spike dataset tail:")
display(df_pressure_spike[pressure_spike_preview_columns].tail(10))

print("\nStep 5D completed successfully.")
print("Pressure spike / sudden change indicators are ready for Step 5E.")

Step 5D - Create Pressure Spike / Sudden Change Indicators
================================================================================
Pressure spike working copy created successfully.
Input dataset source: df_pressure_volatility
Input dataset shape: 720 rows × 53 columns
Missing Step 5D required input columns: 0
Date parse errors: 0
Dataset chronological order: True
Duplicate dates: 0

Spike threshold values:
90th percentile system load change: 212.20
95th percentile system load change: 289.40
90th percentile net intake change: 115.00
95th percentile net intake change: 143.20
90th percentile growth rate change: 4.09
95th percentile growth rate change: 5.40

Pressure spike indicators created successfully.
Final Step 5D dataset shape: 720 rows × 75 columns

Pressure spike level distribution:

C:\Users\Mohit\AppData\Local\Temp\ipykernel_9200\1456595716.py:142: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  .pct_change()

      Pressure Spike Level  Record Count  Record Percentage
0           No Major Spike           452              62.78
1  Moderate Pressure Spike           219              30.42
2      High Pressure Spike            42               5.83
3  Critical Pressure Spike             7               0.97

Pressure spike risk category distribution:

  Pressure Spike Risk Category  Record Count  Record Percentage
0                No Spike Risk           452              62.78
1  Backlog Severity Escalation           122              16.94
2         Moderate Spike Watch            93              12.92
3      Multi-Factor Spike Risk            28               3.89
4   Major Intake Increase Risk            20               2.78
5     Major Load Increase Risk             5               0.69

Step 5D validation summary:

                          Step 5D Check                  Result
0                  Input Dataset Source  df_pressure_volatility
1                          Rows Checked                     720
2                Columns Before Step 5D                      53
3                 Columns After Step 5D                      75
4             New Spike Columns Created                      22
5        Missing Required Input Columns                       0
6             Missing New Spike Columns                       0
7   Missing Values in New Spike Columns                       0
8                     Date Parse Errors                       0
9                       Duplicate Dates                       0
10                  Chronological Order                    True
11             Rows Deleted or Modified                       0

Pressure spike dataset preview:

,Date,total_system_load,daily_system_load_change,system_load_pct_change,net_daily_intake,daily_net_intake_change,net_intake_pct_change,care_load_growth_rate_pct,daily_growth_rate_change,backlog_severity_score,pressure_spike_score,pressure_spike_level,pressure_spike_risk_category
0,2023-01-12,6619,0.0,0.000000,-402,0.0,0.000000,0.00,0.00,0,0,No Major Spike,No Spike Risk
1,2023-01-22,7171,552.0,8.339628,-188,214.0,-53.233831,8.34,8.34,0,6,Critical Pressure Spike,Major Load Increase Risk
2,2023-01-23,7330,159.0,2.217264,-142,46.0,-24.468085,2.22,-6.12,0,2,Moderate Pressure Spike,Moderate Spike Watch
3,2023-01-24,7475,145.0,1.978172,-128,14.0,-9.859155,1.98,-0.24,0,0,No Major Spike,No Spike Risk
4,2023-01-25,7560,85.0,1.137124,-139,-11.0,8.593750,1.14,-0.84,0,0,No Major Spike,No Spike Risk
5,2023-01-29,7517,-43.0,-0.568783,-292,-153.0,110.071942,-0.57,-1.71,0,2,Moderate Pressure Spike,Moderate Spike Watch
6,2023-01-30,7797,280.0,3.724890,-167,125.0,-42.808219,3.72,4.29,0,3,High Pressure Spike,Multi-Factor Spike Risk
7,2023-01-31,7839,42.0,0.538669,-122,45.0,-26.946108,0.54,-3.18,0,0,No Major Spike,No Spike Risk
8,2023-02-01,7935,96.0,1.224646,-204,-82.0,67.213115,1.22,0.68,0,0,No Major Spike,No Spike Risk
9,2023-02-02,7892,-43.0,-0.541903,-275,-71.0,34.803922,-0.54,-1.76,0,0,No Major Spike,No Spike Risk

Pressure spike dataset tail:

,Date,total_system_load,daily_system_load_change,system_load_pct_change,net_daily_intake,daily_net_intake_change,net_intake_pct_change,care_load_growth_rate_pct,daily_growth_rate_change,backlog_severity_score,pressure_spike_score,pressure_spike_level,pressure_spike_risk_category
710,2025-12-08,2467,14.0,0.570730,5,4.0,400.000000,0.57,0.73,1,0,No Major Spike,No Spike Risk
711,2025-12-09,2473,6.0,0.243210,-1,-6.0,-120.000000,0.24,-0.33,0,0,No Major Spike,No Spike Risk
712,2025-12-10,2493,20.0,0.808734,-4,-3.0,300.000000,0.81,0.57,0,0,No Major Spike,No Spike Risk
713,2025-12-11,2484,-9.0,-0.361011,-1,3.0,-75.000000,-0.36,-1.17,0,0,No Major Spike,No Spike Risk
714,2025-12-14,2497,13.0,0.523349,-4,-3.0,300.000000,0.52,0.88,0,0,No Major Spike,No Spike Risk
715,2025-12-15,2512,15.0,0.600721,2,6.0,-150.000000,0.60,0.08,1,1,Moderate Pressure Spike,Backlog Severity Escalation
716,2025-12-16,2522,10.0,0.398089,6,4.0,200.000000,0.40,-0.20,1,0,No Major Spike,No Spike Risk
717,2025-12-17,2512,-10.0,-0.396511,1,-5.0,-83.333333,-0.40,-0.80,2,1,Moderate Pressure Spike,Backlog Severity Escalation
718,2025-12-18,2522,10.0,0.398089,-10,-11.0,-1100.000000,0.40,0.80,0,0,No Major Spike,No Spike Risk
719,2025-12-21,2502,-20.0,-0.793021,-3,7.0,-70.000000,-0.79,-1.19,0,0,No Major Spike,No Spike Risk

Step 5D completed successfully.
Pressure spike / sudden change indicators are ready for Step 5E.

## Step 5E — Detect Prolonged Strain / High-Pressure Windows

In this step, we identify prolonged pressure and strain windows across the daily care load timeline.

This step uses the pressure-enriched dataset created in the previous steps and detects continuous high-pressure periods based on multiple operational signals, including:

- Rolling pressure level
- Volatility pressure level
- Pressure spike level
- Backlog severity
- High-load day indicators
- Logical anomaly pressure

The goal of this step is to move beyond single-day spikes and identify sustained operational stress windows where the care system remained under pressure for multiple consecutive reporting dates.

This output will support the next analysis stages by helping identify:

- Prolonged strain periods
- High-pressure date windows
- System pressure duration
- Peak pressure windows
- Critical operational stress periods

In [5]:
# ============================================================
# Step 5E — Detect Prolonged Strain / High-Pressure Windows
# ============================================================

import pandas as pd
import numpy as np

print("Step 5E - Detect Prolonged Strain / High-Pressure Windows")
print("=" * 80)

# ------------------------------------------------------------
# 1. Select safest available input dataframe
# ------------------------------------------------------------

input_source_name = None

if "df_pressure_spike" in globals():
    df_pressure_windows_base = df_pressure_spike.copy()
    input_source_name = "df_pressure_spike"
elif "df_pressure_volatility" in globals():
    df_pressure_windows_base = df_pressure_volatility.copy()
    input_source_name = "df_pressure_volatility"
elif "df_pressure_rolling" in globals():
    df_pressure_windows_base = df_pressure_rolling.copy()
    input_source_name = "df_pressure_rolling"
elif "df_daily_trend_high_load" in globals():
    df_pressure_windows_base = df_daily_trend_high_load.copy()
    input_source_name = "df_daily_trend_high_load"
elif "df_daily_trend" in globals():
    df_pressure_windows_base = df_daily_trend.copy()
    input_source_name = "df_daily_trend"
else:
    raise NameError(
        "No valid input dataframe found for Step 5E. "
        "Please run Step 5A to Step 5D first."
    )

print(f"Pressure window working copy created successfully.")
print(f"Input dataset source: {input_source_name}")
print(f"Input dataset shape: {df_pressure_windows_base.shape[0]} rows × {df_pressure_windows_base.shape[1]} columns")

# ------------------------------------------------------------
# 2. Validate date column
# ------------------------------------------------------------

if "Date" not in df_pressure_windows_base.columns:
    raise KeyError("Required column missing: Date")

df_pressure_windows_base["Date"] = pd.to_datetime(
    df_pressure_windows_base["Date"],
    errors="coerce"
)

date_parse_errors = int(df_pressure_windows_base["Date"].isna().sum())

if date_parse_errors > 0:
    raise ValueError(
        f"Date parsing failed for {date_parse_errors} rows. "
        "Please fix Date column before Step 5E."
    )

df_pressure_windows_base = (
    df_pressure_windows_base
    .sort_values("Date")
    .reset_index(drop=True)
)

chronological_order = bool(df_pressure_windows_base["Date"].is_monotonic_increasing)
duplicate_dates = int(df_pressure_windows_base["Date"].duplicated().sum())

print(f"Date parse errors: {date_parse_errors}")
print(f"Dataset chronological order: {chronological_order}")
print(f"Duplicate dates: {duplicate_dates}")

# ------------------------------------------------------------
# 3. Required base metric validation
# ------------------------------------------------------------

base_required_columns = [
    "total_system_load",
    "net_daily_intake",
    "care_load_growth_rate_pct",
    "backlog_severity_score"
]

missing_base_columns = [
    col for col in base_required_columns
    if col not in df_pressure_windows_base.columns
]

print(f"Missing Step 5E base input columns: {len(missing_base_columns)}")

if missing_base_columns:
    print("Missing columns:")
    for col in missing_base_columns:
        print(f"- {col}")
    raise KeyError(
        "Step 5E cannot continue because required base pressure columns are missing."
    )

# ------------------------------------------------------------
# 4. Helper functions
# ------------------------------------------------------------

def safe_numeric(series):
    return pd.to_numeric(series, errors="coerce")


def safe_flag_from_text(series, positive_keywords):
    """
    Converts text/category columns into 1/0 flags based on keyword matches.
    """
    text_series = series.fillna("").astype(str).str.lower()
    pattern = "|".join([str(keyword).lower() for keyword in positive_keywords])
    return text_series.str.contains(pattern, regex=True).astype(int)


def safe_binary_column(df, column_name, positive_keywords=None, default_value=0):
    """
    Safely creates a binary signal from an existing column.
    Works for numeric, bool, or text columns.
    """
    if column_name not in df.columns:
        return pd.Series(default_value, index=df.index)

    series = df[column_name]

    if pd.api.types.is_bool_dtype(series):
        return series.fillna(False).astype(int)

    if pd.api.types.is_numeric_dtype(series):
        return (pd.to_numeric(series, errors="coerce").fillna(0) > 0).astype(int)

    if positive_keywords is None:
        positive_keywords = ["high", "critical", "sustained", "pressure", "risk", "spike", "elevated"]

    return safe_flag_from_text(series, positive_keywords)


# ------------------------------------------------------------
# 5. Create individual pressure signals safely
# ------------------------------------------------------------

df_pressure_windows = df_pressure_windows_base.copy()

# Rolling pressure signal
if "rolling_pressure_level" in df_pressure_windows.columns:
    df_pressure_windows["rolling_pressure_signal"] = safe_flag_from_text(
        df_pressure_windows["rolling_pressure_level"],
        ["short-term rolling pressure", "sustained rolling pressure", "load above rolling average"]
    )
else:
    df_pressure_windows["rolling_pressure_signal"] = 0

# Volatility pressure signal
if "volatility_pressure_level" in df_pressure_windows.columns:
    df_pressure_windows["volatility_pressure_signal"] = safe_flag_from_text(
        df_pressure_windows["volatility_pressure_level"],
        ["moderate volatility pressure", "high volatility pressure"]
    )
else:
    df_pressure_windows["volatility_pressure_signal"] = 0

# Pressure spike signal
if "pressure_spike_level" in df_pressure_windows.columns:
    df_pressure_windows["pressure_spike_signal"] = safe_flag_from_text(
        df_pressure_windows["pressure_spike_level"],
        ["moderate pressure spike", "high pressure spike", "critical pressure spike"]
    )
else:
    df_pressure_windows["pressure_spike_signal"] = 0

# Pressure spike risk signal
if "pressure_spike_risk_category" in df_pressure_windows.columns:
    df_pressure_windows["pressure_spike_risk_signal"] = safe_flag_from_text(
        df_pressure_windows["pressure_spike_risk_category"],
        [
            "backlog severity escalation",
            "moderate spike watch",
            "multi-factor spike risk",
            "major intake increase risk",
            "major load increase risk"
        ]
    )
else:
    df_pressure_windows["pressure_spike_risk_signal"] = 0

# High-load signal from Notebook 04 / Step 4G
high_load_signal_columns = [
    "high_load_day_flag",
    "elevated_or_high_load_day_flag",
    "critical_load_day_flag",
    "sustained_high_load_flag"
]

existing_high_load_signal_columns = [
    col for col in high_load_signal_columns
    if col in df_pressure_windows.columns
]

if existing_high_load_signal_columns:
    high_load_signal_frame = pd.DataFrame(index=df_pressure_windows.index)

    for col in existing_high_load_signal_columns:
        high_load_signal_frame[col] = safe_binary_column(df_pressure_windows, col)

    df_pressure_windows["high_load_signal"] = (
        high_load_signal_frame.sum(axis=1) > 0
    ).astype(int)
else:
    df_pressure_windows["high_load_signal"] = 0

# Backlog pressure signal
df_pressure_windows["backlog_pressure_signal"] = (
    safe_numeric(df_pressure_windows["backlog_severity_score"]).fillna(0) >= 2
).astype(int)

# Logical anomaly signal
if "logical_constraint_anomaly_flag" in df_pressure_windows.columns:
    df_pressure_windows["logical_anomaly_signal"] = safe_binary_column(
        df_pressure_windows,
        "logical_constraint_anomaly_flag"
    )
elif "logical_anomaly_days" in df_pressure_windows.columns:
    df_pressure_windows["logical_anomaly_signal"] = (
        safe_numeric(df_pressure_windows["logical_anomaly_days"]).fillna(0) > 0
    ).astype(int)
else:
    df_pressure_windows["logical_anomaly_signal"] = 0

# Positive intake / intake pressure signal
if "positive_net_intake_flag" in df_pressure_windows.columns:
    df_pressure_windows["intake_pressure_signal"] = safe_binary_column(
        df_pressure_windows,
        "positive_net_intake_flag"
    )
else:
    df_pressure_windows["intake_pressure_signal"] = (
        safe_numeric(df_pressure_windows["net_daily_intake"]).fillna(0) > 0
    ).astype(int)

# ------------------------------------------------------------
# 6. Create combined daily strain score
# ------------------------------------------------------------

strain_signal_columns = [
    "rolling_pressure_signal",
    "volatility_pressure_signal",
    "pressure_spike_signal",
    "pressure_spike_risk_signal",
    "high_load_signal",
    "backlog_pressure_signal",
    "logical_anomaly_signal",
    "intake_pressure_signal"
]

df_pressure_windows["daily_pressure_signal_count"] = df_pressure_windows[strain_signal_columns].sum(axis=1)

df_pressure_windows["daily_strain_score"] = (
    df_pressure_windows["rolling_pressure_signal"] * 2
    + df_pressure_windows["volatility_pressure_signal"] * 1
    + df_pressure_windows["pressure_spike_signal"] * 2
    + df_pressure_windows["pressure_spike_risk_signal"] * 2
    + df_pressure_windows["high_load_signal"] * 2
    + df_pressure_windows["backlog_pressure_signal"] * 2
    + df_pressure_windows["logical_anomaly_signal"] * 1
    + df_pressure_windows["intake_pressure_signal"] * 1
)

# ------------------------------------------------------------
# 7. Classify daily strain level
# ------------------------------------------------------------

def classify_daily_strain(score):
    if score >= 9:
        return "Critical Daily Strain"
    elif score >= 6:
        return "High Daily Strain"
    elif score >= 3:
        return "Moderate Daily Strain"
    else:
        return "Normal Daily Pressure"


df_pressure_windows["daily_strain_level"] = df_pressure_windows["daily_strain_score"].apply(classify_daily_strain)

df_pressure_windows["high_pressure_day_flag"] = (
    df_pressure_windows["daily_strain_score"] >= 3
).astype(int)

df_pressure_windows["severe_pressure_day_flag"] = (
    df_pressure_windows["daily_strain_score"] >= 6
).astype(int)

print("\nDaily strain indicators created successfully.")

# ------------------------------------------------------------
# 8. Detect consecutive high-pressure windows
# ------------------------------------------------------------

df_pressure_windows["pressure_window_break"] = (
    df_pressure_windows["high_pressure_day_flag"]
    .ne(df_pressure_windows["high_pressure_day_flag"].shift())
).cumsum()

df_pressure_windows["pressure_window_id"] = np.where(
    df_pressure_windows["high_pressure_day_flag"] == 1,
    df_pressure_windows["pressure_window_break"],
    np.nan
)

# Keep only high-pressure days for window aggregation
df_high_pressure_days = df_pressure_windows[
    df_pressure_windows["high_pressure_day_flag"] == 1
].copy()

minimum_window_days = 3

if df_high_pressure_days.empty:
    df_prolonged_pressure_windows = pd.DataFrame(
        columns=[
            "pressure_window_id",
            "window_start_date",
            "window_end_date",
            "window_duration_days",
            "reporting_days",
            "avg_system_load",
            "peak_system_load",
            "avg_daily_strain_score",
            "max_daily_strain_score",
            "severe_pressure_days",
            "backlog_pressure_days",
            "spike_pressure_days",
            "volatility_pressure_days",
            "total_net_intake",
            "avg_net_daily_intake",
            "window_pressure_category"
        ]
    )
else:
    df_prolonged_pressure_windows = (
        df_high_pressure_days
        .groupby("pressure_window_id", dropna=True)
        .agg(
            window_start_date=("Date", "min"),
            window_end_date=("Date", "max"),
            reporting_days=("Date", "count"),
            avg_system_load=("total_system_load", "mean"),
            peak_system_load=("total_system_load", "max"),
            avg_daily_strain_score=("daily_strain_score", "mean"),
            max_daily_strain_score=("daily_strain_score", "max"),
            severe_pressure_days=("severe_pressure_day_flag", "sum"),
            backlog_pressure_days=("backlog_pressure_signal", "sum"),
            spike_pressure_days=("pressure_spike_signal", "sum"),
            volatility_pressure_days=("volatility_pressure_signal", "sum"),
            total_net_intake=("net_daily_intake", "sum"),
            avg_net_daily_intake=("net_daily_intake", "mean")
        )
        .reset_index()
    )

    df_prolonged_pressure_windows["window_duration_days"] = (
        df_prolonged_pressure_windows["window_end_date"]
        - df_prolonged_pressure_windows["window_start_date"]
    ).dt.days + 1

    df_prolonged_pressure_windows = df_prolonged_pressure_windows[
        df_prolonged_pressure_windows["reporting_days"] >= minimum_window_days
    ].copy()

    def classify_window_pressure(row):
        if row["max_daily_strain_score"] >= 9 or row["severe_pressure_days"] >= 5:
            return "Critical Prolonged Strain Window"
        elif row["avg_daily_strain_score"] >= 6 or row["severe_pressure_days"] >= 2:
            return "High Prolonged Strain Window"
        elif row["reporting_days"] >= 7:
            return "Extended Moderate Pressure Window"
        else:
            return "Short Prolonged Pressure Window"

    if not df_prolonged_pressure_windows.empty:
        df_prolonged_pressure_windows["window_pressure_category"] = (
            df_prolonged_pressure_windows.apply(classify_window_pressure, axis=1)
        )

        numeric_window_columns = [
            "avg_system_load",
            "avg_daily_strain_score",
            "avg_net_daily_intake"
        ]

        for col in numeric_window_columns:
            df_prolonged_pressure_windows[col] = df_prolonged_pressure_windows[col].round(2)

# ------------------------------------------------------------
# 9. Add prolonged window flags back to daily dataset
# ------------------------------------------------------------

df_pressure_windows["prolonged_pressure_window_flag"] = 0
df_pressure_windows["prolonged_pressure_window_category"] = "No Prolonged Pressure Window"

if not df_prolonged_pressure_windows.empty:
    valid_window_ids = df_prolonged_pressure_windows["pressure_window_id"].tolist()

    df_pressure_windows["prolonged_pressure_window_flag"] = (
        df_pressure_windows["pressure_window_id"].isin(valid_window_ids)
    ).astype(int)

    window_category_map = dict(
        zip(
            df_prolonged_pressure_windows["pressure_window_id"],
            df_prolonged_pressure_windows["window_pressure_category"]
        )
    )

    df_pressure_windows["prolonged_pressure_window_category"] = (
        df_pressure_windows["pressure_window_id"]
        .map(window_category_map)
        .fillna("No Prolonged Pressure Window")
    )

# ------------------------------------------------------------
# 10. Create daily pressure window level distribution
# ------------------------------------------------------------

df_daily_strain_distribution = (
    df_pressure_windows["daily_strain_level"]
    .value_counts(dropna=False)
    .reset_index()
)

df_daily_strain_distribution.columns = [
    "Daily Strain Level",
    "Record Count"
]

df_daily_strain_distribution["Record Percentage"] = (
    df_daily_strain_distribution["Record Count"]
    / len(df_pressure_windows)
    * 100
).round(2)

# ------------------------------------------------------------
# 11. Create prolonged window category distribution
# ------------------------------------------------------------

df_pressure_window_category_distribution = (
    df_pressure_windows["prolonged_pressure_window_category"]
    .value_counts(dropna=False)
    .reset_index()
)

df_pressure_window_category_distribution.columns = [
    "Prolonged Pressure Window Category",
    "Record Count"
]

df_pressure_window_category_distribution["Record Percentage"] = (
    df_pressure_window_category_distribution["Record Count"]
    / len(df_pressure_windows)
    * 100
).round(2)

# ------------------------------------------------------------
# 12. Create Step 5E validation summary
# ------------------------------------------------------------

new_step_5e_columns = [
    "rolling_pressure_signal",
    "volatility_pressure_signal",
    "pressure_spike_signal",
    "pressure_spike_risk_signal",
    "high_load_signal",
    "backlog_pressure_signal",
    "logical_anomaly_signal",
    "intake_pressure_signal",
    "daily_pressure_signal_count",
    "daily_strain_score",
    "daily_strain_level",
    "high_pressure_day_flag",
    "severe_pressure_day_flag",
    "pressure_window_break",
    "pressure_window_id",
    "prolonged_pressure_window_flag",
    "prolonged_pressure_window_category"
]

missing_new_step_5e_columns = [
    col for col in new_step_5e_columns
    if col not in df_pressure_windows.columns
]

missing_values_new_step_5e = int(
    df_pressure_windows[new_step_5e_columns]
    .isna()
    .sum()
    .sum()
)

df_step_5e_validation_summary = pd.DataFrame({
    "Step 5E Check": [
        "Input Dataset Source",
        "Rows Checked",
        "Columns Before Step 5E",
        "Columns After Step 5E",
        "New Window Columns Created",
        "Missing Required Input Columns",
        "Missing New Window Columns",
        "Missing Values in New Window Columns",
        "Date Parse Errors",
        "Duplicate Dates",
        "Chronological Order",
        "High-Pressure Days",
        "Severe Pressure Days",
        "Minimum Window Days Used",
        "Prolonged Pressure Windows Detected",
        "Rows Deleted or Modified"
    ],
    "Result": [
        input_source_name,
        df_pressure_windows_base.shape[0],
        df_pressure_windows_base.shape[1],
        df_pressure_windows.shape[1],
        len(new_step_5e_columns),
        len(missing_base_columns),
        len(missing_new_step_5e_columns),
        missing_values_new_step_5e,
        date_parse_errors,
        duplicate_dates,
        chronological_order,
        int(df_pressure_windows["high_pressure_day_flag"].sum()),
        int(df_pressure_windows["severe_pressure_day_flag"].sum()),
        minimum_window_days,
        len(df_prolonged_pressure_windows),
        df_pressure_windows_base.shape[0] - df_pressure_windows.shape[0]
    ]
})

# ------------------------------------------------------------
# 13. Preview columns
# ------------------------------------------------------------

pressure_window_preview_columns = [
    "Date",
    "total_system_load",
    "net_daily_intake",
    "care_load_growth_rate_pct",
    "backlog_severity_score",
    "daily_pressure_signal_count",
    "daily_strain_score",
    "daily_strain_level",
    "high_pressure_day_flag",
    "severe_pressure_day_flag",
    "pressure_window_id",
    "prolonged_pressure_window_flag",
    "prolonged_pressure_window_category"
]

pressure_window_preview_columns = [
    col for col in pressure_window_preview_columns
    if col in df_pressure_windows.columns
]

# ------------------------------------------------------------
# 14. Final outputs
# ------------------------------------------------------------

df_pressure_windows_daily = df_pressure_windows.copy()
df_prolonged_strain_windows = df_prolonged_pressure_windows.copy()

print("\nDaily strain level distribution:")
display(df_daily_strain_distribution)

print("\nProlonged pressure window category distribution:")
display(df_pressure_window_category_distribution)

print("\nProlonged strain / high-pressure window summary:")
display(df_prolonged_strain_windows)

print("\nStep 5E validation summary:")
display(df_step_5e_validation_summary)

print("\nPressure window daily dataset preview:")
display(df_pressure_windows_daily[pressure_window_preview_columns].head(10))

print("\nPressure window daily dataset tail:")
display(df_pressure_windows_daily[pressure_window_preview_columns].tail(10))

print("\nStep 5E completed successfully.")
print("Prolonged strain / high-pressure windows are ready for Step 5F.")

Step 5E - Detect Prolonged Strain / High-Pressure Windows
================================================================================
Pressure window working copy created successfully.
Input dataset source: df_pressure_spike
Input dataset shape: 720 rows × 75 columns
Date parse errors: 0
Dataset chronological order: True
Duplicate dates: 0
Missing Step 5E base input columns: 0

Daily strain indicators created successfully.

Daily strain level distribution:

      Daily Strain Level  Record Count  Record Percentage
0  Normal Daily Pressure           331              45.97
1  Moderate Daily Strain           213              29.58
2      High Daily Strain           137              19.03
3  Critical Daily Strain            39               5.42

Prolonged pressure window category distribution:

  Prolonged Pressure Window Category  Record Count  Record Percentage
0       No Prolonged Pressure Window           450              62.50
1   Critical Prolonged Strain Window           186              25.83
2    Short Prolonged Pressure Window            44               6.11
3       High Prolonged Strain Window            40               5.56

Prolonged strain / high-pressure window summary:

,pressure_window_id,window_start_date,window_end_date,reporting_days,avg_system_load,peak_system_load,avg_daily_strain_score,max_daily_strain_score,severe_pressure_days,backlog_pressure_days,spike_pressure_days,volatility_pressure_days,total_net_intake,avg_net_daily_intake,window_duration_days,window_pressure_category
0,2.0,2023-01-22,2023-02-08,13,7680.62,8111,5.08,7,5,0,7,13,-2496,-192.00,18,Critical Prolonged Strain Window
1,4.0,2023-02-12,2023-02-15,4,7866.50,8068,5.25,7,2,0,4,1,-337,-84.25,4,High Prolonged Strain Window
2,6.0,2023-02-20,2023-02-27,6,8081.67,8281,5.50,8,3,0,5,4,-460,-76.67,8,High Prolonged Strain Window
5,12.0,2023-03-23,2023-03-27,3,8212.00,8378,4.67,6,1,0,3,0,-410,-136.67,5,Short Prolonged Pressure Window
8,18.0,2023-04-24,2023-04-26,3,8245.00,8362,5.67,7,2,0,2,0,-47,-15.67,3,High Prolonged Strain Window
12,26.0,2023-05-25,2023-05-30,3,7268.00,7619,5.33,6,1,0,3,3,-583,-194.33,6,Short Prolonged Pressure Window
15,32.0,2023-06-19,2023-06-21,3,5935.00,6118,6.00,8,1,0,3,3,-211,-70.33,3,High Prolonged Strain Window
16,34.0,2023-06-25,2023-06-27,3,6063.00,6142,5.67,7,2,0,3,0,-27,-9.00,3,High Prolonged Strain Window
17,36.0,2023-07-04,2023-07-12,7,6518.86,6714,5.29,9,3,0,3,4,121,17.29,9,Critical Prolonged Strain Window
18,38.0,2023-07-16,2023-07-18,3,6893.67,7159,6.00,6,3,0,3,0,-90,-30.00,3,High Prolonged Strain Window
20,42.0,2023-07-31,2023-08-02,3,8285.67,8432,6.00,8,2,0,2,3,-151,-50.33,3,High Prolonged Strain Window
22,46.0,2023-08-09,2023-09-07,18,10121.39,10664,5.22,7,10,0,11,14,-2802,-155.67,30,Critical Prolonged Strain Window
26,54.0,2023-09-28,2023-10-02,3,10920.00,11146,4.67,5,0,0,3,0,-746,-248.67,5,Short Prolonged Pressure Window
27,56.0,2023-10-05,2023-10-10,3,11019.33,11200,4.33,6,1,0,2,0,-778,-259.33,6,Short Prolonged Pressure Window
28,58.0,2023-10-12,2023-10-16,3,10819.00,11072,5.00,7,1,0,3,0,-933,-311.00,5,Short Prolonged Pressure Window
30,62.0,2023-10-26,2023-10-30,3,9136.33,9332,5.33,6,1,0,3,3,-926,-308.67,5,Short Prolonged Pressure Window
31,64.0,2023-11-01,2023-11-12,7,9624.14,9860,4.86,7,3,0,3,6,-758,-108.29,12,High Prolonged Strain Window
32,66.0,2023-11-14,2023-11-16,3,9901.00,9938,4.00,6,1,0,1,0,-429,-143.00,3,Short Prolonged Pressure Window
38,78.0,2023-12-13,2023-12-18,4,11344.25,11399,4.50,6,2,0,2,0,-879,-219.75,6,High Prolonged Strain Window
42,86.0,2024-01-07,2024-01-09,3,9643.33,9788,5.33,6,1,0,3,2,-715,-238.33,3,Short Prolonged Pressure Window
43,88.0,2024-01-11,2024-01-16,3,8382.67,8880,5.00,5,0,0,3,3,-814,-271.33,6,Short Prolonged Pressure Window
44,90.0,2024-01-23,2024-01-25,3,8379.33,8408,3.33,4,0,0,0,3,-201,-67.00,3,Short Prolonged Pressure Window
45,92.0,2024-01-29,2024-02-01,4,8456.00,8630,7.50,9,4,0,4,4,-64,-16.00,4,Critical Prolonged Strain Window
46,94.0,2024-02-05,2024-02-14,8,8597.75,8834,6.38,10,5,3,5,3,715,89.38,10,Critical Prolonged Strain Window
47,96.0,2024-02-19,2024-02-21,3,8895.33,9003,6.67,10,2,1,2,1,321,107.00,3,Critical Prolonged Strain Window
49,100.0,2024-02-27,2024-02-29,3,9111.00,9168,6.67,10,2,1,2,1,172,57.33,3,Critical Prolonged Strain Window
50,102.0,2024-03-04,2024-03-11,6,9211.50,9327,5.50,9,2,2,4,0,300,50.00,8,Critical Prolonged Strain Window
55,112.0,2024-03-31,2024-04-02,3,7529.00,7570,4.33,5,0,0,3,0,-94,-31.33,3,Short Prolonged Pressure Window
56,114.0,2024-04-07,2024-04-10,4,7239.00,7274,4.25,5,0,0,4,0,-76,-19.00,4,Short Prolonged Pressure Window
57,116.0,2024-04-14,2024-04-16,3,6978.67,7077,4.33,5,0,0,3,0,-20,-6.67,3,Short Prolonged Pressure Window
58,118.0,2024-04-21,2024-05-15,19,7718.95,7988,5.74,9,8,14,7,1,1176,61.89,25,Critical Prolonged Strain Window
60,122.0,2024-05-22,2024-06-03,8,7837.75,7969,6.75,9,5,8,4,0,539,67.38,13,Critical Prolonged Strain Window
61,124.0,2024-06-05,2024-06-10,4,7904.00,8067,4.75,7,1,0,3,0,8,2.00,6,Short Prolonged Pressure Window
68,138.0,2024-07-07,2024-07-10,4,6796.75,6832,5.75,8,2,2,3,0,102,25.50,4,High Prolonged Strain Window
72,146.0,2024-07-31,2024-08-12,9,6221.11,6314,5.78,9,4,3,7,0,40,4.44,13,Critical Prolonged Strain Window
75,152.0,2024-08-20,2024-09-05,10,6467.80,6678,6.20,9,3,10,3,0,659,65.90,17,Critical Prolonged Strain Window
76,154.0,2024-09-09,2024-09-11,3,6644.33,6658,6.33,9,2,1,2,0,94,31.33,3,Critical Prolonged Strain Window
80,162.0,2024-09-30,2024-10-10,8,6262.25,6354,5.25,10,3,3,4,0,300,37.50,11,Critical Prolonged Strain Window
81,164.0,2024-10-14,2024-10-23,8,6258.88,6371,5.25,9,2,6,3,0,336,42.00,10,Critical Prolonged Strain Window
82,166.0,2024-10-28,2024-10-30,3,6362.67,6425,6.33,9,2,1,2,0,158,52.67,3,Critical Prolonged Strain Window
84,170.0,2024-11-06,2024-11-18,8,6184.12,6342,6.00,9,4,6,6,0,119,14.88,13,Critical Prolonged Strain Window
86,174.0,2024-11-25,2024-12-08,10,6332.30,6593,5.70,10,2,8,3,0,670,67.00,14,Critical Prolonged Strain Window
87,176.0,2024-12-10,2024-12-12,3,6708.33,6755,6.67,10,2,1,2,0,236,78.67,3,Critical Prolonged Strain Window
88,178.0,2024-12-16,2024-12-18,3,6813.33,6883,6.33,9,2,1,2,0,212,70.67,3,Critical Prolonged Strain Window
101,204.0,2025-03-19,2025-03-31,9,2172.22,2218,5.89,9,3,7,3,0,51,5.67,13,Critical Prolonged Strain Window
103,208.0,2025-04-07,2025-04-10,4,2274.00,2290,6.00,9,2,2,2,0,23,5.75,4,Critical Prolonged Strain Window
109,220.0,2025-05-07,2025-05-14,6,2404.50,2425,5.67,9,2,4,2,0,30,5.00,8,Critical Prolonged Strain Window
124,250.0,2025-10-09,2025-10-14,3,2253.00,2265,6.33,9,2,1,2,0,10,3.33,6,Critical Prolonged Strain Window
126,254.0,2025-10-21,2025-10-26,4,2299.25,2311,6.00,9,2,2,2,0,19,4.75,6,Critical Prolonged Strain Window
133,268.0,2025-11-25,2025-11-30,3,2422.67,2433,6.33,9,2,1,2,0,14,4.67,6,Critical Prolonged Strain Window
136,274.0,2025-12-15,2025-12-17,3,2515.33,2522,6.33,9,2,1,2,0,9,3.00,3,Critical Prolonged Strain Window

Step 5E validation summary:

                           Step 5E Check             Result
0                   Input Dataset Source  df_pressure_spike
1                           Rows Checked                720
2                 Columns Before Step 5E                 75
3                  Columns After Step 5E                 92
4             New Window Columns Created                 17
5         Missing Required Input Columns                  0
6             Missing New Window Columns                  0
7   Missing Values in New Window Columns                331
8                      Date Parse Errors                  0
9                        Duplicate Dates                  0
10                   Chronological Order               True
11                    High-Pressure Days                389
12                  Severe Pressure Days                176
13              Minimum Window Days Used                  3
14   Prolonged Pressure Windows Detected                 51
15              Rows Deleted or Modified                  0

Pressure window daily dataset preview:

,Date,total_system_load,net_daily_intake,care_load_growth_rate_pct,backlog_severity_score,daily_pressure_signal_count,daily_strain_score,daily_strain_level,high_pressure_day_flag,severe_pressure_day_flag,pressure_window_id,prolonged_pressure_window_flag,prolonged_pressure_window_category
0,2023-01-12,6619,-402,0.00,0,0,0,Normal Daily Pressure,0,0,NaN,0,No Prolonged Pressure Window
1,2023-01-22,7171,-188,8.34,0,4,7,High Daily Strain,1,1,2.0,1,Critical Prolonged Strain Window
2,2023-01-23,7330,-142,2.22,0,4,7,High Daily Strain,1,1,2.0,1,Critical Prolonged Strain Window
3,2023-01-24,7475,-128,1.98,0,3,4,Moderate Daily Strain,1,0,2.0,1,Critical Prolonged Strain Window
4,2023-01-25,7560,-139,1.14,0,3,4,Moderate Daily Strain,1,0,2.0,1,Critical Prolonged Strain Window
5,2023-01-29,7517,-292,-0.57,0,4,7,High Daily Strain,1,1,2.0,1,Critical Prolonged Strain Window
6,2023-01-30,7797,-167,3.72,0,4,7,High Daily Strain,1,1,2.0,1,Critical Prolonged Strain Window
7,2023-01-31,7839,-122,0.54,0,2,3,Moderate Daily Strain,1,0,2.0,1,Critical Prolonged Strain Window
8,2023-02-01,7935,-204,1.22,0,2,3,Moderate Daily Strain,1,0,2.0,1,Critical Prolonged Strain Window
9,2023-02-02,7892,-275,-0.54,0,3,4,Moderate Daily Strain,1,0,2.0,1,Critical Prolonged Strain Window

Pressure window daily dataset tail:

,Date,total_system_load,net_daily_intake,care_load_growth_rate_pct,backlog_severity_score,daily_pressure_signal_count,daily_strain_score,daily_strain_level,high_pressure_day_flag,severe_pressure_day_flag,pressure_window_id,prolonged_pressure_window_flag,prolonged_pressure_window_category
710,2025-12-08,2467,5,0.57,1,2,3,Moderate Daily Strain,1,0,272.0,0,No Prolonged Pressure Window
711,2025-12-09,2473,-1,0.24,0,1,2,Normal Daily Pressure,0,0,NaN,0,No Prolonged Pressure Window
712,2025-12-10,2493,-4,0.81,0,1,2,Normal Daily Pressure,0,0,NaN,0,No Prolonged Pressure Window
713,2025-12-11,2484,-1,-0.36,0,1,2,Normal Daily Pressure,0,0,NaN,0,No Prolonged Pressure Window
714,2025-12-14,2497,-4,0.52,0,1,2,Normal Daily Pressure,0,0,NaN,0,No Prolonged Pressure Window
715,2025-12-15,2512,2,0.60,1,4,7,High Daily Strain,1,1,274.0,1,Critical Prolonged Strain Window
716,2025-12-16,2522,6,0.40,1,2,3,Moderate Daily Strain,1,0,274.0,1,Critical Prolonged Strain Window
717,2025-12-17,2512,1,-0.40,2,5,9,Critical Daily Strain,1,1,274.0,1,Critical Prolonged Strain Window
718,2025-12-18,2522,-10,0.40,0,1,2,Normal Daily Pressure,0,0,NaN,0,No Prolonged Pressure Window
719,2025-12-21,2502,-3,-0.79,0,0,0,Normal Daily Pressure,0,0,NaN,0,No Prolonged Pressure Window

Step 5E completed successfully.
Prolonged strain / high-pressure windows are ready for Step 5F.

## Step 5F — Create Final Pressure & Stress Classification Summary

This step creates the final pressure and stress classification layer by combining rolling pressure, volatility, spike indicators, and prolonged pressure window signals.

The objective is to convert daily operational pressure patterns into an executive-ready classification system for identifying normal, early warning, moderate stress, high stress, and critical pressure days.

This step preserves all existing rows and columns from previous steps.

In [8]:
# ============================================================
# Step 5F - Create Final Pressure & Stress Classification Summary
# ============================================================

import pandas as pd
import numpy as np

print("Step 5F - Create Final Pressure & Stress Classification Summary")
print("=" * 75)

# ------------------------------------------------------------
# 1. Select safest available input dataset
# ------------------------------------------------------------

if "df_pressure_windows_daily" in globals():
    df_pressure_final = df_pressure_windows_daily.copy()
    input_dataset_source = "df_pressure_windows_daily"
elif "df_pressure_spike" in globals():
    df_pressure_final = df_pressure_spike.copy()
    input_dataset_source = "df_pressure_spike"
elif "df_pressure_volatility" in globals():
    df_pressure_final = df_pressure_volatility.copy()
    input_dataset_source = "df_pressure_volatility"
elif "df_pressure_rolling" in globals():
    df_pressure_final = df_pressure_rolling.copy()
    input_dataset_source = "df_pressure_rolling"
else:
    raise NameError(
        "No valid Step 5 input dataset found. Please run Step 5B to Step 5E before Step 5F."
    )

print("Final pressure working copy created successfully.")
print(f"Input dataset source: {input_dataset_source}")
print(f"Input dataset shape: {df_pressure_final.shape[0]} rows × {df_pressure_final.shape[1]} columns")

rows_before_step_5f = df_pressure_final.shape[0]
columns_before_step_5f = df_pressure_final.shape[1]

# ------------------------------------------------------------
# 2. Basic validation
# ------------------------------------------------------------

if "Date" not in df_pressure_final.columns:
    raise KeyError("Required column missing: Date")

df_pressure_final["Date"] = pd.to_datetime(df_pressure_final["Date"], errors="coerce")

date_parse_errors = int(df_pressure_final["Date"].isna().sum())

df_pressure_final = df_pressure_final.sort_values("Date").reset_index(drop=True)

duplicate_dates = int(df_pressure_final["Date"].duplicated().sum())
chronological_order = bool(df_pressure_final["Date"].is_monotonic_increasing)

required_base_columns = [
    "total_system_load",
    "net_daily_intake",
    "care_load_growth_rate_pct",
    "backlog_severity_score"
]

missing_required_base_columns = [
    col for col in required_base_columns if col not in df_pressure_final.columns
]

if missing_required_base_columns:
    raise KeyError(f"Missing required base columns for Step 5F: {missing_required_base_columns}")

print(f"Missing Step 5F base input columns: {len(missing_required_base_columns)}")
print(f"Date parse errors: {date_parse_errors}")
print(f"Dataset chronological order: {chronological_order}")
print(f"Duplicate dates: {duplicate_dates}")

# ------------------------------------------------------------
# 3. Helper functions
# ------------------------------------------------------------

def get_numeric_series(df, column_name, default_value=0):
    """
    Safely returns a numeric series.
    If column is missing, returns a default numeric series.
    """
    if column_name in df.columns:
        return pd.to_numeric(df[column_name], errors="coerce").fillna(default_value)
    return pd.Series(default_value, index=df.index)


def normalize_to_10(series):
    """
    Converts any numeric signal into a 0-10 scale using min-max normalization.
    Handles flat or empty series safely.
    """
    series = pd.to_numeric(series, errors="coerce").fillna(0)

    min_value = series.min()
    max_value = series.max()

    if pd.isna(min_value) or pd.isna(max_value) or max_value == min_value:
        return pd.Series(0, index=series.index)

    return ((series - min_value) / (max_value - min_value) * 10).round(2)


def binary_score(series, score_value=10):
    """
    Converts binary/boolean flags into numeric score.
    """
    return np.where(pd.to_numeric(series, errors="coerce").fillna(0) > 0, score_value, 0)


# ------------------------------------------------------------
# 4. Build calibrated component scores
# ------------------------------------------------------------

rolling_pressure_score = get_numeric_series(df_pressure_final, "rolling_pressure_score", 0)
volatility_pressure_score = get_numeric_series(df_pressure_final, "volatility_pressure_score", 0)
pressure_spike_score = get_numeric_series(df_pressure_final, "pressure_spike_score", 0)
daily_strain_score = get_numeric_series(df_pressure_final, "daily_strain_score", 0)

high_pressure_day_flag = get_numeric_series(df_pressure_final, "high_pressure_day_flag", 0)
severe_pressure_day_flag = get_numeric_series(df_pressure_final, "severe_pressure_day_flag", 0)

prolonged_window_flag = get_numeric_series(df_pressure_final, "prolonged_pressure_window_flag", 0)
critical_window_flag = get_numeric_series(df_pressure_final, "critical_prolonged_window_flag", 0)

# Fallback window scoring from category column if direct flags are not available
if "prolonged_pressure_window_category" in df_pressure_final.columns:
    window_category_score_map = {
        "No Prolonged Pressure Window": 0,
        "Short Prolonged Pressure Window": 3,
        "High Prolonged Strain Window": 7,
        "Critical Prolonged Strain Window": 10
    }

    prolonged_category_score = (
        df_pressure_final["prolonged_pressure_window_category"]
        .map(window_category_score_map)
        .fillna(0)
    )
else:
    prolonged_category_score = pd.Series(0, index=df_pressure_final.index)

# Normalize raw operational intensity signals
system_load_intensity_score = normalize_to_10(df_pressure_final["total_system_load"])
net_intake_pressure_score = normalize_to_10(df_pressure_final["net_daily_intake"].abs())
growth_pressure_score = normalize_to_10(df_pressure_final["care_load_growth_rate_pct"].abs())
backlog_pressure_score = normalize_to_10(df_pressure_final["backlog_severity_score"])

# Normalize existing Step 5 metrics
rolling_pressure_score_norm = normalize_to_10(rolling_pressure_score)
volatility_pressure_score_norm = normalize_to_10(volatility_pressure_score)
pressure_spike_score_norm = normalize_to_10(pressure_spike_score)
daily_strain_score_norm = normalize_to_10(daily_strain_score)

# Window/flag scores
high_pressure_day_score = binary_score(high_pressure_day_flag, 6)
severe_pressure_day_score = binary_score(severe_pressure_day_flag, 10)
prolonged_window_score = np.maximum(
    binary_score(prolonged_window_flag, 7),
    prolonged_category_score
)
critical_window_score = binary_score(critical_window_flag, 10)

# ------------------------------------------------------------
# 5. Final recalibrated pressure stress score
# ------------------------------------------------------------

df_pressure_final["rolling_pressure_component_score"] = rolling_pressure_score_norm
df_pressure_final["volatility_pressure_component_score"] = volatility_pressure_score_norm
df_pressure_final["pressure_spike_component_score"] = pressure_spike_score_norm
df_pressure_final["daily_strain_component_score"] = daily_strain_score_norm
df_pressure_final["load_intensity_component_score"] = system_load_intensity_score
df_pressure_final["net_intake_component_score"] = net_intake_pressure_score
df_pressure_final["growth_pressure_component_score"] = growth_pressure_score
df_pressure_final["backlog_component_score"] = backlog_pressure_score
df_pressure_final["window_pressure_component_score"] = prolonged_window_score
df_pressure_final["critical_window_component_score"] = critical_window_score

df_pressure_final["final_pressure_stress_score"] = (
    df_pressure_final["daily_strain_component_score"] * 0.22
    + df_pressure_final["volatility_pressure_component_score"] * 0.18
    + df_pressure_final["pressure_spike_component_score"] * 0.16
    + df_pressure_final["rolling_pressure_component_score"] * 0.14
    + df_pressure_final["load_intensity_component_score"] * 0.10
    + df_pressure_final["net_intake_component_score"] * 0.06
    + df_pressure_final["growth_pressure_component_score"] * 0.05
    + df_pressure_final["backlog_component_score"] * 0.05
    + df_pressure_final["window_pressure_component_score"] * 0.03
    + df_pressure_final["critical_window_component_score"] * 0.01
).round(2)

# ------------------------------------------------------------
# 6. Dynamic percentile-based recalibration thresholds
# ------------------------------------------------------------

score_series = df_pressure_final["final_pressure_stress_score"].copy()

non_zero_scores = score_series[score_series > 0]

if len(non_zero_scores) >= 10:
    q40 = non_zero_scores.quantile(0.40)
    q65 = non_zero_scores.quantile(0.65)
    q82 = non_zero_scores.quantile(0.82)
    q94 = non_zero_scores.quantile(0.94)
else:
    q40 = score_series.quantile(0.40)
    q65 = score_series.quantile(0.65)
    q82 = score_series.quantile(0.82)
    q94 = score_series.quantile(0.94)

# Make sure thresholds are stable and increasing
threshold_early = max(float(q40), 0.75)
threshold_moderate = max(float(q65), threshold_early + 0.25)
threshold_high = max(float(q82), threshold_moderate + 0.25)
threshold_critical = max(float(q94), threshold_high + 0.25)

print("\nFinal pressure stress recalibration thresholds:")
print(f"Early pressure threshold: {threshold_early:.2f}")
print(f"Moderate stress threshold: {threshold_moderate:.2f}")
print(f"High stress threshold: {threshold_high:.2f}")
print(f"Critical pressure threshold: {threshold_critical:.2f}")

# ------------------------------------------------------------
# 7. Final pressure stress classification
# ------------------------------------------------------------

def classify_final_pressure(row):
    score = row["final_pressure_stress_score"]

    severe_flag = row.get("severe_pressure_day_flag", 0)
    high_flag = row.get("high_pressure_day_flag", 0)
    spike_score = row.get("pressure_spike_score", 0)
    strain_score = row.get("daily_strain_score", 0)
    backlog_score = row.get("backlog_severity_score", 0)

    critical_window = row.get("critical_prolonged_window_flag", 0)
    prolonged_window = row.get("prolonged_pressure_window_flag", 0)

    if (
        score >= threshold_critical
        or critical_window == 1
        or (severe_flag == 1 and spike_score >= 6)
        or (strain_score >= 8 and backlog_score >= 2)
    ):
        return "Critical System Pressure"

    elif (
        score >= threshold_high
        or severe_flag == 1
        or (high_flag == 1 and spike_score >= 4)
        or (strain_score >= 6 and prolonged_window == 1)
    ):
        return "High System Stress"

    elif (
        score >= threshold_moderate
        or high_flag == 1
        or spike_score >= 4
        or strain_score >= 4
        or backlog_score >= 2
    ):
        return "Moderate System Stress"

    elif (
        score >= threshold_early
        or spike_score > 0
        or strain_score > 0
        or backlog_score > 0
    ):
        return "Early Pressure Watch"

    else:
        return "Normal Operating Pressure"


df_pressure_final["final_pressure_stress_level"] = df_pressure_final.apply(
    classify_final_pressure,
    axis=1
)

# ------------------------------------------------------------
# 8. Operational response category
# ------------------------------------------------------------

operational_response_map = {
    "Normal Operating Pressure": "Routine Monitoring",
    "Early Pressure Watch": "Early Warning Review",
    "Moderate System Stress": "Operational Watch Required",
    "High System Stress": "Priority Monitoring Required",
    "Critical System Pressure": "Immediate Escalation Required"
}

df_pressure_final["operational_response_category"] = (
    df_pressure_final["final_pressure_stress_level"]
    .map(operational_response_map)
    .fillna("Review Required")
)

# ------------------------------------------------------------
# 9. Primary pressure driver classification
# ------------------------------------------------------------

def classify_primary_pressure_driver(row):
    driver_scores = {
        "Rolling Load Pressure": row.get("rolling_pressure_component_score", 0),
        "Volatility Pressure": row.get("volatility_pressure_component_score", 0),
        "Sudden Spike Pressure": row.get("pressure_spike_component_score", 0),
        "Daily Strain Pressure": row.get("daily_strain_component_score", 0),
        "Backlog Severity Pressure": row.get("backlog_component_score", 0),
        "Prolonged Window Pressure": row.get("window_pressure_component_score", 0)
    }

    max_driver = max(driver_scores, key=driver_scores.get)
    max_score = driver_scores[max_driver]

    if max_score <= 0:
        return "No Major Pressure Driver"

    return max_driver


df_pressure_final["primary_pressure_driver"] = df_pressure_final.apply(
    classify_primary_pressure_driver,
    axis=1
)

# ------------------------------------------------------------
# 10. Final pressure priority rank
# ------------------------------------------------------------

priority_rank_map = {
    "Normal Operating Pressure": 1,
    "Early Pressure Watch": 2,
    "Moderate System Stress": 3,
    "High System Stress": 4,
    "Critical System Pressure": 5
}

df_pressure_final["final_pressure_priority_rank"] = (
    df_pressure_final["final_pressure_stress_level"]
    .map(priority_rank_map)
    .fillna(0)
    .astype(int)
)

# ------------------------------------------------------------
# 11. Summary tables
# ------------------------------------------------------------

final_pressure_stress_distribution = (
    df_pressure_final["final_pressure_stress_level"]
    .value_counts()
    .reindex(
        [
            "Normal Operating Pressure",
            "Early Pressure Watch",
            "Moderate System Stress",
            "High System Stress",
            "Critical System Pressure"
        ],
        fill_value=0
    )
    .reset_index()
)

final_pressure_stress_distribution.columns = [
    "Final Pressure Stress Level",
    "Record Count"
]

final_pressure_stress_distribution["Record Percentage"] = (
    final_pressure_stress_distribution["Record Count"]
    / len(df_pressure_final)
    * 100
).round(2)

operational_response_distribution = (
    df_pressure_final["operational_response_category"]
    .value_counts()
    .reindex(
        [
            "Routine Monitoring",
            "Early Warning Review",
            "Operational Watch Required",
            "Priority Monitoring Required",
            "Immediate Escalation Required"
        ],
        fill_value=0
    )
    .reset_index()
)

operational_response_distribution.columns = [
    "Operational Response Category",
    "Record Count"
]

operational_response_distribution["Record Percentage"] = (
    operational_response_distribution["Record Count"]
    / len(df_pressure_final)
    * 100
).round(2)

primary_pressure_driver_summary = (
    df_pressure_final["primary_pressure_driver"]
    .value_counts()
    .reset_index()
)

primary_pressure_driver_summary.columns = [
    "Primary Pressure Driver",
    "Record Count"
]

primary_pressure_driver_summary["Record Percentage"] = (
    primary_pressure_driver_summary["Record Count"]
    / len(df_pressure_final)
    * 100
).round(2)

executive_final_pressure_summary = pd.DataFrame({
    "Final Pressure Summary Metric": [
        "Input Dataset Source",
        "Total Reporting Days",
        "Normal Operating Pressure Days",
        "Early Pressure Watch Days",
        "Moderate System Stress Days",
        "High System Stress Days",
        "Critical System Pressure Days",
        "Average Final Pressure Stress Score",
        "Maximum Final Pressure Stress Score",
        "Highest Pressure Date",
        "Rows Deleted or Modified"
    ],
    "Result": [
        input_dataset_source,
        len(df_pressure_final),
        int((df_pressure_final["final_pressure_stress_level"] == "Normal Operating Pressure").sum()),
        int((df_pressure_final["final_pressure_stress_level"] == "Early Pressure Watch").sum()),
        int((df_pressure_final["final_pressure_stress_level"] == "Moderate System Stress").sum()),
        int((df_pressure_final["final_pressure_stress_level"] == "High System Stress").sum()),
        int((df_pressure_final["final_pressure_stress_level"] == "Critical System Pressure").sum()),
        round(df_pressure_final["final_pressure_stress_score"].mean(), 2),
        round(df_pressure_final["final_pressure_stress_score"].max(), 2),
        df_pressure_final.loc[
            df_pressure_final["final_pressure_stress_score"].idxmax(),
            "Date"
        ].date(),
        rows_before_step_5f - df_pressure_final.shape[0]
    ]
})

# ------------------------------------------------------------
# 12. Validation summary
# ------------------------------------------------------------

new_step_5f_columns = [
    "rolling_pressure_component_score",
    "volatility_pressure_component_score",
    "pressure_spike_component_score",
    "daily_strain_component_score",
    "load_intensity_component_score",
    "net_intake_component_score",
    "growth_pressure_component_score",
    "backlog_component_score",
    "window_pressure_component_score",
    "critical_window_component_score",
    "final_pressure_stress_score",
    "final_pressure_stress_level",
    "operational_response_category",
    "primary_pressure_driver",
    "final_pressure_priority_rank"
]

missing_new_step_5f_columns = [
    col for col in new_step_5f_columns if col not in df_pressure_final.columns
]

missing_values_new_step_5f_columns = int(
    df_pressure_final[new_step_5f_columns].isna().sum().sum()
)

step_5f_validation_summary = pd.DataFrame({
    "Step 5F Check": [
        "Input Dataset Source",
        "Rows Checked",
        "Columns Before Step 5F",
        "Columns After Step 5F",
        "New Final Classification Columns Created",
        "Missing Required Base Columns",
        "Missing New Final Columns",
        "Missing Values in New Final Columns",
        "Date Parse Errors",
        "Duplicate Dates",
        "Chronological Order",
        "Rows Deleted or Modified"
    ],
    "Result": [
        input_dataset_source,
        df_pressure_final.shape[0],
        columns_before_step_5f,
        df_pressure_final.shape[1],
        len(new_step_5f_columns),
        len(missing_required_base_columns),
        len(missing_new_step_5f_columns),
        missing_values_new_step_5f_columns,
        date_parse_errors,
        duplicate_dates,
        chronological_order,
        rows_before_step_5f - df_pressure_final.shape[0]
    ]
})

# ------------------------------------------------------------
# 13. Display summaries
# ------------------------------------------------------------

print("\nFinal pressure classification created successfully.")

print("\nFinal pressure stress level distribution:")
display(final_pressure_stress_distribution)

print("\nOperational response category distribution:")
display(operational_response_distribution)

print("\nPrimary pressure driver summary:")
display(primary_pressure_driver_summary)

print("\nExecutive final pressure classification summary:")
display(executive_final_pressure_summary)

print("\nStep 5F validation summary:")
display(step_5f_validation_summary)

# ------------------------------------------------------------
# 14. Display final dataset preview
# ------------------------------------------------------------

final_pressure_preview_columns = [
    "Date",
    "total_system_load",
    "net_daily_intake",
    "care_load_growth_rate_pct",
    "backlog_severity_score",
    "rolling_pressure_score",
    "volatility_pressure_score",
    "pressure_spike_score",
    "daily_strain_score",
    "final_pressure_stress_score",
    "final_pressure_stress_level",
    "operational_response_category",
    "primary_pressure_driver",
    "final_pressure_priority_rank"
]

final_pressure_preview_columns = [
    col for col in final_pressure_preview_columns if col in df_pressure_final.columns
]

print("\nFinal pressure classification dataset preview:")
display(df_pressure_final[final_pressure_preview_columns].head(10))

print("\nFinal pressure classification dataset tail:")
display(df_pressure_final[final_pressure_preview_columns].tail(10))

print("\nStep 5F completed successfully.")
print("Final pressure and stress classification summary is ready for Step 5G.")

Step 5F - Create Final Pressure & Stress Classification Summary
===========================================================================
Final pressure working copy created successfully.
Input dataset source: df_pressure_windows_daily
Input dataset shape: 720 rows × 92 columns
Missing Step 5F base input columns: 0
Date parse errors: 0
Dataset chronological order: True
Duplicate dates: 0

Final pressure stress recalibration thresholds:
Early pressure threshold: 1.60
Moderate stress threshold: 2.56
High stress threshold: 3.37
Critical pressure threshold: 4.19

Final pressure classification created successfully.

Final pressure stress level distribution:

  Final Pressure Stress Level  Record Count  Record Percentage
0   Normal Operating Pressure           128              17.78
1        Early Pressure Watch           196              27.22
2      Moderate System Stress           180              25.00
3          High System Stress           138              19.17
4    Critical System Pressure            78              10.83

Operational response category distribution:

   Operational Response Category  Record Count  Record Percentage
0             Routine Monitoring           128              17.78
1           Early Warning Review           196              27.22
2     Operational Watch Required           180              25.00
3   Priority Monitoring Required           138              19.17
4  Immediate Escalation Required            78              10.83

Primary pressure driver summary:

     Primary Pressure Driver  Record Count  Record Percentage
0      Daily Strain Pressure           223              30.97
1  Prolonged Window Pressure           210              29.17
2        Volatility Pressure           116              16.11
3   No Major Pressure Driver           101              14.03
4  Backlog Severity Pressure            52               7.22
5      Sudden Spike Pressure            18               2.50

Executive final pressure classification summary:

          Final Pressure Summary Metric                     Result
0                  Input Dataset Source  df_pressure_windows_daily
1                  Total Reporting Days                        720
2        Normal Operating Pressure Days                        128
3             Early Pressure Watch Days                        196
4           Moderate System Stress Days                        180
5               High System Stress Days                        138
6         Critical System Pressure Days                         78
7   Average Final Pressure Stress Score                       2.05
8   Maximum Final Pressure Stress Score                       6.07
9                 Highest Pressure Date                 2023-01-22
10             Rows Deleted or Modified                          0

Step 5F validation summary:

                               Step 5F Check                     Result
0                       Input Dataset Source  df_pressure_windows_daily
1                               Rows Checked                        720
2                     Columns Before Step 5F                         92
3                      Columns After Step 5F                        107
4   New Final Classification Columns Created                         15
5              Missing Required Base Columns                          0
6                  Missing New Final Columns                          0
7        Missing Values in New Final Columns                          0
8                          Date Parse Errors                          0
9                            Duplicate Dates                          0
10                       Chronological Order                       True
11                  Rows Deleted or Modified                          0

Final pressure classification dataset preview:

,Date,total_system_load,net_daily_intake,care_load_growth_rate_pct,backlog_severity_score,volatility_pressure_score,pressure_spike_score,daily_strain_score,final_pressure_stress_score,final_pressure_stress_level,operational_response_category,primary_pressure_driver,final_pressure_priority_rank
0,2023-01-12,6619,-402,0.00,0,0,0,0,0.99,Normal Operating Pressure,Routine Monitoring,No Major Pressure Driver,1
1,2023-01-22,7171,-188,8.34,0,5,6,7,6.07,Critical System Pressure,Immediate Escalation Required,Sudden Spike Pressure,5
2,2023-01-23,7330,-142,2.22,0,5,2,7,4.70,Critical System Pressure,Immediate Escalation Required,Prolonged Window Pressure,5
3,2023-01-24,7475,-128,1.98,0,5,0,4,3.49,High System Stress,Priority Monitoring Required,Prolonged Window Pressure,4
4,2023-01-25,7560,-139,1.14,0,5,0,4,3.48,High System Stress,Priority Monitoring Required,Prolonged Window Pressure,4
5,2023-01-29,7517,-292,-0.57,0,5,2,7,4.84,Critical System Pressure,Immediate Escalation Required,Prolonged Window Pressure,5
6,2023-01-30,7797,-167,3.72,0,5,3,7,5.11,Critical System Pressure,Immediate Escalation Required,Prolonged Window Pressure,5
7,2023-01-31,7839,-122,0.54,0,5,0,3,3.24,Moderate System Stress,Operational Watch Required,Prolonged Window Pressure,3
8,2023-02-01,7935,-204,1.22,0,4,0,3,3.08,Moderate System Stress,Operational Watch Required,Prolonged Window Pressure,3
9,2023-02-02,7892,-275,-0.54,0,4,0,4,3.36,Moderate System Stress,Operational Watch Required,Prolonged Window Pressure,3

Final pressure classification dataset tail:

,Date,total_system_load,net_daily_intake,care_load_growth_rate_pct,backlog_severity_score,volatility_pressure_score,pressure_spike_score,daily_strain_score,final_pressure_stress_score,final_pressure_stress_level,operational_response_category,primary_pressure_driver,final_pressure_priority_rank
710,2025-12-08,2467,5,0.57,1,0,0,3,0.91,Moderate System Stress,Operational Watch Required,Backlog Severity Pressure,3
711,2025-12-09,2473,-1,0.24,0,0,0,2,0.50,Early Pressure Watch,Early Warning Review,Daily Strain Pressure,2
712,2025-12-10,2493,-4,0.81,0,0,0,2,0.53,Early Pressure Watch,Early Warning Review,Daily Strain Pressure,2
713,2025-12-11,2484,-1,-0.36,0,0,0,2,0.51,Early Pressure Watch,Early Warning Review,Daily Strain Pressure,2
714,2025-12-14,2497,-4,0.52,0,0,0,2,0.52,Early Pressure Watch,Early Warning Review,Daily Strain Pressure,2
715,2025-12-15,2512,2,0.60,1,0,1,7,2.35,High System Stress,Priority Monitoring Required,Prolonged Window Pressure,4
716,2025-12-16,2522,6,0.40,1,0,0,3,1.20,Moderate System Stress,Operational Watch Required,Prolonged Window Pressure,3
717,2025-12-17,2512,1,-0.40,2,1,1,9,3.25,Critical System Pressure,Immediate Escalation Required,Prolonged Window Pressure,5
718,2025-12-18,2522,-10,0.40,0,0,0,2,0.52,Early Pressure Watch,Early Warning Review,Daily Strain Pressure,2
719,2025-12-21,2502,-3,-0.79,0,0,0,0,0.09,Normal Operating Pressure,Routine Monitoring,No Major Pressure Driver,1

Step 5F completed successfully.
Final pressure and stress classification summary is ready for Step 5G.

## Step 5G — Export Final Pressure & Stress Classification Dataset

In this step, the final pressure and stress classification dataset is exported for downstream analysis, visualization, and dashboard preparation.

This step uses the final classified dataset created in Step 5F and saves it as a structured CSV file inside the processed data directory.

### Objectives

- Export the final pressure and stress classification dataset.
- Preserve all engineered rolling, volatility, spike, prolonged strain, and final classification metrics.
- Create a compact export validation summary.
- Confirm that the exported dataset has the expected row count, column count, and no duplicate dates.
- Prepare the dataset for the next notebook/dashboard stage.

### Output

The final exported file will be saved as:

`data/processed/final_pressure_stress_classification_dataset.csv`

In [9]:
# ============================================================
# Step 5G — Export Final Pressure & Stress Classification Dataset
# ============================================================

print("Step 5G - Export Final Pressure & Stress Classification Dataset")
print("=" * 75)

# ------------------------------------------------------------
# 1. Import required libraries
# ------------------------------------------------------------

import os
import pandas as pd


# ------------------------------------------------------------
# 2. Validate Step 5F final dataset availability
# ------------------------------------------------------------

required_step_5g_input = "df_pressure_final"

if required_step_5g_input not in globals():
    raise NameError(
        "Step 5G Error: df_pressure_final is not available. "
        "Please run Step 5F before Step 5G."
    )

if not isinstance(df_pressure_final, pd.DataFrame):
    raise TypeError(
        "Step 5G Error: df_pressure_final exists but is not a pandas DataFrame."
    )

if df_pressure_final.empty:
    raise ValueError(
        "Step 5G Error: df_pressure_final is empty. "
        "Please verify Step 5F output before exporting."
    )

print("Final pressure dataset found successfully.")
print(f"Input dataset shape: {df_pressure_final.shape[0]} rows × {df_pressure_final.shape[1]} columns")


# ------------------------------------------------------------
# 3. Create safe export copy
# ------------------------------------------------------------

df_pressure_export = df_pressure_final.copy()

print("Export working copy created successfully.")


# ------------------------------------------------------------
# 4. Ensure Date column is clean and chronological
# ------------------------------------------------------------

if "Date" not in df_pressure_export.columns:
    raise KeyError(
        "Step 5G Error: Date column is missing from df_pressure_final."
    )

df_pressure_export["Date"] = pd.to_datetime(df_pressure_export["Date"], errors="coerce")

date_parse_errors = int(df_pressure_export["Date"].isna().sum())

if date_parse_errors > 0:
    raise ValueError(
        f"Step 5G Error: {date_parse_errors} Date values could not be parsed."
    )

df_pressure_export = df_pressure_export.sort_values("Date").reset_index(drop=True)

duplicate_dates = int(df_pressure_export["Date"].duplicated().sum())
chronological_order_status = bool(df_pressure_export["Date"].is_monotonic_increasing)

print(f"Date parse errors: {date_parse_errors}")
print(f"Duplicate dates: {duplicate_dates}")
print(f"Dataset chronological order: {chronological_order_status}")


# ------------------------------------------------------------
# 5. Validate important final classification columns
# ------------------------------------------------------------

required_final_export_columns = [
    "Date",
    "total_system_load",
    "net_daily_intake",
    "care_load_growth_rate_pct",
    "backlog_severity_score",
    "final_pressure_stress_score",
    "final_pressure_stress_level",
    "operational_response_category",
    "primary_pressure_driver"
]

missing_final_export_columns = [
    col for col in required_final_export_columns
    if col not in df_pressure_export.columns
]

if missing_final_export_columns:
    raise KeyError(
        "Step 5G Error: Missing required final export columns: "
        f"{missing_final_export_columns}"
    )

missing_values_in_required_columns = int(
    df_pressure_export[required_final_export_columns].isna().sum().sum()
)

print(f"Missing required final export columns: {len(missing_final_export_columns)}")
print(f"Missing values in required export columns: {missing_values_in_required_columns}")


# ------------------------------------------------------------
# 6. Create export directory
# ------------------------------------------------------------

processed_output_dir = os.path.join("data", "processed")
os.makedirs(processed_output_dir, exist_ok=True)

print(f"Processed output directory ready: {processed_output_dir}")


# ------------------------------------------------------------
# 7. Define export file paths
# ------------------------------------------------------------

final_pressure_export_path = os.path.join(
    processed_output_dir,
    "final_pressure_stress_classification_dataset.csv"
)

final_pressure_summary_export_path = os.path.join(
    processed_output_dir,
    "final_pressure_stress_export_summary.csv"
)

final_pressure_level_distribution_path = os.path.join(
    processed_output_dir,
    "final_pressure_stress_level_distribution.csv"
)

operational_response_distribution_path = os.path.join(
    processed_output_dir,
    "operational_response_category_distribution.csv"
)

primary_pressure_driver_distribution_path = os.path.join(
    processed_output_dir,
    "primary_pressure_driver_distribution.csv"
)


# ------------------------------------------------------------
# 8. Export final full dataset
# ------------------------------------------------------------

df_pressure_export.to_csv(final_pressure_export_path, index=False)

print("Final pressure and stress classification dataset exported successfully.")
print(f"Export path: {final_pressure_export_path}")


# ------------------------------------------------------------
# 9. Create distribution summary exports
# ------------------------------------------------------------

final_pressure_level_distribution = (
    df_pressure_export["final_pressure_stress_level"]
    .value_counts(dropna=False)
    .reset_index()
)

final_pressure_level_distribution.columns = [
    "Final Pressure Stress Level",
    "Record Count"
]

final_pressure_level_distribution["Record Percentage"] = (
    final_pressure_level_distribution["Record Count"] / len(df_pressure_export) * 100
).round(2)

final_pressure_level_distribution.to_csv(
    final_pressure_level_distribution_path,
    index=False
)


operational_response_distribution = (
    df_pressure_export["operational_response_category"]
    .value_counts(dropna=False)
    .reset_index()
)

operational_response_distribution.columns = [
    "Operational Response Category",
    "Record Count"
]

operational_response_distribution["Record Percentage"] = (
    operational_response_distribution["Record Count"] / len(df_pressure_export) * 100
).round(2)

operational_response_distribution.to_csv(
    operational_response_distribution_path,
    index=False
)


primary_pressure_driver_distribution = (
    df_pressure_export["primary_pressure_driver"]
    .value_counts(dropna=False)
    .reset_index()
)

primary_pressure_driver_distribution.columns = [
    "Primary Pressure Driver",
    "Record Count"
]

primary_pressure_driver_distribution["Record Percentage"] = (
    primary_pressure_driver_distribution["Record Count"] / len(df_pressure_export) * 100
).round(2)

primary_pressure_driver_distribution.to_csv(
    primary_pressure_driver_distribution_path,
    index=False
)

print("Final distribution summary files exported successfully.")


# ------------------------------------------------------------
# 10. Create export validation summary
# ------------------------------------------------------------

final_export_summary = pd.DataFrame({
    "Step 5G Export Check": [
        "Input Dataset Source",
        "Exported Dataset Rows",
        "Exported Dataset Columns",
        "Date Parse Errors",
        "Duplicate Dates",
        "Chronological Order",
        "Missing Required Export Columns",
        "Missing Values in Required Export Columns",
        "Final Pressure Stress Levels",
        "Operational Response Categories",
        "Primary Pressure Drivers",
        "Full Dataset Export Path",
        "Stress Level Distribution Export Path",
        "Operational Response Distribution Export Path",
        "Primary Pressure Driver Distribution Export Path"
    ],
    "Result": [
        "df_pressure_final",
        df_pressure_export.shape[0],
        df_pressure_export.shape[1],
        date_parse_errors,
        duplicate_dates,
        chronological_order_status,
        len(missing_final_export_columns),
        missing_values_in_required_columns,
        df_pressure_export["final_pressure_stress_level"].nunique(dropna=False),
        df_pressure_export["operational_response_category"].nunique(dropna=False),
        df_pressure_export["primary_pressure_driver"].nunique(dropna=False),
        final_pressure_export_path,
        final_pressure_level_distribution_path,
        operational_response_distribution_path,
        primary_pressure_driver_distribution_path
    ]
})

final_export_summary.to_csv(final_pressure_summary_export_path, index=False)

print("Step 5G export validation summary created successfully.")


# ------------------------------------------------------------
# 11. Display export validation summary
# ------------------------------------------------------------

print("\nStep 5G validation summary:")
display(final_export_summary)


# ------------------------------------------------------------
# 12. Display final distribution summaries
# ------------------------------------------------------------

print("\nFinal pressure stress level distribution:")
display(final_pressure_level_distribution)

print("\nOperational response category distribution:")
display(operational_response_distribution)

print("\nPrimary pressure driver distribution:")
display(primary_pressure_driver_distribution)


# ------------------------------------------------------------
# 13. Display final exported dataset preview
# ------------------------------------------------------------

final_export_preview_columns = [
    col for col in [
        "Date",
        "total_system_load",
        "net_daily_intake",
        "care_load_growth_rate_pct",
        "backlog_severity_score",
        "volatility_pressure_score",
        "pressure_spike_score",
        "daily_strain_score",
        "final_pressure_stress_score",
        "final_pressure_stress_level",
        "operational_response_category",
        "primary_pressure_driver"
    ]
    if col in df_pressure_export.columns
]

print("\nFinal exported dataset preview:")
display(df_pressure_export[final_export_preview_columns].head(10))

print("\nFinal exported dataset tail:")
display(df_pressure_export[final_export_preview_columns].tail(10))


# ------------------------------------------------------------
# 14. Completion message
# ------------------------------------------------------------

print("\nStep 5G completed successfully.")
print("Final pressure and stress classification dataset is exported and ready for Step 5H or the next notebook stage.")

Step 5G - Export Final Pressure & Stress Classification Dataset
===========================================================================
Final pressure dataset found successfully.
Input dataset shape: 720 rows × 107 columns
Export working copy created successfully.
Date parse errors: 0
Duplicate dates: 0
Dataset chronological order: True
Missing required final export columns: 0
Missing values in required export columns: 0
Processed output directory ready: data\processed
Final pressure and stress classification dataset exported successfully.
Export path: data\processed\final_pressure_stress_classification_dataset.csv
Final distribution summary files exported successfully.
Step 5G export validation summary created successfully.

Step 5G validation summary:

,Step 5G Export Check,Result
0,Input Dataset Source,df_pressure_final
1,Exported Dataset Rows,720
2,Exported Dataset Columns,107
3,Date Parse Errors,0
4,Duplicate Dates,0
5,Chronological Order,True
6,Missing Required Export Columns,0
7,Missing Values in Required Export Columns,0
8,Final Pressure Stress Levels,5
9,Operational Response Categories,5
10,Primary Pressure Drivers,6
11,Full Dataset Export Path,data\processed\final_pressure_stress_classific...
12,Stress Level Distribution Export Path,data\processed\final_pressure_stress_level_dis...
13,Operational Response Distribution Export Path,data\processed\operational_response_category_d...
14,Primary Pressure Driver Distribution Export Path,data\processed\primary_pressure_driver_distrib...

Final pressure stress level distribution:

  Final Pressure Stress Level  Record Count  Record Percentage
0        Early Pressure Watch           196              27.22
1      Moderate System Stress           180              25.00
2          High System Stress           138              19.17
3   Normal Operating Pressure           128              17.78
4    Critical System Pressure            78              10.83

Operational response category distribution:

   Operational Response Category  Record Count  Record Percentage
0           Early Warning Review           196              27.22
1     Operational Watch Required           180              25.00
2   Priority Monitoring Required           138              19.17
3             Routine Monitoring           128              17.78
4  Immediate Escalation Required            78              10.83

Primary pressure driver distribution:

     Primary Pressure Driver  Record Count  Record Percentage
0      Daily Strain Pressure           223              30.97
1  Prolonged Window Pressure           210              29.17
2        Volatility Pressure           116              16.11
3   No Major Pressure Driver           101              14.03
4  Backlog Severity Pressure            52               7.22
5      Sudden Spike Pressure            18               2.50

Final exported dataset preview:

,Date,total_system_load,net_daily_intake,care_load_growth_rate_pct,backlog_severity_score,volatility_pressure_score,pressure_spike_score,daily_strain_score,final_pressure_stress_score,final_pressure_stress_level,operational_response_category,primary_pressure_driver
0,2023-01-12,6619,-402,0.00,0,0,0,0,0.99,Normal Operating Pressure,Routine Monitoring,No Major Pressure Driver
1,2023-01-22,7171,-188,8.34,0,5,6,7,6.07,Critical System Pressure,Immediate Escalation Required,Sudden Spike Pressure
2,2023-01-23,7330,-142,2.22,0,5,2,7,4.70,Critical System Pressure,Immediate Escalation Required,Prolonged Window Pressure
3,2023-01-24,7475,-128,1.98,0,5,0,4,3.49,High System Stress,Priority Monitoring Required,Prolonged Window Pressure
4,2023-01-25,7560,-139,1.14,0,5,0,4,3.48,High System Stress,Priority Monitoring Required,Prolonged Window Pressure
5,2023-01-29,7517,-292,-0.57,0,5,2,7,4.84,Critical System Pressure,Immediate Escalation Required,Prolonged Window Pressure
6,2023-01-30,7797,-167,3.72,0,5,3,7,5.11,Critical System Pressure,Immediate Escalation Required,Prolonged Window Pressure
7,2023-01-31,7839,-122,0.54,0,5,0,3,3.24,Moderate System Stress,Operational Watch Required,Prolonged Window Pressure
8,2023-02-01,7935,-204,1.22,0,4,0,3,3.08,Moderate System Stress,Operational Watch Required,Prolonged Window Pressure
9,2023-02-02,7892,-275,-0.54,0,4,0,4,3.36,Moderate System Stress,Operational Watch Required,Prolonged Window Pressure

Final exported dataset tail:

,Date,total_system_load,net_daily_intake,care_load_growth_rate_pct,backlog_severity_score,volatility_pressure_score,pressure_spike_score,daily_strain_score,final_pressure_stress_score,final_pressure_stress_level,operational_response_category,primary_pressure_driver
710,2025-12-08,2467,5,0.57,1,0,0,3,0.91,Moderate System Stress,Operational Watch Required,Backlog Severity Pressure
711,2025-12-09,2473,-1,0.24,0,0,0,2,0.50,Early Pressure Watch,Early Warning Review,Daily Strain Pressure
712,2025-12-10,2493,-4,0.81,0,0,0,2,0.53,Early Pressure Watch,Early Warning Review,Daily Strain Pressure
713,2025-12-11,2484,-1,-0.36,0,0,0,2,0.51,Early Pressure Watch,Early Warning Review,Daily Strain Pressure
714,2025-12-14,2497,-4,0.52,0,0,0,2,0.52,Early Pressure Watch,Early Warning Review,Daily Strain Pressure
715,2025-12-15,2512,2,0.60,1,0,1,7,2.35,High System Stress,Priority Monitoring Required,Prolonged Window Pressure
716,2025-12-16,2522,6,0.40,1,0,0,3,1.20,Moderate System Stress,Operational Watch Required,Prolonged Window Pressure
717,2025-12-17,2512,1,-0.40,2,1,1,9,3.25,Critical System Pressure,Immediate Escalation Required,Prolonged Window Pressure
718,2025-12-18,2522,-10,0.40,0,0,0,2,0.52,Early Pressure Watch,Early Warning Review,Daily Strain Pressure
719,2025-12-21,2502,-3,-0.79,0,0,0,0,0.09,Normal Operating Pressure,Routine Monitoring,No Major Pressure Driver

Step 5G completed successfully.
Final pressure and stress classification dataset is exported and ready for Step 5H or the next notebook stage.

## Step 5H — Final Notebook 05 Completion Summary / Validation Wrap-up

This step creates the final validation and completion summary for Notebook 05.

The objective of this step is to confirm that all pressure and stress identification stages have been completed successfully, including:

- Baseline pressure metric preparation
- Rolling average pressure metrics
- Variability and volatility pressure indicators
- Sudden spike and daily change detection
- Prolonged strain and high-pressure window detection
- Final pressure and stress classification
- Final dataset export for downstream analysis

This summary ensures that the final pressure and stress classification dataset is ready for the next notebook stage.

In [10]:
# ============================================================
# Step 5H — Final Notebook 05 Completion Summary / Validation Wrap-up
# ============================================================

print("Step 5H - Final Notebook 05 Completion Summary / Validation Wrap-up")
print("=" * 80)

import pandas as pd
from pathlib import Path

# ------------------------------------------------------------
# 1. Validate required final dataset from Step 5G
# ------------------------------------------------------------

required_final_objects = ["df_pressure_export"]

missing_final_objects = [
    obj for obj in required_final_objects
    if obj not in globals()
]

if missing_final_objects:
    raise NameError(
        f"Missing required final object(s) from previous step: {missing_final_objects}. "
        "Please run Step 5G before Step 5H."
    )

df_notebook_05_final = df_pressure_export.copy()

print("Final Notebook 05 dataset loaded successfully.")
print(f"Final dataset shape: {df_notebook_05_final.shape[0]} rows × {df_notebook_05_final.shape[1]} columns")

# ------------------------------------------------------------
# 2. Confirm final export path
# ------------------------------------------------------------

final_export_path = Path("data/processed/final_pressure_stress_classification_dataset.csv")

export_file_exists = final_export_path.exists()

print(f"Expected final export path: {final_export_path}")
print(f"Final exported file exists: {export_file_exists}")

if not export_file_exists:
    raise FileNotFoundError(
        "Final exported dataset file was not found. "
        "Please rerun Step 5G before completing Step 5H."
    )

# ------------------------------------------------------------
# 3. Validate key final classification columns
# ------------------------------------------------------------

expected_final_columns = [
    "Date",
    "total_system_load",
    "net_daily_intake",
    "care_load_growth_rate_pct",
    "backlog_severity_score",
    "volatility_pressure_score",
    "pressure_spike_score",
    "daily_strain_score",
    "final_pressure_stress_score",
    "final_pressure_stress_level",
    "operational_response_category",
    "primary_pressure_driver"
]

available_expected_columns = [
    col for col in expected_final_columns
    if col in df_notebook_05_final.columns
]

missing_expected_columns = [
    col for col in expected_final_columns
    if col not in df_notebook_05_final.columns
]

print(f"Expected final columns checked: {len(expected_final_columns)}")
print(f"Expected final columns available: {len(available_expected_columns)}")
print(f"Missing expected final columns: {len(missing_expected_columns)}")

if missing_expected_columns:
    print("Missing expected final columns list:")
    print(missing_expected_columns)

# ------------------------------------------------------------
# 4. Create step completion tracker
# ------------------------------------------------------------

notebook_05_step_completion_summary = pd.DataFrame({
    "Notebook Step": [
        "Step 5A",
        "Step 5B",
        "Step 5C",
        "Step 5D",
        "Step 5E",
        "Step 5F",
        "Step 5G",
        "Step 5H"
    ],
    "Step Description": [
        "Create Base Pressure and Stress Identification Dataset",
        "Create Rolling Average Pressure Metrics",
        "Create Variability / Volatility Pressure Metrics",
        "Create Pressure Spike / Sudden Change Indicators",
        "Detect Prolonged Strain / High-Pressure Windows",
        "Create Final Pressure & Stress Classification Summary",
        "Export Final Pressure & Stress Classification Dataset",
        "Final Notebook 05 Completion Summary / Validation Wrap-up"
    ],
    "Status": [
        "Completed",
        "Completed",
        "Completed",
        "Completed",
        "Completed",
        "Completed",
        "Completed",
        "Completed"
    ]
})

print("\nNotebook 05 step completion tracker:")
display(notebook_05_step_completion_summary)

# ------------------------------------------------------------
# 5. Final pressure stress distribution summary
# ------------------------------------------------------------

if "final_pressure_stress_level" in df_notebook_05_final.columns:
    final_pressure_distribution = (
        df_notebook_05_final["final_pressure_stress_level"]
        .value_counts(dropna=False)
        .reset_index()
    )

    final_pressure_distribution.columns = [
        "Final Pressure Stress Level",
        "Record Count"
    ]

    final_pressure_distribution["Record Percentage"] = (
        final_pressure_distribution["Record Count"] / len(df_notebook_05_final) * 100
    ).round(2)

    print("\nFinal pressure stress level distribution:")
    display(final_pressure_distribution)
else:
    final_pressure_distribution = pd.DataFrame()
    print("\nFinal pressure stress level distribution could not be created because column is missing.")

# ------------------------------------------------------------
# 6. Operational response distribution summary
# ------------------------------------------------------------

if "operational_response_category" in df_notebook_05_final.columns:
    operational_response_distribution = (
        df_notebook_05_final["operational_response_category"]
        .value_counts(dropna=False)
        .reset_index()
    )

    operational_response_distribution.columns = [
        "Operational Response Category",
        "Record Count"
    ]

    operational_response_distribution["Record Percentage"] = (
        operational_response_distribution["Record Count"] / len(df_notebook_05_final) * 100
    ).round(2)

    print("\nOperational response category distribution:")
    display(operational_response_distribution)
else:
    operational_response_distribution = pd.DataFrame()
    print("\nOperational response category distribution could not be created because column is missing.")

# ------------------------------------------------------------
# 7. Primary pressure driver summary
# ------------------------------------------------------------

if "primary_pressure_driver" in df_notebook_05_final.columns:
    primary_pressure_driver_summary = (
        df_notebook_05_final["primary_pressure_driver"]
        .value_counts(dropna=False)
        .reset_index()
    )

    primary_pressure_driver_summary.columns = [
        "Primary Pressure Driver",
        "Record Count"
    ]

    primary_pressure_driver_summary["Record Percentage"] = (
        primary_pressure_driver_summary["Record Count"] / len(df_notebook_05_final) * 100
    ).round(2)

    print("\nPrimary pressure driver summary:")
    display(primary_pressure_driver_summary)
else:
    primary_pressure_driver_summary = pd.DataFrame()
    print("\nPrimary pressure driver summary could not be created because column is missing.")

# ------------------------------------------------------------
# 8. Executive notebook completion summary
# ------------------------------------------------------------

total_reporting_days = len(df_notebook_05_final)

normal_days = (
    int((df_notebook_05_final["final_pressure_stress_level"] == "Normal Operating Pressure").sum())
    if "final_pressure_stress_level" in df_notebook_05_final.columns else 0
)

early_watch_days = (
    int((df_notebook_05_final["final_pressure_stress_level"] == "Early Pressure Watch").sum())
    if "final_pressure_stress_level" in df_notebook_05_final.columns else 0
)

moderate_stress_days = (
    int((df_notebook_05_final["final_pressure_stress_level"] == "Moderate System Stress").sum())
    if "final_pressure_stress_level" in df_notebook_05_final.columns else 0
)

high_stress_days = (
    int((df_notebook_05_final["final_pressure_stress_level"] == "High System Stress").sum())
    if "final_pressure_stress_level" in df_notebook_05_final.columns else 0
)

critical_pressure_days = (
    int((df_notebook_05_final["final_pressure_stress_level"] == "Critical System Pressure").sum())
    if "final_pressure_stress_level" in df_notebook_05_final.columns else 0
)

average_pressure_score = (
    round(df_notebook_05_final["final_pressure_stress_score"].mean(), 2)
    if "final_pressure_stress_score" in df_notebook_05_final.columns else None
)

maximum_pressure_score = (
    round(df_notebook_05_final["final_pressure_stress_score"].max(), 2)
    if "final_pressure_stress_score" in df_notebook_05_final.columns else None
)

highest_pressure_date = (
    df_notebook_05_final.loc[
        df_notebook_05_final["final_pressure_stress_score"].idxmax(),
        "Date"
    ]
    if "final_pressure_stress_score" in df_notebook_05_final.columns and "Date" in df_notebook_05_final.columns
    else None
)

notebook_05_final_summary = pd.DataFrame({
    "Notebook 05 Final Summary Metric": [
        "Final Dataset Name",
        "Final Export Path",
        "Total Reporting Days",
        "Total Final Columns",
        "Normal Operating Pressure Days",
        "Early Pressure Watch Days",
        "Moderate System Stress Days",
        "High System Stress Days",
        "Critical System Pressure Days",
        "Average Final Pressure Stress Score",
        "Maximum Final Pressure Stress Score",
        "Highest Pressure Date",
        "Rows Deleted or Modified",
        "Final Export File Exists",
        "Notebook 05 Completion Status",
        "Ready for Next Notebook Stage"
    ],
    "Result": [
        "df_notebook_05_final",
        str(final_export_path),
        total_reporting_days,
        df_notebook_05_final.shape[1],
        normal_days,
        early_watch_days,
        moderate_stress_days,
        high_stress_days,
        critical_pressure_days,
        average_pressure_score,
        maximum_pressure_score,
        highest_pressure_date,
        0,
        export_file_exists,
        "Completed Successfully",
        "Yes"
    ]
})

print("\nExecutive Notebook 05 final completion summary:")
display(notebook_05_final_summary)

# ------------------------------------------------------------
# 9. Final dataset preview
# ------------------------------------------------------------

final_preview_columns = [
    col for col in [
        "Date",
        "total_system_load",
        "net_daily_intake",
        "care_load_growth_rate_pct",
        "backlog_severity_score",
        "volatility_pressure_score",
        "pressure_spike_score",
        "daily_strain_score",
        "final_pressure_stress_score",
        "final_pressure_stress_level",
        "operational_response_category",
        "primary_pressure_driver"
    ]
    if col in df_notebook_05_final.columns
]

print("\nFinal Notebook 05 dataset preview:")
display(df_notebook_05_final[final_preview_columns].head(10))

print("\nFinal Notebook 05 dataset tail:")
display(df_notebook_05_final[final_preview_columns].tail(10))

# ------------------------------------------------------------
# 10. Completion message
# ------------------------------------------------------------

print("\nStep 5H completed successfully.")
print("Notebook 05 pressure and stress identification workflow is complete.")
print("Final pressure and stress classification dataset is exported and ready for the next notebook stage.")

Step 5H - Final Notebook 05 Completion Summary / Validation Wrap-up
================================================================================
Final Notebook 05 dataset loaded successfully.
Final dataset shape: 720 rows × 107 columns
Expected final export path: data\processed\final_pressure_stress_classification_dataset.csv
Final exported file exists: True
Expected final columns checked: 12
Expected final columns available: 12
Missing expected final columns: 0

Notebook 05 step completion tracker:

  Notebook Step                                   Step Description     Status
0       Step 5A  Create Base Pressure and Stress Identification...  Completed
1       Step 5B            Create Rolling Average Pressure Metrics  Completed
2       Step 5C   Create Variability / Volatility Pressure Metrics  Completed
3       Step 5D   Create Pressure Spike / Sudden Change Indicators  Completed
4       Step 5E    Detect Prolonged Strain / High-Pressure Windows  Completed
5       Step 5F  Create Final Pressure & Stress Classification ...  Completed
6       Step 5G  Export Final Pressure & Stress Classification ...  Completed
7       Step 5H  Final Notebook 05 Completion Summary / Validat...  Completed

Final pressure stress level distribution:

  Final Pressure Stress Level  Record Count  Record Percentage
0        Early Pressure Watch           196              27.22
1      Moderate System Stress           180              25.00
2          High System Stress           138              19.17
3   Normal Operating Pressure           128              17.78
4    Critical System Pressure            78              10.83

Operational response category distribution:

   Operational Response Category  Record Count  Record Percentage
0           Early Warning Review           196              27.22
1     Operational Watch Required           180              25.00
2   Priority Monitoring Required           138              19.17
3             Routine Monitoring           128              17.78
4  Immediate Escalation Required            78              10.83

Primary pressure driver summary:

     Primary Pressure Driver  Record Count  Record Percentage
0      Daily Strain Pressure           223              30.97
1  Prolonged Window Pressure           210              29.17
2        Volatility Pressure           116              16.11
3   No Major Pressure Driver           101              14.03
4  Backlog Severity Pressure            52               7.22
5      Sudden Spike Pressure            18               2.50

Executive Notebook 05 final completion summary:

,Notebook 05 Final Summary Metric,Result
0,Final Dataset Name,df_notebook_05_final
1,Final Export Path,data\processed\final_pressure_stress_classific...
2,Total Reporting Days,720
3,Total Final Columns,107
4,Normal Operating Pressure Days,128
5,Early Pressure Watch Days,196
6,Moderate System Stress Days,180
7,High System Stress Days,138
8,Critical System Pressure Days,78
9,Average Final Pressure Stress Score,2.05
10,Maximum Final Pressure Stress Score,6.07
11,Highest Pressure Date,2023-01-22 00:00:00
12,Rows Deleted or Modified,0
13,Final Export File Exists,True
14,Notebook 05 Completion Status,Completed Successfully
15,Ready for Next Notebook Stage,Yes

Final Notebook 05 dataset preview:

,Date,total_system_load,net_daily_intake,care_load_growth_rate_pct,backlog_severity_score,volatility_pressure_score,pressure_spike_score,daily_strain_score,final_pressure_stress_score,final_pressure_stress_level,operational_response_category,primary_pressure_driver
0,2023-01-12,6619,-402,0.00,0,0,0,0,0.99,Normal Operating Pressure,Routine Monitoring,No Major Pressure Driver
1,2023-01-22,7171,-188,8.34,0,5,6,7,6.07,Critical System Pressure,Immediate Escalation Required,Sudden Spike Pressure
2,2023-01-23,7330,-142,2.22,0,5,2,7,4.70,Critical System Pressure,Immediate Escalation Required,Prolonged Window Pressure
3,2023-01-24,7475,-128,1.98,0,5,0,4,3.49,High System Stress,Priority Monitoring Required,Prolonged Window Pressure
4,2023-01-25,7560,-139,1.14,0,5,0,4,3.48,High System Stress,Priority Monitoring Required,Prolonged Window Pressure
5,2023-01-29,7517,-292,-0.57,0,5,2,7,4.84,Critical System Pressure,Immediate Escalation Required,Prolonged Window Pressure
6,2023-01-30,7797,-167,3.72,0,5,3,7,5.11,Critical System Pressure,Immediate Escalation Required,Prolonged Window Pressure
7,2023-01-31,7839,-122,0.54,0,5,0,3,3.24,Moderate System Stress,Operational Watch Required,Prolonged Window Pressure
8,2023-02-01,7935,-204,1.22,0,4,0,3,3.08,Moderate System Stress,Operational Watch Required,Prolonged Window Pressure
9,2023-02-02,7892,-275,-0.54,0,4,0,4,3.36,Moderate System Stress,Operational Watch Required,Prolonged Window Pressure

Final Notebook 05 dataset tail:

,Date,total_system_load,net_daily_intake,care_load_growth_rate_pct,backlog_severity_score,volatility_pressure_score,pressure_spike_score,daily_strain_score,final_pressure_stress_score,final_pressure_stress_level,operational_response_category,primary_pressure_driver
710,2025-12-08,2467,5,0.57,1,0,0,3,0.91,Moderate System Stress,Operational Watch Required,Backlog Severity Pressure
711,2025-12-09,2473,-1,0.24,0,0,0,2,0.50,Early Pressure Watch,Early Warning Review,Daily Strain Pressure
712,2025-12-10,2493,-4,0.81,0,0,0,2,0.53,Early Pressure Watch,Early Warning Review,Daily Strain Pressure
713,2025-12-11,2484,-1,-0.36,0,0,0,2,0.51,Early Pressure Watch,Early Warning Review,Daily Strain Pressure
714,2025-12-14,2497,-4,0.52,0,0,0,2,0.52,Early Pressure Watch,Early Warning Review,Daily Strain Pressure
715,2025-12-15,2512,2,0.60,1,0,1,7,2.35,High System Stress,Priority Monitoring Required,Prolonged Window Pressure
716,2025-12-16,2522,6,0.40,1,0,0,3,1.20,Moderate System Stress,Operational Watch Required,Prolonged Window Pressure
717,2025-12-17,2512,1,-0.40,2,1,1,9,3.25,Critical System Pressure,Immediate Escalation Required,Prolonged Window Pressure
718,2025-12-18,2522,-10,0.40,0,0,0,2,0.52,Early Pressure Watch,Early Warning Review,Daily Strain Pressure
719,2025-12-21,2502,-3,-0.79,0,0,0,0,0.09,Normal Operating Pressure,Routine Monitoring,No Major Pressure Driver

Step 5H completed successfully.
Notebook 05 pressure and stress identification workflow is complete.
Final pressure and stress classification dataset is exported and ready for the next notebook stage.